
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser. 
 * Use it to get access to models, enums, and input types.
 * 
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from './internal/prismaNamespaceBrowser'
export { Prisma }
export * as $Enums from './enums'
export * from './enums';
/**
 * Model User
 * 
 */
export type User = Prisma.UserModel
/**
 * Model Conversation
 * 
 */
export type Conversation = Prisma.ConversationModel
/**
 * Model Message
 * 
 */
export type Message = Prisma.MessageModel
/**
 * Model Document
 * 
 */
export type Document = Prisma.DocumentModel
/**
 * Model DocumentChunk
 * 
 */
export type DocumentChunk = Prisma.DocumentChunkModel
/**
 * Model MessageSource
 * 
 */
export type MessageSource = Prisma.MessageSourceModel
/**
 * Model RetrievalMetric
 * 
 */
export type RetrievalMetric = Prisma.RetrievalMetricModel
/**
 * Model AgentTask
 * 
 */
export type AgentTask = Prisma.AgentTaskModel
/**
 * Model AgentLog
 * 
 */
export type AgentLog = Prisma.AgentLogModel
/**
 * Model AgentMetrics
 * 
 */
export type AgentMetrics = Prisma.AgentMetricsModel
/**
 * Model AgentRoutingLog
 * 
 */
export type AgentRoutingLog = Prisma.AgentRoutingLogModel
/**
 * Model ToolExecutionLog
 * 
 */
export type ToolExecutionLog = Prisma.ToolExecutionLogModel
/**
 * Model ToolConfiguration
 * 
 */
export type ToolConfiguration = Prisma.ToolConfigurationModel
/**
 * Model ConversationMemory
 * 
 */
export type ConversationMemory = Prisma.ConversationMemoryModel
/**
 * Model MetricsRecord
 * 
 */
export type MetricsRecord = Prisma.MetricsRecordModel
/**
 * Model SecurityAuditLog
 * 
 */
export type SecurityAuditLog = Prisma.SecurityAuditLogModel
