
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma. Through it you get access to all the models, enums, and input types.
 * If you're looking for something you can import in the client-side of your application, please refer to the `browser.ts` file instead.
 *
 * 🟢 You can import this file directly.
 */

import * as process from 'node:process'
import * as path from 'node:path'
import { fileURLToPath } from 'node:url'
globalThis['__dirname'] = path.dirname(fileURLToPath(import.meta.url))

import * as runtime from "@prisma/client/runtime/client"
import * as $Enums from "./enums"
import * as $Class from "./internal/class"
import * as Prisma from "./internal/prismaNamespace"

export * as $Enums from './enums'
export * from "./enums"
/**
 * ## Prisma Client
 * 
 * Type-safe database client for TypeScript
 * @example
 * ```
 * const prisma = new PrismaClient({
 *   adapter: new PrismaPg({ connectionString: process.env.DATABASE_URL })
 * })
 * // Fetch zero or more Users
 * const users = await prisma.user.findMany()
 * ```
 * 
 * Read more in our [docs](https://pris.ly/d/client).
 */
export const PrismaClient = $Class.getPrismaClientClass()
export type PrismaClient<LogOpts extends Prisma.LogLevel = never, OmitOpts extends Prisma.PrismaClientOptions["omit"] = Prisma.PrismaClientOptions["omit"], ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = $Class.PrismaClient<LogOpts, OmitOpts, ExtArgs>
export { Prisma }

/**
 * Model User
 * 
 */
export type User = Prisma.UserModel
/**
 * Model Conversation
 * 
 */
export type Conversation = Prisma.ConversationModel
/**
 * Model Message
 * 
 */
export type Message = Prisma.MessageModel
/**
 * Model Document
 * 
 */
export type Document = Prisma.DocumentModel
/**
 * Model DocumentChunk
 * 
 */
export type DocumentChunk = Prisma.DocumentChunkModel
/**
 * Model MessageSource
 * 
 */
export type MessageSource = Prisma.MessageSourceModel
/**
 * Model RetrievalMetric
 * 
 */
export type RetrievalMetric = Prisma.RetrievalMetricModel
/**
 * Model AgentTask
 * 
 */
export type AgentTask = Prisma.AgentTaskModel
/**
 * Model AgentLog
 * 
 */
export type AgentLog = Prisma.AgentLogModel
/**
 * Model AgentMetrics
 * 
 */
export type AgentMetrics = Prisma.AgentMetricsModel
/**
 * Model AgentRoutingLog
 * 
 */
export type AgentRoutingLog = Prisma.AgentRoutingLogModel
/**
 * Model ToolExecutionLog
 * 
 */
export type ToolExecutionLog = Prisma.ToolExecutionLogModel
/**
 * Model ToolConfiguration
 * 
 */
export type ToolConfiguration = Prisma.ToolConfigurationModel
/**
 * Model ConversationMemory
 * 
 */
export type ConversationMemory = Prisma.ConversationMemoryModel
/**
 * Model MetricsRecord
 * 
 */
export type MetricsRecord = Prisma.MetricsRecordModel
/**
 * Model SecurityAuditLog
 * 
 */
export type SecurityAuditLog = Prisma.SecurityAuditLogModel
