
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the client.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/client"
import type * as Prisma from "../models"
import { type PrismaClient } from "./class"

export type * from '../models'

export type DMMF = typeof runtime.DMMF

export type PrismaPromise<T> = runtime.Types.Public.PrismaPromise<T>

/**
 * Prisma Errors
 */

export const PrismaClientKnownRequestError = runtime.PrismaClientKnownRequestError
export type PrismaClientKnownRequestError = runtime.PrismaClientKnownRequestError

export const PrismaClientUnknownRequestError = runtime.PrismaClientUnknownRequestError
export type PrismaClientUnknownRequestError = runtime.PrismaClientUnknownRequestError

export const PrismaClientRustPanicError = runtime.PrismaClientRustPanicError
export type PrismaClientRustPanicError = runtime.PrismaClientRustPanicError

export const PrismaClientInitializationError = runtime.PrismaClientInitializationError
export type PrismaClientInitializationError = runtime.PrismaClientInitializationError

export const PrismaClientValidationError = runtime.PrismaClientValidationError
export type PrismaClientValidationError = runtime.PrismaClientValidationError

/**
 * Re-export of sql-template-tag
 */
export const sql = runtime.sqltag
export const empty = runtime.empty
export const join = runtime.join
export const raw = runtime.raw
export const Sql = runtime.Sql
export type Sql = runtime.Sql



/**
 * Decimal.js
 */
export const Decimal = runtime.Decimal
export type Decimal = runtime.Decimal

export type DecimalJsLike = runtime.DecimalJsLike

/**
* Extensions
*/
export type Extension = runtime.Types.Extensions.UserArgs
export const getExtensionContext = runtime.Extensions.getExtensionContext
export type Args<T, F extends runtime.Operation> = runtime.Types.Public.Args<T, F>
export type Payload<T, F extends runtime.Operation = never> = runtime.Types.Public.Payload<T, F>
export type Result<T, A, F extends runtime.Operation> = runtime.Types.Public.Result<T, A, F>
export type Exact<A, W> = runtime.Types.Public.Exact<A, W>

export type PrismaVersion = {
  client: string
  engine: string
}

/**
 * Prisma Client JS version: 7.4.2
 * Query Engine version: 94a226be1cf2967af2541cca5529f0f7ba866919
 */
export const prismaVersion: PrismaVersion = {
  client: "7.4.2",
  engine: "94a226be1cf2967af2541cca5529f0f7ba866919"
}

/**
 * Utility Types
 */

export type Bytes = runtime.Bytes
export type JsonObject = runtime.JsonObject
export type JsonArray = runtime.JsonArray
export type JsonValue = runtime.JsonValue
export type InputJsonObject = runtime.InputJsonObject
export type InputJsonArray = runtime.InputJsonArray
export type InputJsonValue = runtime.InputJsonValue


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


type SelectAndInclude = {
  select: any
  include: any
}

type SelectAndOmit = {
  select: any
  omit: any
}

/**
 * From T, pick a set of properties whose keys are in the union K
 */
type Prisma__Pick<T, K extends keyof T> = {
    [P in K]: T[P];
};

export type Enumerable<T> = T | Array<T>;

/**
 * Subset
 * @desc From `T` pick properties that exist in `U`. Simple version of Intersection
 */
export type Subset<T, U> = {
  [key in keyof T]: key extends keyof U ? T[key] : never;
};

/**
 * SelectSubset
 * @desc From `T` pick properties that exist in `U`. Simple version of Intersection.
 * Additionally, it validates, if both select and include are present. If the case, it errors.
 */
export type SelectSubset<T, U> = {
  [key in keyof T]: key extends keyof U ? T[key] : never
} &
  (T extends SelectAndInclude
    ? 'Please either choose `select` or `include`.'
    : T extends SelectAndOmit
      ? 'Please either choose `select` or `omit`.'
      : {})

/**
 * Subset + Intersection
 * @desc From `T` pick properties that exist in `U` and intersect `K`
 */
export type SubsetIntersection<T, U, K> = {
  [key in keyof T]: key extends keyof U ? T[key] : never
} &
  K

type Without<T, U> = { [P in Exclude<keyof T, keyof U>]?: never };

/**
 * XOR is needed to have a real mutually exclusive union type
 * https://stackoverflow.com/questions/42123407/does-typescript-support-mutually-exclusive-types
 */
export type XOR<T, U> =
  T extends object ?
  U extends object ?
    (Without<T, U> & U) | (Without<U, T> & T)
  : U : T


/**
 * Is T a Record?
 */
type IsObject<T extends any> = T extends Array<any>
? False
: T extends Date
? False
: T extends Uint8Array
? False
: T extends BigInt
? False
: T extends object
? True
: False


/**
 * If it's T[], return T
 */
export type UnEnumerate<T extends unknown> = T extends Array<infer U> ? U : T

/**
 * From ts-toolbelt
 */

type __Either<O extends object, K extends Key> = Omit<O, K> &
  {
    // Merge all but K
    [P in K]: Prisma__Pick<O, P & keyof O> // With K possibilities
  }[K]

type EitherStrict<O extends object, K extends Key> = Strict<__Either<O, K>>

type EitherLoose<O extends object, K extends Key> = ComputeRaw<__Either<O, K>>

type _Either<
  O extends object,
  K extends Key,
  strict extends Boolean
> = {
  1: EitherStrict<O, K>
  0: EitherLoose<O, K>
}[strict]

export type Either<
  O extends object,
  K extends Key,
  strict extends Boolean = 1
> = O extends unknown ? _Either<O, K, strict> : never

export type Union = any

export type PatchUndefined<O extends object, O1 extends object> = {
  [K in keyof O]: O[K] extends undefined ? At<O1, K> : O[K]
} & {}

/** Helper Types for "Merge" **/
export type IntersectOf<U extends Union> = (
  U extends unknown ? (k: U) => void : never
) extends (k: infer I) => void
  ? I
  : never

export type Overwrite<O extends object, O1 extends object> = {
    [K in keyof O]: K extends keyof O1 ? O1[K] : O[K];
} & {};

type _Merge<U extends object> = IntersectOf<Overwrite<U, {
    [K in keyof U]-?: At<U, K>;
}>>;

type Key = string | number | symbol;
type AtStrict<O extends object, K extends Key> = O[K & keyof O];
type AtLoose<O extends object, K extends Key> = O extends unknown ? AtStrict<O, K> : never;
export type At<O extends object, K extends Key, strict extends Boolean = 1> = {
    1: AtStrict<O, K>;
    0: AtLoose<O, K>;
}[strict];

export type ComputeRaw<A extends any> = A extends Function ? A : {
  [K in keyof A]: A[K];
} & {};

export type OptionalFlat<O> = {
  [K in keyof O]?: O[K];
} & {};

type _Record<K extends keyof any, T> = {
  [P in K]: T;
};

// cause typescript not to expand types and preserve names
type NoExpand<T> = T extends unknown ? T : never;

// this type assumes the passed object is entirely optional
export type AtLeast<O extends object, K extends string> = NoExpand<
  O extends unknown
  ? | (K extends keyof O ? { [P in K]: O[P] } & O : O)
    | {[P in keyof O as P extends K ? P : never]-?: O[P]} & O
  : never>;

type _Strict<U, _U = U> = U extends unknown ? U & OptionalFlat<_Record<Exclude<Keys<_U>, keyof U>, never>> : never;

export type Strict<U extends object> = ComputeRaw<_Strict<U>>;
/** End Helper Types for "Merge" **/

export type Merge<U extends object> = ComputeRaw<_Merge<Strict<U>>>;

export type Boolean = True | False

export type True = 1

export type False = 0

export type Not<B extends Boolean> = {
  0: 1
  1: 0
}[B]

export type Extends<A1 extends any, A2 extends any> = [A1] extends [never]
  ? 0 // anything `never` is false
  : A1 extends A2
  ? 1
  : 0

export type Has<U extends Union, U1 extends Union> = Not<
  Extends<Exclude<U1, U>, U1>
>

export type Or<B1 extends Boolean, B2 extends Boolean> = {
  0: {
    0: 0
    1: 1
  }
  1: {
    0: 1
    1: 1
  }
}[B1][B2]

export type Keys<U extends Union> = U extends unknown ? keyof U : never

export type GetScalarType<T, O> = O extends object ? {
  [P in keyof T]: P extends keyof O
    ? O[P]
    : never
} : never

type FieldPaths<
  T,
  U = Omit<T, '_avg' | '_sum' | '_count' | '_min' | '_max'>
> = IsObject<T> extends True ? U : T

export type GetHavingFields<T> = {
  [K in keyof T]: Or<
    Or<Extends<'OR', K>, Extends<'AND', K>>,
    Extends<'NOT', K>
  > extends True
    ? // infer is only needed to not hit TS limit
      // based on the brilliant idea of Pierre-Antoine Mills
      // https://github.com/microsoft/TypeScript/issues/30188#issuecomment-478938437
      T[K] extends infer TK
      ? GetHavingFields<UnEnumerate<TK> extends object ? Merge<UnEnumerate<TK>> : never>
      : never
    : {} extends FieldPaths<T[K]>
    ? never
    : K
}[keyof T]

/**
 * Convert tuple to union
 */
type _TupleToUnion<T> = T extends (infer E)[] ? E : never
type TupleToUnion<K extends readonly any[]> = _TupleToUnion<K>
export type MaybeTupleToUnion<T> = T extends any[] ? TupleToUnion<T> : T

/**
 * Like `Pick`, but additionally can also accept an array of keys
 */
export type PickEnumerable<T, K extends Enumerable<keyof T> | keyof T> = Prisma__Pick<T, MaybeTupleToUnion<K>>

/**
 * Exclude all keys with underscores
 */
export type ExcludeUnderscoreKeys<T extends string> = T extends `_${string}` ? never : T


export type FieldRef<Model, FieldType> = runtime.FieldRef<Model, FieldType>

type FieldRefInputType<Model, FieldType> = Model extends never ? never : FieldRef<Model, FieldType>


export const ModelName = {
  User: 'User',
  Conversation: 'Conversation',
  Message: 'Message',
  Document: 'Document',
  DocumentChunk: 'DocumentChunk',
  MessageSource: 'MessageSource',
  RetrievalMetric: 'RetrievalMetric',
  AgentTask: 'AgentTask',
  AgentLog: 'AgentLog',
  AgentMetrics: 'AgentMetrics',
  AgentRoutingLog: 'AgentRoutingLog',
  ToolExecutionLog: 'ToolExecutionLog',
  ToolConfiguration: 'ToolConfiguration',
  ConversationMemory: 'ConversationMemory',
  MetricsRecord: 'MetricsRecord',
  SecurityAuditLog: 'SecurityAuditLog'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]



export interface TypeMapCb<GlobalOmitOptions = {}> extends runtime.Types.Utils.Fn<{extArgs: runtime.Types.Extensions.InternalArgs }, runtime.Types.Utils.Record<string, any>> {
  returns: TypeMap<this['params']['extArgs'], GlobalOmitOptions>
}

export type TypeMap<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> = {
  globalOmitOptions: {
    omit: GlobalOmitOptions
  }
  meta: {
    modelProps: "user" | "conversation" | "message" | "document" | "documentChunk" | "messageSource" | "retrievalMetric" | "agentTask" | "agentLog" | "agentMetrics" | "agentRoutingLog" | "toolExecutionLog" | "toolConfiguration" | "conversationMemory" | "metricsRecord" | "securityAuditLog"
    txIsolationLevel: TransactionIsolationLevel
  }
  model: {
    User: {
      payload: Prisma.$UserPayload<ExtArgs>
      fields: Prisma.UserFieldRefs
      operations: {
        findUnique: {
          args: Prisma.UserFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.UserFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>
        }
        findFirst: {
          args: Prisma.UserFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.UserFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>
        }
        findMany: {
          args: Prisma.UserFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>[]
        }
        create: {
          args: Prisma.UserCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>
        }
        createMany: {
          args: Prisma.UserCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.UserCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>[]
        }
        delete: {
          args: Prisma.UserDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>
        }
        update: {
          args: Prisma.UserUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>
        }
        deleteMany: {
          args: Prisma.UserDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.UserUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.UserUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>[]
        }
        upsert: {
          args: Prisma.UserUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>
        }
        aggregate: {
          args: Prisma.UserAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateUser>
        }
        groupBy: {
          args: Prisma.UserGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.UserGroupByOutputType>[]
        }
        count: {
          args: Prisma.UserCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.UserCountAggregateOutputType> | number
        }
      }
    }
    Conversation: {
      payload: Prisma.$ConversationPayload<ExtArgs>
      fields: Prisma.ConversationFieldRefs
      operations: {
        findUnique: {
          args: Prisma.ConversationFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ConversationPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.ConversationFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ConversationPayload>
        }
        findFirst: {
          args: Prisma.ConversationFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ConversationPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.ConversationFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ConversationPayload>
        }
        findMany: {
          args: Prisma.ConversationFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ConversationPayload>[]
        }
        create: {
          args: Prisma.ConversationCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ConversationPayload>
        }
        createMany: {
          args: Prisma.ConversationCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.ConversationCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ConversationPayload>[]
        }
        delete: {
          args: Prisma.ConversationDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ConversationPayload>
        }
        update: {
          args: Prisma.ConversationUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ConversationPayload>
        }
        deleteMany: {
          args: Prisma.ConversationDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.ConversationUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.ConversationUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ConversationPayload>[]
        }
        upsert: {
          args: Prisma.ConversationUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ConversationPayload>
        }
        aggregate: {
          args: Prisma.ConversationAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateConversation>
        }
        groupBy: {
          args: Prisma.ConversationGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ConversationGroupByOutputType>[]
        }
        count: {
          args: Prisma.ConversationCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ConversationCountAggregateOutputType> | number
        }
      }
    }
    Message: {
      payload: Prisma.$MessagePayload<ExtArgs>
      fields: Prisma.MessageFieldRefs
      operations: {
        findUnique: {
          args: Prisma.MessageFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MessagePayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.MessageFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MessagePayload>
        }
        findFirst: {
          args: Prisma.MessageFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MessagePayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.MessageFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MessagePayload>
        }
        findMany: {
          args: Prisma.MessageFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MessagePayload>[]
        }
        create: {
          args: Prisma.MessageCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MessagePayload>
        }
        createMany: {
          args: Prisma.MessageCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.MessageCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MessagePayload>[]
        }
        delete: {
          args: Prisma.MessageDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MessagePayload>
        }
        update: {
          args: Prisma.MessageUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MessagePayload>
        }
        deleteMany: {
          args: Prisma.MessageDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.MessageUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.MessageUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MessagePayload>[]
        }
        upsert: {
          args: Prisma.MessageUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MessagePayload>
        }
        aggregate: {
          args: Prisma.MessageAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateMessage>
        }
        groupBy: {
          args: Prisma.MessageGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.MessageGroupByOutputType>[]
        }
        count: {
          args: Prisma.MessageCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.MessageCountAggregateOutputType> | number
        }
      }
    }
    Document: {
      payload: Prisma.$DocumentPayload<ExtArgs>
      fields: Prisma.DocumentFieldRefs
      operations: {
        findUnique: {
          args: Prisma.DocumentFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DocumentPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.DocumentFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DocumentPayload>
        }
        findFirst: {
          args: Prisma.DocumentFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DocumentPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.DocumentFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DocumentPayload>
        }
        findMany: {
          args: Prisma.DocumentFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DocumentPayload>[]
        }
        create: {
          args: Prisma.DocumentCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DocumentPayload>
        }
        createMany: {
          args: Prisma.DocumentCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.DocumentCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DocumentPayload>[]
        }
        delete: {
          args: Prisma.DocumentDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DocumentPayload>
        }
        update: {
          args: Prisma.DocumentUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DocumentPayload>
        }
        deleteMany: {
          args: Prisma.DocumentDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.DocumentUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.DocumentUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DocumentPayload>[]
        }
        upsert: {
          args: Prisma.DocumentUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DocumentPayload>
        }
        aggregate: {
          args: Prisma.DocumentAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateDocument>
        }
        groupBy: {
          args: Prisma.DocumentGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.DocumentGroupByOutputType>[]
        }
        count: {
          args: Prisma.DocumentCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.DocumentCountAggregateOutputType> | number
        }
      }
    }
    DocumentChunk: {
      payload: Prisma.$DocumentChunkPayload<ExtArgs>
      fields: Prisma.DocumentChunkFieldRefs
      operations: {
        findUnique: {
          args: Prisma.DocumentChunkFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DocumentChunkPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.DocumentChunkFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DocumentChunkPayload>
        }
        findFirst: {
          args: Prisma.DocumentChunkFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DocumentChunkPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.DocumentChunkFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DocumentChunkPayload>
        }
        findMany: {
          args: Prisma.DocumentChunkFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DocumentChunkPayload>[]
        }
        create: {
          args: Prisma.DocumentChunkCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DocumentChunkPayload>
        }
        createMany: {
          args: Prisma.DocumentChunkCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.DocumentChunkCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DocumentChunkPayload>[]
        }
        delete: {
          args: Prisma.DocumentChunkDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DocumentChunkPayload>
        }
        update: {
          args: Prisma.DocumentChunkUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DocumentChunkPayload>
        }
        deleteMany: {
          args: Prisma.DocumentChunkDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.DocumentChunkUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.DocumentChunkUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DocumentChunkPayload>[]
        }
        upsert: {
          args: Prisma.DocumentChunkUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DocumentChunkPayload>
        }
        aggregate: {
          args: Prisma.DocumentChunkAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateDocumentChunk>
        }
        groupBy: {
          args: Prisma.DocumentChunkGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.DocumentChunkGroupByOutputType>[]
        }
        count: {
          args: Prisma.DocumentChunkCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.DocumentChunkCountAggregateOutputType> | number
        }
      }
    }
    MessageSource: {
      payload: Prisma.$MessageSourcePayload<ExtArgs>
      fields: Prisma.MessageSourceFieldRefs
      operations: {
        findUnique: {
          args: Prisma.MessageSourceFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MessageSourcePayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.MessageSourceFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MessageSourcePayload>
        }
        findFirst: {
          args: Prisma.MessageSourceFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MessageSourcePayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.MessageSourceFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MessageSourcePayload>
        }
        findMany: {
          args: Prisma.MessageSourceFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MessageSourcePayload>[]
        }
        create: {
          args: Prisma.MessageSourceCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MessageSourcePayload>
        }
        createMany: {
          args: Prisma.MessageSourceCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.MessageSourceCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MessageSourcePayload>[]
        }
        delete: {
          args: Prisma.MessageSourceDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MessageSourcePayload>
        }
        update: {
          args: Prisma.MessageSourceUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MessageSourcePayload>
        }
        deleteMany: {
          args: Prisma.MessageSourceDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.MessageSourceUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.MessageSourceUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MessageSourcePayload>[]
        }
        upsert: {
          args: Prisma.MessageSourceUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MessageSourcePayload>
        }
        aggregate: {
          args: Prisma.MessageSourceAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateMessageSource>
        }
        groupBy: {
          args: Prisma.MessageSourceGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.MessageSourceGroupByOutputType>[]
        }
        count: {
          args: Prisma.MessageSourceCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.MessageSourceCountAggregateOutputType> | number
        }
      }
    }
    RetrievalMetric: {
      payload: Prisma.$RetrievalMetricPayload<ExtArgs>
      fields: Prisma.RetrievalMetricFieldRefs
      operations: {
        findUnique: {
          args: Prisma.RetrievalMetricFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RetrievalMetricPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.RetrievalMetricFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RetrievalMetricPayload>
        }
        findFirst: {
          args: Prisma.RetrievalMetricFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RetrievalMetricPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.RetrievalMetricFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RetrievalMetricPayload>
        }
        findMany: {
          args: Prisma.RetrievalMetricFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RetrievalMetricPayload>[]
        }
        create: {
          args: Prisma.RetrievalMetricCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RetrievalMetricPayload>
        }
        createMany: {
          args: Prisma.RetrievalMetricCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.RetrievalMetricCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RetrievalMetricPayload>[]
        }
        delete: {
          args: Prisma.RetrievalMetricDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RetrievalMetricPayload>
        }
        update: {
          args: Prisma.RetrievalMetricUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RetrievalMetricPayload>
        }
        deleteMany: {
          args: Prisma.RetrievalMetricDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.RetrievalMetricUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.RetrievalMetricUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RetrievalMetricPayload>[]
        }
        upsert: {
          args: Prisma.RetrievalMetricUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RetrievalMetricPayload>
        }
        aggregate: {
          args: Prisma.RetrievalMetricAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateRetrievalMetric>
        }
        groupBy: {
          args: Prisma.RetrievalMetricGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.RetrievalMetricGroupByOutputType>[]
        }
        count: {
          args: Prisma.RetrievalMetricCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.RetrievalMetricCountAggregateOutputType> | number
        }
      }
    }
    AgentTask: {
      payload: Prisma.$AgentTaskPayload<ExtArgs>
      fields: Prisma.AgentTaskFieldRefs
      operations: {
        findUnique: {
          args: Prisma.AgentTaskFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AgentTaskPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.AgentTaskFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AgentTaskPayload>
        }
        findFirst: {
          args: Prisma.AgentTaskFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AgentTaskPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.AgentTaskFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AgentTaskPayload>
        }
        findMany: {
          args: Prisma.AgentTaskFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AgentTaskPayload>[]
        }
        create: {
          args: Prisma.AgentTaskCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AgentTaskPayload>
        }
        createMany: {
          args: Prisma.AgentTaskCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.AgentTaskCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AgentTaskPayload>[]
        }
        delete: {
          args: Prisma.AgentTaskDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AgentTaskPayload>
        }
        update: {
          args: Prisma.AgentTaskUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AgentTaskPayload>
        }
        deleteMany: {
          args: Prisma.AgentTaskDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.AgentTaskUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.AgentTaskUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AgentTaskPayload>[]
        }
        upsert: {
          args: Prisma.AgentTaskUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AgentTaskPayload>
        }
        aggregate: {
          args: Prisma.AgentTaskAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateAgentTask>
        }
        groupBy: {
          args: Prisma.AgentTaskGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AgentTaskGroupByOutputType>[]
        }
        count: {
          args: Prisma.AgentTaskCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AgentTaskCountAggregateOutputType> | number
        }
      }
    }
    AgentLog: {
      payload: Prisma.$AgentLogPayload<ExtArgs>
      fields: Prisma.AgentLogFieldRefs
      operations: {
        findUnique: {
          args: Prisma.AgentLogFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AgentLogPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.AgentLogFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AgentLogPayload>
        }
        findFirst: {
          args: Prisma.AgentLogFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AgentLogPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.AgentLogFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AgentLogPayload>
        }
        findMany: {
          args: Prisma.AgentLogFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AgentLogPayload>[]
        }
        create: {
          args: Prisma.AgentLogCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AgentLogPayload>
        }
        createMany: {
          args: Prisma.AgentLogCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.AgentLogCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AgentLogPayload>[]
        }
        delete: {
          args: Prisma.AgentLogDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AgentLogPayload>
        }
        update: {
          args: Prisma.AgentLogUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AgentLogPayload>
        }
        deleteMany: {
          args: Prisma.AgentLogDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.AgentLogUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.AgentLogUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AgentLogPayload>[]
        }
        upsert: {
          args: Prisma.AgentLogUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AgentLogPayload>
        }
        aggregate: {
          args: Prisma.AgentLogAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateAgentLog>
        }
        groupBy: {
          args: Prisma.AgentLogGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AgentLogGroupByOutputType>[]
        }
        count: {
          args: Prisma.AgentLogCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AgentLogCountAggregateOutputType> | number
        }
      }
    }
    AgentMetrics: {
      payload: Prisma.$AgentMetricsPayload<ExtArgs>
      fields: Prisma.AgentMetricsFieldRefs
      operations: {
        findUnique: {
          args: Prisma.AgentMetricsFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AgentMetricsPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.AgentMetricsFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AgentMetricsPayload>
        }
        findFirst: {
          args: Prisma.AgentMetricsFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AgentMetricsPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.AgentMetricsFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AgentMetricsPayload>
        }
        findMany: {
          args: Prisma.AgentMetricsFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AgentMetricsPayload>[]
        }
        create: {
          args: Prisma.AgentMetricsCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AgentMetricsPayload>
        }
        createMany: {
          args: Prisma.AgentMetricsCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.AgentMetricsCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AgentMetricsPayload>[]
        }
        delete: {
          args: Prisma.AgentMetricsDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AgentMetricsPayload>
        }
        update: {
          args: Prisma.AgentMetricsUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AgentMetricsPayload>
        }
        deleteMany: {
          args: Prisma.AgentMetricsDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.AgentMetricsUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.AgentMetricsUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AgentMetricsPayload>[]
        }
        upsert: {
          args: Prisma.AgentMetricsUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AgentMetricsPayload>
        }
        aggregate: {
          args: Prisma.AgentMetricsAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateAgentMetrics>
        }
        groupBy: {
          args: Prisma.AgentMetricsGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AgentMetricsGroupByOutputType>[]
        }
        count: {
          args: Prisma.AgentMetricsCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AgentMetricsCountAggregateOutputType> | number
        }
      }
    }
    AgentRoutingLog: {
      payload: Prisma.$AgentRoutingLogPayload<ExtArgs>
      fields: Prisma.AgentRoutingLogFieldRefs
      operations: {
        findUnique: {
          args: Prisma.AgentRoutingLogFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AgentRoutingLogPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.AgentRoutingLogFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AgentRoutingLogPayload>
        }
        findFirst: {
          args: Prisma.AgentRoutingLogFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AgentRoutingLogPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.AgentRoutingLogFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AgentRoutingLogPayload>
        }
        findMany: {
          args: Prisma.AgentRoutingLogFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AgentRoutingLogPayload>[]
        }
        create: {
          args: Prisma.AgentRoutingLogCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AgentRoutingLogPayload>
        }
        createMany: {
          args: Prisma.AgentRoutingLogCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.AgentRoutingLogCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AgentRoutingLogPayload>[]
        }
        delete: {
          args: Prisma.AgentRoutingLogDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AgentRoutingLogPayload>
        }
        update: {
          args: Prisma.AgentRoutingLogUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AgentRoutingLogPayload>
        }
        deleteMany: {
          args: Prisma.AgentRoutingLogDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.AgentRoutingLogUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.AgentRoutingLogUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AgentRoutingLogPayload>[]
        }
        upsert: {
          args: Prisma.AgentRoutingLogUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AgentRoutingLogPayload>
        }
        aggregate: {
          args: Prisma.AgentRoutingLogAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateAgentRoutingLog>
        }
        groupBy: {
          args: Prisma.AgentRoutingLogGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AgentRoutingLogGroupByOutputType>[]
        }
        count: {
          args: Prisma.AgentRoutingLogCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AgentRoutingLogCountAggregateOutputType> | number
        }
      }
    }
    ToolExecutionLog: {
      payload: Prisma.$ToolExecutionLogPayload<ExtArgs>
      fields: Prisma.ToolExecutionLogFieldRefs
      operations: {
        findUnique: {
          args: Prisma.ToolExecutionLogFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ToolExecutionLogPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.ToolExecutionLogFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ToolExecutionLogPayload>
        }
        findFirst: {
          args: Prisma.ToolExecutionLogFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ToolExecutionLogPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.ToolExecutionLogFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ToolExecutionLogPayload>
        }
        findMany: {
          args: Prisma.ToolExecutionLogFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ToolExecutionLogPayload>[]
        }
        create: {
          args: Prisma.ToolExecutionLogCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ToolExecutionLogPayload>
        }
        createMany: {
          args: Prisma.ToolExecutionLogCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.ToolExecutionLogCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ToolExecutionLogPayload>[]
        }
        delete: {
          args: Prisma.ToolExecutionLogDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ToolExecutionLogPayload>
        }
        update: {
          args: Prisma.ToolExecutionLogUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ToolExecutionLogPayload>
        }
        deleteMany: {
          args: Prisma.ToolExecutionLogDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.ToolExecutionLogUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.ToolExecutionLogUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ToolExecutionLogPayload>[]
        }
        upsert: {
          args: Prisma.ToolExecutionLogUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ToolExecutionLogPayload>
        }
        aggregate: {
          args: Prisma.ToolExecutionLogAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateToolExecutionLog>
        }
        groupBy: {
          args: Prisma.ToolExecutionLogGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ToolExecutionLogGroupByOutputType>[]
        }
        count: {
          args: Prisma.ToolExecutionLogCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ToolExecutionLogCountAggregateOutputType> | number
        }
      }
    }
    ToolConfiguration: {
      payload: Prisma.$ToolConfigurationPayload<ExtArgs>
      fields: Prisma.ToolConfigurationFieldRefs
      operations: {
        findUnique: {
          args: Prisma.ToolConfigurationFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ToolConfigurationPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.ToolConfigurationFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ToolConfigurationPayload>
        }
        findFirst: {
          args: Prisma.ToolConfigurationFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ToolConfigurationPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.ToolConfigurationFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ToolConfigurationPayload>
        }
        findMany: {
          args: Prisma.ToolConfigurationFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ToolConfigurationPayload>[]
        }
        create: {
          args: Prisma.ToolConfigurationCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ToolConfigurationPayload>
        }
        createMany: {
          args: Prisma.ToolConfigurationCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.ToolConfigurationCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ToolConfigurationPayload>[]
        }
        delete: {
          args: Prisma.ToolConfigurationDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ToolConfigurationPayload>
        }
        update: {
          args: Prisma.ToolConfigurationUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ToolConfigurationPayload>
        }
        deleteMany: {
          args: Prisma.ToolConfigurationDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.ToolConfigurationUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.ToolConfigurationUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ToolConfigurationPayload>[]
        }
        upsert: {
          args: Prisma.ToolConfigurationUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ToolConfigurationPayload>
        }
        aggregate: {
          args: Prisma.ToolConfigurationAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateToolConfiguration>
        }
        groupBy: {
          args: Prisma.ToolConfigurationGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ToolConfigurationGroupByOutputType>[]
        }
        count: {
          args: Prisma.ToolConfigurationCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ToolConfigurationCountAggregateOutputType> | number
        }
      }
    }
    ConversationMemory: {
      payload: Prisma.$ConversationMemoryPayload<ExtArgs>
      fields: Prisma.ConversationMemoryFieldRefs
      operations: {
        findUnique: {
          args: Prisma.ConversationMemoryFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ConversationMemoryPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.ConversationMemoryFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ConversationMemoryPayload>
        }
        findFirst: {
          args: Prisma.ConversationMemoryFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ConversationMemoryPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.ConversationMemoryFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ConversationMemoryPayload>
        }
        findMany: {
          args: Prisma.ConversationMemoryFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ConversationMemoryPayload>[]
        }
        create: {
          args: Prisma.ConversationMemoryCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ConversationMemoryPayload>
        }
        createMany: {
          args: Prisma.ConversationMemoryCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.ConversationMemoryCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ConversationMemoryPayload>[]
        }
        delete: {
          args: Prisma.ConversationMemoryDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ConversationMemoryPayload>
        }
        update: {
          args: Prisma.ConversationMemoryUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ConversationMemoryPayload>
        }
        deleteMany: {
          args: Prisma.ConversationMemoryDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.ConversationMemoryUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.ConversationMemoryUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ConversationMemoryPayload>[]
        }
        upsert: {
          args: Prisma.ConversationMemoryUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ConversationMemoryPayload>
        }
        aggregate: {
          args: Prisma.ConversationMemoryAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateConversationMemory>
        }
        groupBy: {
          args: Prisma.ConversationMemoryGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ConversationMemoryGroupByOutputType>[]
        }
        count: {
          args: Prisma.ConversationMemoryCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ConversationMemoryCountAggregateOutputType> | number
        }
      }
    }
    MetricsRecord: {
      payload: Prisma.$MetricsRecordPayload<ExtArgs>
      fields: Prisma.MetricsRecordFieldRefs
      operations: {
        findUnique: {
          args: Prisma.MetricsRecordFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MetricsRecordPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.MetricsRecordFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MetricsRecordPayload>
        }
        findFirst: {
          args: Prisma.MetricsRecordFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MetricsRecordPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.MetricsRecordFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MetricsRecordPayload>
        }
        findMany: {
          args: Prisma.MetricsRecordFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MetricsRecordPayload>[]
        }
        create: {
          args: Prisma.MetricsRecordCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MetricsRecordPayload>
        }
        createMany: {
          args: Prisma.MetricsRecordCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.MetricsRecordCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MetricsRecordPayload>[]
        }
        delete: {
          args: Prisma.MetricsRecordDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MetricsRecordPayload>
        }
        update: {
          args: Prisma.MetricsRecordUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MetricsRecordPayload>
        }
        deleteMany: {
          args: Prisma.MetricsRecordDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.MetricsRecordUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.MetricsRecordUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MetricsRecordPayload>[]
        }
        upsert: {
          args: Prisma.MetricsRecordUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MetricsRecordPayload>
        }
        aggregate: {
          args: Prisma.MetricsRecordAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateMetricsRecord>
        }
        groupBy: {
          args: Prisma.MetricsRecordGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.MetricsRecordGroupByOutputType>[]
        }
        count: {
          args: Prisma.MetricsRecordCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.MetricsRecordCountAggregateOutputType> | number
        }
      }
    }
    SecurityAuditLog: {
      payload: Prisma.$SecurityAuditLogPayload<ExtArgs>
      fields: Prisma.SecurityAuditLogFieldRefs
      operations: {
        findUnique: {
          args: Prisma.SecurityAuditLogFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SecurityAuditLogPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.SecurityAuditLogFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SecurityAuditLogPayload>
        }
        findFirst: {
          args: Prisma.SecurityAuditLogFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SecurityAuditLogPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.SecurityAuditLogFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SecurityAuditLogPayload>
        }
        findMany: {
          args: Prisma.SecurityAuditLogFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SecurityAuditLogPayload>[]
        }
        create: {
          args: Prisma.SecurityAuditLogCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SecurityAuditLogPayload>
        }
        createMany: {
          args: Prisma.SecurityAuditLogCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.SecurityAuditLogCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SecurityAuditLogPayload>[]
        }
        delete: {
          args: Prisma.SecurityAuditLogDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SecurityAuditLogPayload>
        }
        update: {
          args: Prisma.SecurityAuditLogUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SecurityAuditLogPayload>
        }
        deleteMany: {
          args: Prisma.SecurityAuditLogDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.SecurityAuditLogUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.SecurityAuditLogUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SecurityAuditLogPayload>[]
        }
        upsert: {
          args: Prisma.SecurityAuditLogUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SecurityAuditLogPayload>
        }
        aggregate: {
          args: Prisma.SecurityAuditLogAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateSecurityAuditLog>
        }
        groupBy: {
          args: Prisma.SecurityAuditLogGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.SecurityAuditLogGroupByOutputType>[]
        }
        count: {
          args: Prisma.SecurityAuditLogCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.SecurityAuditLogCountAggregateOutputType> | number
        }
      }
    }
  }
} & {
  other: {
    payload: any
    operations: {
      $executeRaw: {
        args: [query: TemplateStringsArray | Sql, ...values: any[]],
        result: any
      }
      $executeRawUnsafe: {
        args: [query: string, ...values: any[]],
        result: any
      }
      $queryRaw: {
        args: [query: TemplateStringsArray | Sql, ...values: any[]],
        result: any
      }
      $queryRawUnsafe: {
        args: [query: string, ...values: any[]],
        result: any
      }
    }
  }
}

/**
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const UserScalarFieldEnum = {
  id: 'id',
  email: 'email',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  rateLimitKey: 'rateLimitKey'
} as const

export type UserScalarFieldEnum = (typeof UserScalarFieldEnum)[keyof typeof UserScalarFieldEnum]


export const ConversationScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  title: 'title',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type ConversationScalarFieldEnum = (typeof ConversationScalarFieldEnum)[keyof typeof ConversationScalarFieldEnum]


export const MessageScalarFieldEnum = {
  id: 'id',
  conversationId: 'conversationId',
  role: 'role',
  content: 'content',
  tokenUsage: 'tokenUsage',
  latency: 'latency',
  createdAt: 'createdAt'
} as const

export type MessageScalarFieldEnum = (typeof MessageScalarFieldEnum)[keyof typeof MessageScalarFieldEnum]


export const DocumentScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  name: 'name',
  type: 'type',
  originalPath: 'originalPath',
  metadata: 'metadata',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type DocumentScalarFieldEnum = (typeof DocumentScalarFieldEnum)[keyof typeof DocumentScalarFieldEnum]


export const DocumentChunkScalarFieldEnum = {
  id: 'id',
  documentId: 'documentId',
  chunkIndex: 'chunkIndex',
  content: 'content',
  embedding: 'embedding',
  createdAt: 'createdAt'
} as const

export type DocumentChunkScalarFieldEnum = (typeof DocumentChunkScalarFieldEnum)[keyof typeof DocumentChunkScalarFieldEnum]


export const MessageSourceScalarFieldEnum = {
  id: 'id',
  messageId: 'messageId',
  documentId: 'documentId',
  chunkId: 'chunkId',
  rankPosition: 'rankPosition',
  similarity: 'similarity',
  createdAt: 'createdAt'
} as const

export type MessageSourceScalarFieldEnum = (typeof MessageSourceScalarFieldEnum)[keyof typeof MessageSourceScalarFieldEnum]


export const RetrievalMetricScalarFieldEnum = {
  id: 'id',
  documentId: 'documentId',
  chunkId: 'chunkId',
  userId: 'userId',
  hitCount: 'hitCount',
  lastRetrieved: 'lastRetrieved',
  createdAt: 'createdAt'
} as const

export type RetrievalMetricScalarFieldEnum = (typeof RetrievalMetricScalarFieldEnum)[keyof typeof RetrievalMetricScalarFieldEnum]


export const AgentTaskScalarFieldEnum = {
  id: 'id',
  conversationId: 'conversationId',
  parentTaskId: 'parentTaskId',
  originalQuery: 'originalQuery',
  taskDescription: 'taskDescription',
  taskType: 'taskType',
  status: 'status',
  result: 'result',
  metadata: 'metadata',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type AgentTaskScalarFieldEnum = (typeof AgentTaskScalarFieldEnum)[keyof typeof AgentTaskScalarFieldEnum]


export const AgentLogScalarFieldEnum = {
  id: 'id',
  conversationId: 'conversationId',
  agentType: 'agentType',
  agentName: 'agentName',
  input: 'input',
  output: 'output',
  status: 'status',
  errorMessage: 'errorMessage',
  executionTime: 'executionTime',
  tokenUsage: 'tokenUsage',
  metadata: 'metadata',
  createdAt: 'createdAt'
} as const

export type AgentLogScalarFieldEnum = (typeof AgentLogScalarFieldEnum)[keyof typeof AgentLogScalarFieldEnum]


export const AgentMetricsScalarFieldEnum = {
  id: 'id',
  agentType: 'agentType',
  totalExecutions: 'totalExecutions',
  successCount: 'successCount',
  errorCount: 'errorCount',
  totalExecutionTime: 'totalExecutionTime',
  averageExecutionTime: 'averageExecutionTime',
  averageTokenUsage: 'averageTokenUsage',
  routingFrequency: 'routingFrequency',
  lastExecution: 'lastExecution',
  createdAt: 'createdAt'
} as const

export type AgentMetricsScalarFieldEnum = (typeof AgentMetricsScalarFieldEnum)[keyof typeof AgentMetricsScalarFieldEnum]


export const AgentRoutingLogScalarFieldEnum = {
  id: 'id',
  conversationId: 'conversationId',
  query: 'query',
  detectedIntent: 'detectedIntent',
  selectedAgent: 'selectedAgent',
  confidence: 'confidence',
  reasoning: 'reasoning',
  createdAt: 'createdAt'
} as const

export type AgentRoutingLogScalarFieldEnum = (typeof AgentRoutingLogScalarFieldEnum)[keyof typeof AgentRoutingLogScalarFieldEnum]


export const ToolExecutionLogScalarFieldEnum = {
  id: 'id',
  conversationId: 'conversationId',
  userId: 'userId',
  toolName: 'toolName',
  toolCallId: 'toolCallId',
  paramsHash: 'paramsHash',
  executionTime: 'executionTime',
  resultHash: 'resultHash',
  success: 'success',
  errorMessage: 'errorMessage',
  resultSize: 'resultSize',
  cacheHit: 'cacheHit',
  metadata: 'metadata',
  createdAt: 'createdAt'
} as const

export type ToolExecutionLogScalarFieldEnum = (typeof ToolExecutionLogScalarFieldEnum)[keyof typeof ToolExecutionLogScalarFieldEnum]


export const ToolConfigurationScalarFieldEnum = {
  id: 'id',
  globalEnabled: 'globalEnabled',
  toolSettings: 'toolSettings',
  loggingConfig: 'loggingConfig',
  securityConfig: 'securityConfig',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type ToolConfigurationScalarFieldEnum = (typeof ToolConfigurationScalarFieldEnum)[keyof typeof ToolConfigurationScalarFieldEnum]


export const ConversationMemoryScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  conversationId: 'conversationId',
  summary: 'summary',
  embedding: 'embedding',
  tokenCount: 'tokenCount',
  messageCount: 'messageCount',
  keyTopics: 'keyTopics',
  metadata: 'metadata',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type ConversationMemoryScalarFieldEnum = (typeof ConversationMemoryScalarFieldEnum)[keyof typeof ConversationMemoryScalarFieldEnum]


export const MetricsRecordScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  conversationId: 'conversationId',
  tokenCount: 'tokenCount',
  latency: 'latency',
  agentType: 'agentType',
  toolUsed: 'toolUsed',
  modelUsed: 'modelUsed',
  inputTokens: 'inputTokens',
  outputTokens: 'outputTokens',
  errorOccurred: 'errorOccurred',
  errorType: 'errorType',
  retrievalHit: 'retrievalHit',
  metadata: 'metadata',
  createdAt: 'createdAt'
} as const

export type MetricsRecordScalarFieldEnum = (typeof MetricsRecordScalarFieldEnum)[keyof typeof MetricsRecordScalarFieldEnum]


export const SecurityAuditLogScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  conversationId: 'conversationId',
  threatType: 'threatType',
  severity: 'severity',
  description: 'description',
  suspicious_input: 'suspicious_input',
  action_taken: 'action_taken',
  is_blocked: 'is_blocked',
  metadata: 'metadata',
  createdAt: 'createdAt'
} as const

export type SecurityAuditLogScalarFieldEnum = (typeof SecurityAuditLogScalarFieldEnum)[keyof typeof SecurityAuditLogScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]



/**
 * Field references
 */


/**
 * Reference to a field of type 'String'
 */
export type StringFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'String'>
    


/**
 * Reference to a field of type 'DateTime'
 */
export type DateTimeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'DateTime'>
    


/**
 * Reference to a field of type 'Int'
 */
export type IntFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Int'>
    


/**
 * Reference to a field of type 'Bytes'
 */
export type BytesFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Bytes'>
    


/**
 * Reference to a field of type 'Float'
 */
export type FloatFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Float'>
    


/**
 * Reference to a field of type 'Boolean'
 */
export type BooleanFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Boolean'>
    

/**
 * Batch Payload for updateMany & deleteMany & createMany
 */
export type BatchPayload = {
  count: number
}

export const defineExtension = runtime.Extensions.defineExtension as unknown as runtime.Types.Extensions.ExtendsHook<"define", TypeMapCb, runtime.Types.Extensions.DefaultArgs>
export type DefaultPrismaClient = PrismaClient
export type ErrorFormat = 'pretty' | 'colorless' | 'minimal'
export type PrismaClientOptions = ({
  /**
   * Instance of a Driver Adapter, e.g., like one provided by `@prisma/adapter-pg`.
   */
  adapter: runtime.SqlDriverAdapterFactory
  accelerateUrl?: never
} | {
  /**
   * Prisma Accelerate URL allowing the client to connect through Accelerate instead of a direct database.
   */
  accelerateUrl: string
  adapter?: never
}) & {
  /**
   * @default "colorless"
   */
  errorFormat?: ErrorFormat
  /**
   * @example
   * ```
   * // Shorthand for `emit: 'stdout'`
   * log: ['query', 'info', 'warn', 'error']
   * 
   * // Emit as events only
   * log: [
   *   { emit: 'event', level: 'query' },
   *   { emit: 'event', level: 'info' },
   *   { emit: 'event', level: 'warn' }
   *   { emit: 'event', level: 'error' }
   * ]
   * 
   * / Emit as events and log to stdout
   * og: [
   *  { emit: 'stdout', level: 'query' },
   *  { emit: 'stdout', level: 'info' },
   *  { emit: 'stdout', level: 'warn' }
   *  { emit: 'stdout', level: 'error' }
   * 
   * ```
   * Read more in our [docs](https://pris.ly/d/logging).
   */
  log?: (LogLevel | LogDefinition)[]
  /**
   * The default values for transactionOptions
   * maxWait ?= 2000
   * timeout ?= 5000
   */
  transactionOptions?: {
    maxWait?: number
    timeout?: number
    isolationLevel?: TransactionIsolationLevel
  }
  /**
   * Global configuration for omitting model fields by default.
   * 
   * @example
   * ```
   * const prisma = new PrismaClient({
   *   omit: {
   *     user: {
   *       password: true
   *     }
   *   }
   * })
   * ```
   */
  omit?: GlobalOmitConfig
  /**
   * SQL commenter plugins that add metadata to SQL queries as comments.
   * Comments follow the sqlcommenter format: https://google.github.io/sqlcommenter/
   * 
   * @example
   * ```
   * const prisma = new PrismaClient({
   *   adapter,
   *   comments: [
   *     traceContext(),
   *     queryInsights(),
   *   ],
   * })
   * ```
   */
  comments?: runtime.SqlCommenterPlugin[]
}
export type GlobalOmitConfig = {
  user?: Prisma.UserOmit
  conversation?: Prisma.ConversationOmit
  message?: Prisma.MessageOmit
  document?: Prisma.DocumentOmit
  documentChunk?: Prisma.DocumentChunkOmit
  messageSource?: Prisma.MessageSourceOmit
  retrievalMetric?: Prisma.RetrievalMetricOmit
  agentTask?: Prisma.AgentTaskOmit
  agentLog?: Prisma.AgentLogOmit
  agentMetrics?: Prisma.AgentMetricsOmit
  agentRoutingLog?: Prisma.AgentRoutingLogOmit
  toolExecutionLog?: Prisma.ToolExecutionLogOmit
  toolConfiguration?: Prisma.ToolConfigurationOmit
  conversationMemory?: Prisma.ConversationMemoryOmit
  metricsRecord?: Prisma.MetricsRecordOmit
  securityAuditLog?: Prisma.SecurityAuditLogOmit
}

/* Types for Logging */
export type LogLevel = 'info' | 'query' | 'warn' | 'error'
export type LogDefinition = {
  level: LogLevel
  emit: 'stdout' | 'event'
}

export type CheckIsLogLevel<T> = T extends LogLevel ? T : never;

export type GetLogType<T> = CheckIsLogLevel<
  T extends LogDefinition ? T['level'] : T
>;

export type GetEvents<T extends any[]> = T extends Array<LogLevel | LogDefinition>
  ? GetLogType<T[number]>
  : never;

export type QueryEvent = {
  timestamp: Date
  query: string
  params: string
  duration: number
  target: string
}

export type LogEvent = {
  timestamp: Date
  message: string
  target: string
}
/* End Types for Logging */


export type PrismaAction =
  | 'findUnique'
  | 'findUniqueOrThrow'
  | 'findMany'
  | 'findFirst'
  | 'findFirstOrThrow'
  | 'create'
  | 'createMany'
  | 'createManyAndReturn'
  | 'update'
  | 'updateMany'
  | 'updateManyAndReturn'
  | 'upsert'
  | 'delete'
  | 'deleteMany'
  | 'executeRaw'
  | 'queryRaw'
  | 'aggregate'
  | 'count'
  | 'runCommandRaw'
  | 'findRaw'
  | 'groupBy'

/**
 * `PrismaClient` proxy available in interactive transactions.
 */
export type TransactionClient = Omit<DefaultPrismaClient, runtime.ITXClientDenyList>

