
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `AgentMetrics` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model AgentMetrics
 * 
 */
export type AgentMetricsModel = runtime.Types.Result.DefaultSelection<Prisma.$AgentMetricsPayload>

export type AggregateAgentMetrics = {
  _count: AgentMetricsCountAggregateOutputType | null
  _avg: AgentMetricsAvgAggregateOutputType | null
  _sum: AgentMetricsSumAggregateOutputType | null
  _min: AgentMetricsMinAggregateOutputType | null
  _max: AgentMetricsMaxAggregateOutputType | null
}

export type AgentMetricsAvgAggregateOutputType = {
  totalExecutions: number | null
  successCount: number | null
  errorCount: number | null
  totalExecutionTime: number | null
  averageExecutionTime: number | null
  averageTokenUsage: number | null
  routingFrequency: number | null
}

export type AgentMetricsSumAggregateOutputType = {
  totalExecutions: number | null
  successCount: number | null
  errorCount: number | null
  totalExecutionTime: number | null
  averageExecutionTime: number | null
  averageTokenUsage: number | null
  routingFrequency: number | null
}

export type AgentMetricsMinAggregateOutputType = {
  id: string | null
  agentType: string | null
  totalExecutions: number | null
  successCount: number | null
  errorCount: number | null
  totalExecutionTime: number | null
  averageExecutionTime: number | null
  averageTokenUsage: number | null
  routingFrequency: number | null
  lastExecution: Date | null
  createdAt: Date | null
}

export type AgentMetricsMaxAggregateOutputType = {
  id: string | null
  agentType: string | null
  totalExecutions: number | null
  successCount: number | null
  errorCount: number | null
  totalExecutionTime: number | null
  averageExecutionTime: number | null
  averageTokenUsage: number | null
  routingFrequency: number | null
  lastExecution: Date | null
  createdAt: Date | null
}

export type AgentMetricsCountAggregateOutputType = {
  id: number
  agentType: number
  totalExecutions: number
  successCount: number
  errorCount: number
  totalExecutionTime: number
  averageExecutionTime: number
  averageTokenUsage: number
  routingFrequency: number
  lastExecution: number
  createdAt: number
  _all: number
}


export type AgentMetricsAvgAggregateInputType = {
  totalExecutions?: true
  successCount?: true
  errorCount?: true
  totalExecutionTime?: true
  averageExecutionTime?: true
  averageTokenUsage?: true
  routingFrequency?: true
}

export type AgentMetricsSumAggregateInputType = {
  totalExecutions?: true
  successCount?: true
  errorCount?: true
  totalExecutionTime?: true
  averageExecutionTime?: true
  averageTokenUsage?: true
  routingFrequency?: true
}

export type AgentMetricsMinAggregateInputType = {
  id?: true
  agentType?: true
  totalExecutions?: true
  successCount?: true
  errorCount?: true
  totalExecutionTime?: true
  averageExecutionTime?: true
  averageTokenUsage?: true
  routingFrequency?: true
  lastExecution?: true
  createdAt?: true
}

export type AgentMetricsMaxAggregateInputType = {
  id?: true
  agentType?: true
  totalExecutions?: true
  successCount?: true
  errorCount?: true
  totalExecutionTime?: true
  averageExecutionTime?: true
  averageTokenUsage?: true
  routingFrequency?: true
  lastExecution?: true
  createdAt?: true
}

export type AgentMetricsCountAggregateInputType = {
  id?: true
  agentType?: true
  totalExecutions?: true
  successCount?: true
  errorCount?: true
  totalExecutionTime?: true
  averageExecutionTime?: true
  averageTokenUsage?: true
  routingFrequency?: true
  lastExecution?: true
  createdAt?: true
  _all?: true
}

export type AgentMetricsAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which AgentMetrics to aggregate.
   */
  where?: Prisma.AgentMetricsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AgentMetrics to fetch.
   */
  orderBy?: Prisma.AgentMetricsOrderByWithRelationInput | Prisma.AgentMetricsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.AgentMetricsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AgentMetrics from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AgentMetrics.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned AgentMetrics
  **/
  _count?: true | AgentMetricsCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: AgentMetricsAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: AgentMetricsSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: AgentMetricsMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: AgentMetricsMaxAggregateInputType
}

export type GetAgentMetricsAggregateType<T extends AgentMetricsAggregateArgs> = {
      [P in keyof T & keyof AggregateAgentMetrics]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateAgentMetrics[P]>
    : Prisma.GetScalarType<T[P], AggregateAgentMetrics[P]>
}




export type AgentMetricsGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AgentMetricsWhereInput
  orderBy?: Prisma.AgentMetricsOrderByWithAggregationInput | Prisma.AgentMetricsOrderByWithAggregationInput[]
  by: Prisma.AgentMetricsScalarFieldEnum[] | Prisma.AgentMetricsScalarFieldEnum
  having?: Prisma.AgentMetricsScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: AgentMetricsCountAggregateInputType | true
  _avg?: AgentMetricsAvgAggregateInputType
  _sum?: AgentMetricsSumAggregateInputType
  _min?: AgentMetricsMinAggregateInputType
  _max?: AgentMetricsMaxAggregateInputType
}

export type AgentMetricsGroupByOutputType = {
  id: string
  agentType: string
  totalExecutions: number
  successCount: number
  errorCount: number
  totalExecutionTime: number
  averageExecutionTime: number
  averageTokenUsage: number
  routingFrequency: number
  lastExecution: Date
  createdAt: Date
  _count: AgentMetricsCountAggregateOutputType | null
  _avg: AgentMetricsAvgAggregateOutputType | null
  _sum: AgentMetricsSumAggregateOutputType | null
  _min: AgentMetricsMinAggregateOutputType | null
  _max: AgentMetricsMaxAggregateOutputType | null
}

type GetAgentMetricsGroupByPayload<T extends AgentMetricsGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<AgentMetricsGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof AgentMetricsGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], AgentMetricsGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], AgentMetricsGroupByOutputType[P]>
      }
    >
  >



export type AgentMetricsWhereInput = {
  AND?: Prisma.AgentMetricsWhereInput | Prisma.AgentMetricsWhereInput[]
  OR?: Prisma.AgentMetricsWhereInput[]
  NOT?: Prisma.AgentMetricsWhereInput | Prisma.AgentMetricsWhereInput[]
  id?: Prisma.StringFilter<"AgentMetrics"> | string
  agentType?: Prisma.StringFilter<"AgentMetrics"> | string
  totalExecutions?: Prisma.IntFilter<"AgentMetrics"> | number
  successCount?: Prisma.IntFilter<"AgentMetrics"> | number
  errorCount?: Prisma.IntFilter<"AgentMetrics"> | number
  totalExecutionTime?: Prisma.IntFilter<"AgentMetrics"> | number
  averageExecutionTime?: Prisma.FloatFilter<"AgentMetrics"> | number
  averageTokenUsage?: Prisma.IntFilter<"AgentMetrics"> | number
  routingFrequency?: Prisma.IntFilter<"AgentMetrics"> | number
  lastExecution?: Prisma.DateTimeFilter<"AgentMetrics"> | Date | string
  createdAt?: Prisma.DateTimeFilter<"AgentMetrics"> | Date | string
}

export type AgentMetricsOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  agentType?: Prisma.SortOrder
  totalExecutions?: Prisma.SortOrder
  successCount?: Prisma.SortOrder
  errorCount?: Prisma.SortOrder
  totalExecutionTime?: Prisma.SortOrder
  averageExecutionTime?: Prisma.SortOrder
  averageTokenUsage?: Prisma.SortOrder
  routingFrequency?: Prisma.SortOrder
  lastExecution?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type AgentMetricsWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  agentType?: string
  AND?: Prisma.AgentMetricsWhereInput | Prisma.AgentMetricsWhereInput[]
  OR?: Prisma.AgentMetricsWhereInput[]
  NOT?: Prisma.AgentMetricsWhereInput | Prisma.AgentMetricsWhereInput[]
  totalExecutions?: Prisma.IntFilter<"AgentMetrics"> | number
  successCount?: Prisma.IntFilter<"AgentMetrics"> | number
  errorCount?: Prisma.IntFilter<"AgentMetrics"> | number
  totalExecutionTime?: Prisma.IntFilter<"AgentMetrics"> | number
  averageExecutionTime?: Prisma.FloatFilter<"AgentMetrics"> | number
  averageTokenUsage?: Prisma.IntFilter<"AgentMetrics"> | number
  routingFrequency?: Prisma.IntFilter<"AgentMetrics"> | number
  lastExecution?: Prisma.DateTimeFilter<"AgentMetrics"> | Date | string
  createdAt?: Prisma.DateTimeFilter<"AgentMetrics"> | Date | string
}, "id" | "agentType">

export type AgentMetricsOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  agentType?: Prisma.SortOrder
  totalExecutions?: Prisma.SortOrder
  successCount?: Prisma.SortOrder
  errorCount?: Prisma.SortOrder
  totalExecutionTime?: Prisma.SortOrder
  averageExecutionTime?: Prisma.SortOrder
  averageTokenUsage?: Prisma.SortOrder
  routingFrequency?: Prisma.SortOrder
  lastExecution?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.AgentMetricsCountOrderByAggregateInput
  _avg?: Prisma.AgentMetricsAvgOrderByAggregateInput
  _max?: Prisma.AgentMetricsMaxOrderByAggregateInput
  _min?: Prisma.AgentMetricsMinOrderByAggregateInput
  _sum?: Prisma.AgentMetricsSumOrderByAggregateInput
}

export type AgentMetricsScalarWhereWithAggregatesInput = {
  AND?: Prisma.AgentMetricsScalarWhereWithAggregatesInput | Prisma.AgentMetricsScalarWhereWithAggregatesInput[]
  OR?: Prisma.AgentMetricsScalarWhereWithAggregatesInput[]
  NOT?: Prisma.AgentMetricsScalarWhereWithAggregatesInput | Prisma.AgentMetricsScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"AgentMetrics"> | string
  agentType?: Prisma.StringWithAggregatesFilter<"AgentMetrics"> | string
  totalExecutions?: Prisma.IntWithAggregatesFilter<"AgentMetrics"> | number
  successCount?: Prisma.IntWithAggregatesFilter<"AgentMetrics"> | number
  errorCount?: Prisma.IntWithAggregatesFilter<"AgentMetrics"> | number
  totalExecutionTime?: Prisma.IntWithAggregatesFilter<"AgentMetrics"> | number
  averageExecutionTime?: Prisma.FloatWithAggregatesFilter<"AgentMetrics"> | number
  averageTokenUsage?: Prisma.IntWithAggregatesFilter<"AgentMetrics"> | number
  routingFrequency?: Prisma.IntWithAggregatesFilter<"AgentMetrics"> | number
  lastExecution?: Prisma.DateTimeWithAggregatesFilter<"AgentMetrics"> | Date | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"AgentMetrics"> | Date | string
}

export type AgentMetricsCreateInput = {
  id?: string
  agentType: string
  totalExecutions?: number
  successCount?: number
  errorCount?: number
  totalExecutionTime?: number
  averageExecutionTime?: number
  averageTokenUsage?: number
  routingFrequency?: number
  lastExecution?: Date | string
  createdAt?: Date | string
}

export type AgentMetricsUncheckedCreateInput = {
  id?: string
  agentType: string
  totalExecutions?: number
  successCount?: number
  errorCount?: number
  totalExecutionTime?: number
  averageExecutionTime?: number
  averageTokenUsage?: number
  routingFrequency?: number
  lastExecution?: Date | string
  createdAt?: Date | string
}

export type AgentMetricsUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  agentType?: Prisma.StringFieldUpdateOperationsInput | string
  totalExecutions?: Prisma.IntFieldUpdateOperationsInput | number
  successCount?: Prisma.IntFieldUpdateOperationsInput | number
  errorCount?: Prisma.IntFieldUpdateOperationsInput | number
  totalExecutionTime?: Prisma.IntFieldUpdateOperationsInput | number
  averageExecutionTime?: Prisma.FloatFieldUpdateOperationsInput | number
  averageTokenUsage?: Prisma.IntFieldUpdateOperationsInput | number
  routingFrequency?: Prisma.IntFieldUpdateOperationsInput | number
  lastExecution?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AgentMetricsUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  agentType?: Prisma.StringFieldUpdateOperationsInput | string
  totalExecutions?: Prisma.IntFieldUpdateOperationsInput | number
  successCount?: Prisma.IntFieldUpdateOperationsInput | number
  errorCount?: Prisma.IntFieldUpdateOperationsInput | number
  totalExecutionTime?: Prisma.IntFieldUpdateOperationsInput | number
  averageExecutionTime?: Prisma.FloatFieldUpdateOperationsInput | number
  averageTokenUsage?: Prisma.IntFieldUpdateOperationsInput | number
  routingFrequency?: Prisma.IntFieldUpdateOperationsInput | number
  lastExecution?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AgentMetricsCreateManyInput = {
  id?: string
  agentType: string
  totalExecutions?: number
  successCount?: number
  errorCount?: number
  totalExecutionTime?: number
  averageExecutionTime?: number
  averageTokenUsage?: number
  routingFrequency?: number
  lastExecution?: Date | string
  createdAt?: Date | string
}

export type AgentMetricsUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  agentType?: Prisma.StringFieldUpdateOperationsInput | string
  totalExecutions?: Prisma.IntFieldUpdateOperationsInput | number
  successCount?: Prisma.IntFieldUpdateOperationsInput | number
  errorCount?: Prisma.IntFieldUpdateOperationsInput | number
  totalExecutionTime?: Prisma.IntFieldUpdateOperationsInput | number
  averageExecutionTime?: Prisma.FloatFieldUpdateOperationsInput | number
  averageTokenUsage?: Prisma.IntFieldUpdateOperationsInput | number
  routingFrequency?: Prisma.IntFieldUpdateOperationsInput | number
  lastExecution?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AgentMetricsUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  agentType?: Prisma.StringFieldUpdateOperationsInput | string
  totalExecutions?: Prisma.IntFieldUpdateOperationsInput | number
  successCount?: Prisma.IntFieldUpdateOperationsInput | number
  errorCount?: Prisma.IntFieldUpdateOperationsInput | number
  totalExecutionTime?: Prisma.IntFieldUpdateOperationsInput | number
  averageExecutionTime?: Prisma.FloatFieldUpdateOperationsInput | number
  averageTokenUsage?: Prisma.IntFieldUpdateOperationsInput | number
  routingFrequency?: Prisma.IntFieldUpdateOperationsInput | number
  lastExecution?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AgentMetricsCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  agentType?: Prisma.SortOrder
  totalExecutions?: Prisma.SortOrder
  successCount?: Prisma.SortOrder
  errorCount?: Prisma.SortOrder
  totalExecutionTime?: Prisma.SortOrder
  averageExecutionTime?: Prisma.SortOrder
  averageTokenUsage?: Prisma.SortOrder
  routingFrequency?: Prisma.SortOrder
  lastExecution?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type AgentMetricsAvgOrderByAggregateInput = {
  totalExecutions?: Prisma.SortOrder
  successCount?: Prisma.SortOrder
  errorCount?: Prisma.SortOrder
  totalExecutionTime?: Prisma.SortOrder
  averageExecutionTime?: Prisma.SortOrder
  averageTokenUsage?: Prisma.SortOrder
  routingFrequency?: Prisma.SortOrder
}

export type AgentMetricsMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  agentType?: Prisma.SortOrder
  totalExecutions?: Prisma.SortOrder
  successCount?: Prisma.SortOrder
  errorCount?: Prisma.SortOrder
  totalExecutionTime?: Prisma.SortOrder
  averageExecutionTime?: Prisma.SortOrder
  averageTokenUsage?: Prisma.SortOrder
  routingFrequency?: Prisma.SortOrder
  lastExecution?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type AgentMetricsMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  agentType?: Prisma.SortOrder
  totalExecutions?: Prisma.SortOrder
  successCount?: Prisma.SortOrder
  errorCount?: Prisma.SortOrder
  totalExecutionTime?: Prisma.SortOrder
  averageExecutionTime?: Prisma.SortOrder
  averageTokenUsage?: Prisma.SortOrder
  routingFrequency?: Prisma.SortOrder
  lastExecution?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type AgentMetricsSumOrderByAggregateInput = {
  totalExecutions?: Prisma.SortOrder
  successCount?: Prisma.SortOrder
  errorCount?: Prisma.SortOrder
  totalExecutionTime?: Prisma.SortOrder
  averageExecutionTime?: Prisma.SortOrder
  averageTokenUsage?: Prisma.SortOrder
  routingFrequency?: Prisma.SortOrder
}



export type AgentMetricsSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  agentType?: boolean
  totalExecutions?: boolean
  successCount?: boolean
  errorCount?: boolean
  totalExecutionTime?: boolean
  averageExecutionTime?: boolean
  averageTokenUsage?: boolean
  routingFrequency?: boolean
  lastExecution?: boolean
  createdAt?: boolean
}, ExtArgs["result"]["agentMetrics"]>

export type AgentMetricsSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  agentType?: boolean
  totalExecutions?: boolean
  successCount?: boolean
  errorCount?: boolean
  totalExecutionTime?: boolean
  averageExecutionTime?: boolean
  averageTokenUsage?: boolean
  routingFrequency?: boolean
  lastExecution?: boolean
  createdAt?: boolean
}, ExtArgs["result"]["agentMetrics"]>

export type AgentMetricsSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  agentType?: boolean
  totalExecutions?: boolean
  successCount?: boolean
  errorCount?: boolean
  totalExecutionTime?: boolean
  averageExecutionTime?: boolean
  averageTokenUsage?: boolean
  routingFrequency?: boolean
  lastExecution?: boolean
  createdAt?: boolean
}, ExtArgs["result"]["agentMetrics"]>

export type AgentMetricsSelectScalar = {
  id?: boolean
  agentType?: boolean
  totalExecutions?: boolean
  successCount?: boolean
  errorCount?: boolean
  totalExecutionTime?: boolean
  averageExecutionTime?: boolean
  averageTokenUsage?: boolean
  routingFrequency?: boolean
  lastExecution?: boolean
  createdAt?: boolean
}

export type AgentMetricsOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "agentType" | "totalExecutions" | "successCount" | "errorCount" | "totalExecutionTime" | "averageExecutionTime" | "averageTokenUsage" | "routingFrequency" | "lastExecution" | "createdAt", ExtArgs["result"]["agentMetrics"]>

export type $AgentMetricsPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "AgentMetrics"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    agentType: string
    totalExecutions: number
    successCount: number
    errorCount: number
    totalExecutionTime: number
    averageExecutionTime: number
    averageTokenUsage: number
    routingFrequency: number
    lastExecution: Date
    createdAt: Date
  }, ExtArgs["result"]["agentMetrics"]>
  composites: {}
}

export type AgentMetricsGetPayload<S extends boolean | null | undefined | AgentMetricsDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$AgentMetricsPayload, S>

export type AgentMetricsCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<AgentMetricsFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: AgentMetricsCountAggregateInputType | true
  }

export interface AgentMetricsDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['AgentMetrics'], meta: { name: 'AgentMetrics' } }
  /**
   * Find zero or one AgentMetrics that matches the filter.
   * @param {AgentMetricsFindUniqueArgs} args - Arguments to find a AgentMetrics
   * @example
   * // Get one AgentMetrics
   * const agentMetrics = await prisma.agentMetrics.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends AgentMetricsFindUniqueArgs>(args: Prisma.SelectSubset<T, AgentMetricsFindUniqueArgs<ExtArgs>>): Prisma.Prisma__AgentMetricsClient<runtime.Types.Result.GetResult<Prisma.$AgentMetricsPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one AgentMetrics that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {AgentMetricsFindUniqueOrThrowArgs} args - Arguments to find a AgentMetrics
   * @example
   * // Get one AgentMetrics
   * const agentMetrics = await prisma.agentMetrics.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends AgentMetricsFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, AgentMetricsFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__AgentMetricsClient<runtime.Types.Result.GetResult<Prisma.$AgentMetricsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first AgentMetrics that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AgentMetricsFindFirstArgs} args - Arguments to find a AgentMetrics
   * @example
   * // Get one AgentMetrics
   * const agentMetrics = await prisma.agentMetrics.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends AgentMetricsFindFirstArgs>(args?: Prisma.SelectSubset<T, AgentMetricsFindFirstArgs<ExtArgs>>): Prisma.Prisma__AgentMetricsClient<runtime.Types.Result.GetResult<Prisma.$AgentMetricsPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first AgentMetrics that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AgentMetricsFindFirstOrThrowArgs} args - Arguments to find a AgentMetrics
   * @example
   * // Get one AgentMetrics
   * const agentMetrics = await prisma.agentMetrics.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends AgentMetricsFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, AgentMetricsFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__AgentMetricsClient<runtime.Types.Result.GetResult<Prisma.$AgentMetricsPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more AgentMetrics that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AgentMetricsFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all AgentMetrics
   * const agentMetrics = await prisma.agentMetrics.findMany()
   * 
   * // Get first 10 AgentMetrics
   * const agentMetrics = await prisma.agentMetrics.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const agentMetricsWithIdOnly = await prisma.agentMetrics.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends AgentMetricsFindManyArgs>(args?: Prisma.SelectSubset<T, AgentMetricsFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AgentMetricsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a AgentMetrics.
   * @param {AgentMetricsCreateArgs} args - Arguments to create a AgentMetrics.
   * @example
   * // Create one AgentMetrics
   * const AgentMetrics = await prisma.agentMetrics.create({
   *   data: {
   *     // ... data to create a AgentMetrics
   *   }
   * })
   * 
   */
  create<T extends AgentMetricsCreateArgs>(args: Prisma.SelectSubset<T, AgentMetricsCreateArgs<ExtArgs>>): Prisma.Prisma__AgentMetricsClient<runtime.Types.Result.GetResult<Prisma.$AgentMetricsPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many AgentMetrics.
   * @param {AgentMetricsCreateManyArgs} args - Arguments to create many AgentMetrics.
   * @example
   * // Create many AgentMetrics
   * const agentMetrics = await prisma.agentMetrics.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends AgentMetricsCreateManyArgs>(args?: Prisma.SelectSubset<T, AgentMetricsCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many AgentMetrics and returns the data saved in the database.
   * @param {AgentMetricsCreateManyAndReturnArgs} args - Arguments to create many AgentMetrics.
   * @example
   * // Create many AgentMetrics
   * const agentMetrics = await prisma.agentMetrics.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many AgentMetrics and only return the `id`
   * const agentMetricsWithIdOnly = await prisma.agentMetrics.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends AgentMetricsCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, AgentMetricsCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AgentMetricsPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a AgentMetrics.
   * @param {AgentMetricsDeleteArgs} args - Arguments to delete one AgentMetrics.
   * @example
   * // Delete one AgentMetrics
   * const AgentMetrics = await prisma.agentMetrics.delete({
   *   where: {
   *     // ... filter to delete one AgentMetrics
   *   }
   * })
   * 
   */
  delete<T extends AgentMetricsDeleteArgs>(args: Prisma.SelectSubset<T, AgentMetricsDeleteArgs<ExtArgs>>): Prisma.Prisma__AgentMetricsClient<runtime.Types.Result.GetResult<Prisma.$AgentMetricsPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one AgentMetrics.
   * @param {AgentMetricsUpdateArgs} args - Arguments to update one AgentMetrics.
   * @example
   * // Update one AgentMetrics
   * const agentMetrics = await prisma.agentMetrics.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends AgentMetricsUpdateArgs>(args: Prisma.SelectSubset<T, AgentMetricsUpdateArgs<ExtArgs>>): Prisma.Prisma__AgentMetricsClient<runtime.Types.Result.GetResult<Prisma.$AgentMetricsPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more AgentMetrics.
   * @param {AgentMetricsDeleteManyArgs} args - Arguments to filter AgentMetrics to delete.
   * @example
   * // Delete a few AgentMetrics
   * const { count } = await prisma.agentMetrics.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends AgentMetricsDeleteManyArgs>(args?: Prisma.SelectSubset<T, AgentMetricsDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more AgentMetrics.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AgentMetricsUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many AgentMetrics
   * const agentMetrics = await prisma.agentMetrics.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends AgentMetricsUpdateManyArgs>(args: Prisma.SelectSubset<T, AgentMetricsUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more AgentMetrics and returns the data updated in the database.
   * @param {AgentMetricsUpdateManyAndReturnArgs} args - Arguments to update many AgentMetrics.
   * @example
   * // Update many AgentMetrics
   * const agentMetrics = await prisma.agentMetrics.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more AgentMetrics and only return the `id`
   * const agentMetricsWithIdOnly = await prisma.agentMetrics.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends AgentMetricsUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, AgentMetricsUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AgentMetricsPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one AgentMetrics.
   * @param {AgentMetricsUpsertArgs} args - Arguments to update or create a AgentMetrics.
   * @example
   * // Update or create a AgentMetrics
   * const agentMetrics = await prisma.agentMetrics.upsert({
   *   create: {
   *     // ... data to create a AgentMetrics
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the AgentMetrics we want to update
   *   }
   * })
   */
  upsert<T extends AgentMetricsUpsertArgs>(args: Prisma.SelectSubset<T, AgentMetricsUpsertArgs<ExtArgs>>): Prisma.Prisma__AgentMetricsClient<runtime.Types.Result.GetResult<Prisma.$AgentMetricsPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of AgentMetrics.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AgentMetricsCountArgs} args - Arguments to filter AgentMetrics to count.
   * @example
   * // Count the number of AgentMetrics
   * const count = await prisma.agentMetrics.count({
   *   where: {
   *     // ... the filter for the AgentMetrics we want to count
   *   }
   * })
  **/
  count<T extends AgentMetricsCountArgs>(
    args?: Prisma.Subset<T, AgentMetricsCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], AgentMetricsCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a AgentMetrics.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AgentMetricsAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends AgentMetricsAggregateArgs>(args: Prisma.Subset<T, AgentMetricsAggregateArgs>): Prisma.PrismaPromise<GetAgentMetricsAggregateType<T>>

  /**
   * Group by AgentMetrics.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AgentMetricsGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends AgentMetricsGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: AgentMetricsGroupByArgs['orderBy'] }
      : { orderBy?: AgentMetricsGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, AgentMetricsGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetAgentMetricsGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the AgentMetrics model
 */
readonly fields: AgentMetricsFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for AgentMetrics.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__AgentMetricsClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the AgentMetrics model
 */
export interface AgentMetricsFieldRefs {
  readonly id: Prisma.FieldRef<"AgentMetrics", 'String'>
  readonly agentType: Prisma.FieldRef<"AgentMetrics", 'String'>
  readonly totalExecutions: Prisma.FieldRef<"AgentMetrics", 'Int'>
  readonly successCount: Prisma.FieldRef<"AgentMetrics", 'Int'>
  readonly errorCount: Prisma.FieldRef<"AgentMetrics", 'Int'>
  readonly totalExecutionTime: Prisma.FieldRef<"AgentMetrics", 'Int'>
  readonly averageExecutionTime: Prisma.FieldRef<"AgentMetrics", 'Float'>
  readonly averageTokenUsage: Prisma.FieldRef<"AgentMetrics", 'Int'>
  readonly routingFrequency: Prisma.FieldRef<"AgentMetrics", 'Int'>
  readonly lastExecution: Prisma.FieldRef<"AgentMetrics", 'DateTime'>
  readonly createdAt: Prisma.FieldRef<"AgentMetrics", 'DateTime'>
}
    

// Custom InputTypes
/**
 * AgentMetrics findUnique
 */
export type AgentMetricsFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AgentMetrics
   */
  select?: Prisma.AgentMetricsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AgentMetrics
   */
  omit?: Prisma.AgentMetricsOmit<ExtArgs> | null
  /**
   * Filter, which AgentMetrics to fetch.
   */
  where: Prisma.AgentMetricsWhereUniqueInput
}

/**
 * AgentMetrics findUniqueOrThrow
 */
export type AgentMetricsFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AgentMetrics
   */
  select?: Prisma.AgentMetricsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AgentMetrics
   */
  omit?: Prisma.AgentMetricsOmit<ExtArgs> | null
  /**
   * Filter, which AgentMetrics to fetch.
   */
  where: Prisma.AgentMetricsWhereUniqueInput
}

/**
 * AgentMetrics findFirst
 */
export type AgentMetricsFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AgentMetrics
   */
  select?: Prisma.AgentMetricsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AgentMetrics
   */
  omit?: Prisma.AgentMetricsOmit<ExtArgs> | null
  /**
   * Filter, which AgentMetrics to fetch.
   */
  where?: Prisma.AgentMetricsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AgentMetrics to fetch.
   */
  orderBy?: Prisma.AgentMetricsOrderByWithRelationInput | Prisma.AgentMetricsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for AgentMetrics.
   */
  cursor?: Prisma.AgentMetricsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AgentMetrics from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AgentMetrics.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AgentMetrics.
   */
  distinct?: Prisma.AgentMetricsScalarFieldEnum | Prisma.AgentMetricsScalarFieldEnum[]
}

/**
 * AgentMetrics findFirstOrThrow
 */
export type AgentMetricsFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AgentMetrics
   */
  select?: Prisma.AgentMetricsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AgentMetrics
   */
  omit?: Prisma.AgentMetricsOmit<ExtArgs> | null
  /**
   * Filter, which AgentMetrics to fetch.
   */
  where?: Prisma.AgentMetricsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AgentMetrics to fetch.
   */
  orderBy?: Prisma.AgentMetricsOrderByWithRelationInput | Prisma.AgentMetricsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for AgentMetrics.
   */
  cursor?: Prisma.AgentMetricsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AgentMetrics from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AgentMetrics.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AgentMetrics.
   */
  distinct?: Prisma.AgentMetricsScalarFieldEnum | Prisma.AgentMetricsScalarFieldEnum[]
}

/**
 * AgentMetrics findMany
 */
export type AgentMetricsFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AgentMetrics
   */
  select?: Prisma.AgentMetricsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AgentMetrics
   */
  omit?: Prisma.AgentMetricsOmit<ExtArgs> | null
  /**
   * Filter, which AgentMetrics to fetch.
   */
  where?: Prisma.AgentMetricsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AgentMetrics to fetch.
   */
  orderBy?: Prisma.AgentMetricsOrderByWithRelationInput | Prisma.AgentMetricsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing AgentMetrics.
   */
  cursor?: Prisma.AgentMetricsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AgentMetrics from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AgentMetrics.
   */
  skip?: number
  distinct?: Prisma.AgentMetricsScalarFieldEnum | Prisma.AgentMetricsScalarFieldEnum[]
}

/**
 * AgentMetrics create
 */
export type AgentMetricsCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AgentMetrics
   */
  select?: Prisma.AgentMetricsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AgentMetrics
   */
  omit?: Prisma.AgentMetricsOmit<ExtArgs> | null
  /**
   * The data needed to create a AgentMetrics.
   */
  data: Prisma.XOR<Prisma.AgentMetricsCreateInput, Prisma.AgentMetricsUncheckedCreateInput>
}

/**
 * AgentMetrics createMany
 */
export type AgentMetricsCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many AgentMetrics.
   */
  data: Prisma.AgentMetricsCreateManyInput | Prisma.AgentMetricsCreateManyInput[]
}

/**
 * AgentMetrics createManyAndReturn
 */
export type AgentMetricsCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AgentMetrics
   */
  select?: Prisma.AgentMetricsSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the AgentMetrics
   */
  omit?: Prisma.AgentMetricsOmit<ExtArgs> | null
  /**
   * The data used to create many AgentMetrics.
   */
  data: Prisma.AgentMetricsCreateManyInput | Prisma.AgentMetricsCreateManyInput[]
}

/**
 * AgentMetrics update
 */
export type AgentMetricsUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AgentMetrics
   */
  select?: Prisma.AgentMetricsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AgentMetrics
   */
  omit?: Prisma.AgentMetricsOmit<ExtArgs> | null
  /**
   * The data needed to update a AgentMetrics.
   */
  data: Prisma.XOR<Prisma.AgentMetricsUpdateInput, Prisma.AgentMetricsUncheckedUpdateInput>
  /**
   * Choose, which AgentMetrics to update.
   */
  where: Prisma.AgentMetricsWhereUniqueInput
}

/**
 * AgentMetrics updateMany
 */
export type AgentMetricsUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update AgentMetrics.
   */
  data: Prisma.XOR<Prisma.AgentMetricsUpdateManyMutationInput, Prisma.AgentMetricsUncheckedUpdateManyInput>
  /**
   * Filter which AgentMetrics to update
   */
  where?: Prisma.AgentMetricsWhereInput
  /**
   * Limit how many AgentMetrics to update.
   */
  limit?: number
}

/**
 * AgentMetrics updateManyAndReturn
 */
export type AgentMetricsUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AgentMetrics
   */
  select?: Prisma.AgentMetricsSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the AgentMetrics
   */
  omit?: Prisma.AgentMetricsOmit<ExtArgs> | null
  /**
   * The data used to update AgentMetrics.
   */
  data: Prisma.XOR<Prisma.AgentMetricsUpdateManyMutationInput, Prisma.AgentMetricsUncheckedUpdateManyInput>
  /**
   * Filter which AgentMetrics to update
   */
  where?: Prisma.AgentMetricsWhereInput
  /**
   * Limit how many AgentMetrics to update.
   */
  limit?: number
}

/**
 * AgentMetrics upsert
 */
export type AgentMetricsUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AgentMetrics
   */
  select?: Prisma.AgentMetricsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AgentMetrics
   */
  omit?: Prisma.AgentMetricsOmit<ExtArgs> | null
  /**
   * The filter to search for the AgentMetrics to update in case it exists.
   */
  where: Prisma.AgentMetricsWhereUniqueInput
  /**
   * In case the AgentMetrics found by the `where` argument doesn't exist, create a new AgentMetrics with this data.
   */
  create: Prisma.XOR<Prisma.AgentMetricsCreateInput, Prisma.AgentMetricsUncheckedCreateInput>
  /**
   * In case the AgentMetrics was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.AgentMetricsUpdateInput, Prisma.AgentMetricsUncheckedUpdateInput>
}

/**
 * AgentMetrics delete
 */
export type AgentMetricsDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AgentMetrics
   */
  select?: Prisma.AgentMetricsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AgentMetrics
   */
  omit?: Prisma.AgentMetricsOmit<ExtArgs> | null
  /**
   * Filter which AgentMetrics to delete.
   */
  where: Prisma.AgentMetricsWhereUniqueInput
}

/**
 * AgentMetrics deleteMany
 */
export type AgentMetricsDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which AgentMetrics to delete
   */
  where?: Prisma.AgentMetricsWhereInput
  /**
   * Limit how many AgentMetrics to delete.
   */
  limit?: number
}

/**
 * AgentMetrics without action
 */
export type AgentMetricsDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AgentMetrics
   */
  select?: Prisma.AgentMetricsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AgentMetrics
   */
  omit?: Prisma.AgentMetricsOmit<ExtArgs> | null
}
