
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `AgentRoutingLog` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model AgentRoutingLog
 * 
 */
export type AgentRoutingLogModel = runtime.Types.Result.DefaultSelection<Prisma.$AgentRoutingLogPayload>

export type AggregateAgentRoutingLog = {
  _count: AgentRoutingLogCountAggregateOutputType | null
  _avg: AgentRoutingLogAvgAggregateOutputType | null
  _sum: AgentRoutingLogSumAggregateOutputType | null
  _min: AgentRoutingLogMinAggregateOutputType | null
  _max: AgentRoutingLogMaxAggregateOutputType | null
}

export type AgentRoutingLogAvgAggregateOutputType = {
  confidence: number | null
}

export type AgentRoutingLogSumAggregateOutputType = {
  confidence: number | null
}

export type AgentRoutingLogMinAggregateOutputType = {
  id: string | null
  conversationId: string | null
  query: string | null
  detectedIntent: string | null
  selectedAgent: string | null
  confidence: number | null
  reasoning: string | null
  createdAt: Date | null
}

export type AgentRoutingLogMaxAggregateOutputType = {
  id: string | null
  conversationId: string | null
  query: string | null
  detectedIntent: string | null
  selectedAgent: string | null
  confidence: number | null
  reasoning: string | null
  createdAt: Date | null
}

export type AgentRoutingLogCountAggregateOutputType = {
  id: number
  conversationId: number
  query: number
  detectedIntent: number
  selectedAgent: number
  confidence: number
  reasoning: number
  createdAt: number
  _all: number
}


export type AgentRoutingLogAvgAggregateInputType = {
  confidence?: true
}

export type AgentRoutingLogSumAggregateInputType = {
  confidence?: true
}

export type AgentRoutingLogMinAggregateInputType = {
  id?: true
  conversationId?: true
  query?: true
  detectedIntent?: true
  selectedAgent?: true
  confidence?: true
  reasoning?: true
  createdAt?: true
}

export type AgentRoutingLogMaxAggregateInputType = {
  id?: true
  conversationId?: true
  query?: true
  detectedIntent?: true
  selectedAgent?: true
  confidence?: true
  reasoning?: true
  createdAt?: true
}

export type AgentRoutingLogCountAggregateInputType = {
  id?: true
  conversationId?: true
  query?: true
  detectedIntent?: true
  selectedAgent?: true
  confidence?: true
  reasoning?: true
  createdAt?: true
  _all?: true
}

export type AgentRoutingLogAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which AgentRoutingLog to aggregate.
   */
  where?: Prisma.AgentRoutingLogWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AgentRoutingLogs to fetch.
   */
  orderBy?: Prisma.AgentRoutingLogOrderByWithRelationInput | Prisma.AgentRoutingLogOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.AgentRoutingLogWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AgentRoutingLogs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AgentRoutingLogs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned AgentRoutingLogs
  **/
  _count?: true | AgentRoutingLogCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: AgentRoutingLogAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: AgentRoutingLogSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: AgentRoutingLogMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: AgentRoutingLogMaxAggregateInputType
}

export type GetAgentRoutingLogAggregateType<T extends AgentRoutingLogAggregateArgs> = {
      [P in keyof T & keyof AggregateAgentRoutingLog]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateAgentRoutingLog[P]>
    : Prisma.GetScalarType<T[P], AggregateAgentRoutingLog[P]>
}




export type AgentRoutingLogGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AgentRoutingLogWhereInput
  orderBy?: Prisma.AgentRoutingLogOrderByWithAggregationInput | Prisma.AgentRoutingLogOrderByWithAggregationInput[]
  by: Prisma.AgentRoutingLogScalarFieldEnum[] | Prisma.AgentRoutingLogScalarFieldEnum
  having?: Prisma.AgentRoutingLogScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: AgentRoutingLogCountAggregateInputType | true
  _avg?: AgentRoutingLogAvgAggregateInputType
  _sum?: AgentRoutingLogSumAggregateInputType
  _min?: AgentRoutingLogMinAggregateInputType
  _max?: AgentRoutingLogMaxAggregateInputType
}

export type AgentRoutingLogGroupByOutputType = {
  id: string
  conversationId: string
  query: string
  detectedIntent: string
  selectedAgent: string
  confidence: number
  reasoning: string | null
  createdAt: Date
  _count: AgentRoutingLogCountAggregateOutputType | null
  _avg: AgentRoutingLogAvgAggregateOutputType | null
  _sum: AgentRoutingLogSumAggregateOutputType | null
  _min: AgentRoutingLogMinAggregateOutputType | null
  _max: AgentRoutingLogMaxAggregateOutputType | null
}

type GetAgentRoutingLogGroupByPayload<T extends AgentRoutingLogGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<AgentRoutingLogGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof AgentRoutingLogGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], AgentRoutingLogGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], AgentRoutingLogGroupByOutputType[P]>
      }
    >
  >



export type AgentRoutingLogWhereInput = {
  AND?: Prisma.AgentRoutingLogWhereInput | Prisma.AgentRoutingLogWhereInput[]
  OR?: Prisma.AgentRoutingLogWhereInput[]
  NOT?: Prisma.AgentRoutingLogWhereInput | Prisma.AgentRoutingLogWhereInput[]
  id?: Prisma.StringFilter<"AgentRoutingLog"> | string
  conversationId?: Prisma.StringFilter<"AgentRoutingLog"> | string
  query?: Prisma.StringFilter<"AgentRoutingLog"> | string
  detectedIntent?: Prisma.StringFilter<"AgentRoutingLog"> | string
  selectedAgent?: Prisma.StringFilter<"AgentRoutingLog"> | string
  confidence?: Prisma.FloatFilter<"AgentRoutingLog"> | number
  reasoning?: Prisma.StringNullableFilter<"AgentRoutingLog"> | string | null
  createdAt?: Prisma.DateTimeFilter<"AgentRoutingLog"> | Date | string
}

export type AgentRoutingLogOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  conversationId?: Prisma.SortOrder
  query?: Prisma.SortOrder
  detectedIntent?: Prisma.SortOrder
  selectedAgent?: Prisma.SortOrder
  confidence?: Prisma.SortOrder
  reasoning?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type AgentRoutingLogWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.AgentRoutingLogWhereInput | Prisma.AgentRoutingLogWhereInput[]
  OR?: Prisma.AgentRoutingLogWhereInput[]
  NOT?: Prisma.AgentRoutingLogWhereInput | Prisma.AgentRoutingLogWhereInput[]
  conversationId?: Prisma.StringFilter<"AgentRoutingLog"> | string
  query?: Prisma.StringFilter<"AgentRoutingLog"> | string
  detectedIntent?: Prisma.StringFilter<"AgentRoutingLog"> | string
  selectedAgent?: Prisma.StringFilter<"AgentRoutingLog"> | string
  confidence?: Prisma.FloatFilter<"AgentRoutingLog"> | number
  reasoning?: Prisma.StringNullableFilter<"AgentRoutingLog"> | string | null
  createdAt?: Prisma.DateTimeFilter<"AgentRoutingLog"> | Date | string
}, "id">

export type AgentRoutingLogOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  conversationId?: Prisma.SortOrder
  query?: Prisma.SortOrder
  detectedIntent?: Prisma.SortOrder
  selectedAgent?: Prisma.SortOrder
  confidence?: Prisma.SortOrder
  reasoning?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.AgentRoutingLogCountOrderByAggregateInput
  _avg?: Prisma.AgentRoutingLogAvgOrderByAggregateInput
  _max?: Prisma.AgentRoutingLogMaxOrderByAggregateInput
  _min?: Prisma.AgentRoutingLogMinOrderByAggregateInput
  _sum?: Prisma.AgentRoutingLogSumOrderByAggregateInput
}

export type AgentRoutingLogScalarWhereWithAggregatesInput = {
  AND?: Prisma.AgentRoutingLogScalarWhereWithAggregatesInput | Prisma.AgentRoutingLogScalarWhereWithAggregatesInput[]
  OR?: Prisma.AgentRoutingLogScalarWhereWithAggregatesInput[]
  NOT?: Prisma.AgentRoutingLogScalarWhereWithAggregatesInput | Prisma.AgentRoutingLogScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"AgentRoutingLog"> | string
  conversationId?: Prisma.StringWithAggregatesFilter<"AgentRoutingLog"> | string
  query?: Prisma.StringWithAggregatesFilter<"AgentRoutingLog"> | string
  detectedIntent?: Prisma.StringWithAggregatesFilter<"AgentRoutingLog"> | string
  selectedAgent?: Prisma.StringWithAggregatesFilter<"AgentRoutingLog"> | string
  confidence?: Prisma.FloatWithAggregatesFilter<"AgentRoutingLog"> | number
  reasoning?: Prisma.StringNullableWithAggregatesFilter<"AgentRoutingLog"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"AgentRoutingLog"> | Date | string
}

export type AgentRoutingLogCreateInput = {
  id?: string
  conversationId: string
  query: string
  detectedIntent: string
  selectedAgent: string
  confidence: number
  reasoning?: string | null
  createdAt?: Date | string
}

export type AgentRoutingLogUncheckedCreateInput = {
  id?: string
  conversationId: string
  query: string
  detectedIntent: string
  selectedAgent: string
  confidence: number
  reasoning?: string | null
  createdAt?: Date | string
}

export type AgentRoutingLogUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  conversationId?: Prisma.StringFieldUpdateOperationsInput | string
  query?: Prisma.StringFieldUpdateOperationsInput | string
  detectedIntent?: Prisma.StringFieldUpdateOperationsInput | string
  selectedAgent?: Prisma.StringFieldUpdateOperationsInput | string
  confidence?: Prisma.FloatFieldUpdateOperationsInput | number
  reasoning?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AgentRoutingLogUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  conversationId?: Prisma.StringFieldUpdateOperationsInput | string
  query?: Prisma.StringFieldUpdateOperationsInput | string
  detectedIntent?: Prisma.StringFieldUpdateOperationsInput | string
  selectedAgent?: Prisma.StringFieldUpdateOperationsInput | string
  confidence?: Prisma.FloatFieldUpdateOperationsInput | number
  reasoning?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AgentRoutingLogCreateManyInput = {
  id?: string
  conversationId: string
  query: string
  detectedIntent: string
  selectedAgent: string
  confidence: number
  reasoning?: string | null
  createdAt?: Date | string
}

export type AgentRoutingLogUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  conversationId?: Prisma.StringFieldUpdateOperationsInput | string
  query?: Prisma.StringFieldUpdateOperationsInput | string
  detectedIntent?: Prisma.StringFieldUpdateOperationsInput | string
  selectedAgent?: Prisma.StringFieldUpdateOperationsInput | string
  confidence?: Prisma.FloatFieldUpdateOperationsInput | number
  reasoning?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AgentRoutingLogUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  conversationId?: Prisma.StringFieldUpdateOperationsInput | string
  query?: Prisma.StringFieldUpdateOperationsInput | string
  detectedIntent?: Prisma.StringFieldUpdateOperationsInput | string
  selectedAgent?: Prisma.StringFieldUpdateOperationsInput | string
  confidence?: Prisma.FloatFieldUpdateOperationsInput | number
  reasoning?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AgentRoutingLogCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  conversationId?: Prisma.SortOrder
  query?: Prisma.SortOrder
  detectedIntent?: Prisma.SortOrder
  selectedAgent?: Prisma.SortOrder
  confidence?: Prisma.SortOrder
  reasoning?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type AgentRoutingLogAvgOrderByAggregateInput = {
  confidence?: Prisma.SortOrder
}

export type AgentRoutingLogMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  conversationId?: Prisma.SortOrder
  query?: Prisma.SortOrder
  detectedIntent?: Prisma.SortOrder
  selectedAgent?: Prisma.SortOrder
  confidence?: Prisma.SortOrder
  reasoning?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type AgentRoutingLogMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  conversationId?: Prisma.SortOrder
  query?: Prisma.SortOrder
  detectedIntent?: Prisma.SortOrder
  selectedAgent?: Prisma.SortOrder
  confidence?: Prisma.SortOrder
  reasoning?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type AgentRoutingLogSumOrderByAggregateInput = {
  confidence?: Prisma.SortOrder
}



export type AgentRoutingLogSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  conversationId?: boolean
  query?: boolean
  detectedIntent?: boolean
  selectedAgent?: boolean
  confidence?: boolean
  reasoning?: boolean
  createdAt?: boolean
}, ExtArgs["result"]["agentRoutingLog"]>

export type AgentRoutingLogSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  conversationId?: boolean
  query?: boolean
  detectedIntent?: boolean
  selectedAgent?: boolean
  confidence?: boolean
  reasoning?: boolean
  createdAt?: boolean
}, ExtArgs["result"]["agentRoutingLog"]>

export type AgentRoutingLogSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  conversationId?: boolean
  query?: boolean
  detectedIntent?: boolean
  selectedAgent?: boolean
  confidence?: boolean
  reasoning?: boolean
  createdAt?: boolean
}, ExtArgs["result"]["agentRoutingLog"]>

export type AgentRoutingLogSelectScalar = {
  id?: boolean
  conversationId?: boolean
  query?: boolean
  detectedIntent?: boolean
  selectedAgent?: boolean
  confidence?: boolean
  reasoning?: boolean
  createdAt?: boolean
}

export type AgentRoutingLogOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "conversationId" | "query" | "detectedIntent" | "selectedAgent" | "confidence" | "reasoning" | "createdAt", ExtArgs["result"]["agentRoutingLog"]>

export type $AgentRoutingLogPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "AgentRoutingLog"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    conversationId: string
    query: string
    detectedIntent: string
    selectedAgent: string
    confidence: number
    reasoning: string | null
    createdAt: Date
  }, ExtArgs["result"]["agentRoutingLog"]>
  composites: {}
}

export type AgentRoutingLogGetPayload<S extends boolean | null | undefined | AgentRoutingLogDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$AgentRoutingLogPayload, S>

export type AgentRoutingLogCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<AgentRoutingLogFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: AgentRoutingLogCountAggregateInputType | true
  }

export interface AgentRoutingLogDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['AgentRoutingLog'], meta: { name: 'AgentRoutingLog' } }
  /**
   * Find zero or one AgentRoutingLog that matches the filter.
   * @param {AgentRoutingLogFindUniqueArgs} args - Arguments to find a AgentRoutingLog
   * @example
   * // Get one AgentRoutingLog
   * const agentRoutingLog = await prisma.agentRoutingLog.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends AgentRoutingLogFindUniqueArgs>(args: Prisma.SelectSubset<T, AgentRoutingLogFindUniqueArgs<ExtArgs>>): Prisma.Prisma__AgentRoutingLogClient<runtime.Types.Result.GetResult<Prisma.$AgentRoutingLogPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one AgentRoutingLog that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {AgentRoutingLogFindUniqueOrThrowArgs} args - Arguments to find a AgentRoutingLog
   * @example
   * // Get one AgentRoutingLog
   * const agentRoutingLog = await prisma.agentRoutingLog.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends AgentRoutingLogFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, AgentRoutingLogFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__AgentRoutingLogClient<runtime.Types.Result.GetResult<Prisma.$AgentRoutingLogPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first AgentRoutingLog that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AgentRoutingLogFindFirstArgs} args - Arguments to find a AgentRoutingLog
   * @example
   * // Get one AgentRoutingLog
   * const agentRoutingLog = await prisma.agentRoutingLog.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends AgentRoutingLogFindFirstArgs>(args?: Prisma.SelectSubset<T, AgentRoutingLogFindFirstArgs<ExtArgs>>): Prisma.Prisma__AgentRoutingLogClient<runtime.Types.Result.GetResult<Prisma.$AgentRoutingLogPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first AgentRoutingLog that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AgentRoutingLogFindFirstOrThrowArgs} args - Arguments to find a AgentRoutingLog
   * @example
   * // Get one AgentRoutingLog
   * const agentRoutingLog = await prisma.agentRoutingLog.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends AgentRoutingLogFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, AgentRoutingLogFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__AgentRoutingLogClient<runtime.Types.Result.GetResult<Prisma.$AgentRoutingLogPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more AgentRoutingLogs that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AgentRoutingLogFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all AgentRoutingLogs
   * const agentRoutingLogs = await prisma.agentRoutingLog.findMany()
   * 
   * // Get first 10 AgentRoutingLogs
   * const agentRoutingLogs = await prisma.agentRoutingLog.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const agentRoutingLogWithIdOnly = await prisma.agentRoutingLog.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends AgentRoutingLogFindManyArgs>(args?: Prisma.SelectSubset<T, AgentRoutingLogFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AgentRoutingLogPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a AgentRoutingLog.
   * @param {AgentRoutingLogCreateArgs} args - Arguments to create a AgentRoutingLog.
   * @example
   * // Create one AgentRoutingLog
   * const AgentRoutingLog = await prisma.agentRoutingLog.create({
   *   data: {
   *     // ... data to create a AgentRoutingLog
   *   }
   * })
   * 
   */
  create<T extends AgentRoutingLogCreateArgs>(args: Prisma.SelectSubset<T, AgentRoutingLogCreateArgs<ExtArgs>>): Prisma.Prisma__AgentRoutingLogClient<runtime.Types.Result.GetResult<Prisma.$AgentRoutingLogPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many AgentRoutingLogs.
   * @param {AgentRoutingLogCreateManyArgs} args - Arguments to create many AgentRoutingLogs.
   * @example
   * // Create many AgentRoutingLogs
   * const agentRoutingLog = await prisma.agentRoutingLog.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends AgentRoutingLogCreateManyArgs>(args?: Prisma.SelectSubset<T, AgentRoutingLogCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many AgentRoutingLogs and returns the data saved in the database.
   * @param {AgentRoutingLogCreateManyAndReturnArgs} args - Arguments to create many AgentRoutingLogs.
   * @example
   * // Create many AgentRoutingLogs
   * const agentRoutingLog = await prisma.agentRoutingLog.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many AgentRoutingLogs and only return the `id`
   * const agentRoutingLogWithIdOnly = await prisma.agentRoutingLog.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends AgentRoutingLogCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, AgentRoutingLogCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AgentRoutingLogPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a AgentRoutingLog.
   * @param {AgentRoutingLogDeleteArgs} args - Arguments to delete one AgentRoutingLog.
   * @example
   * // Delete one AgentRoutingLog
   * const AgentRoutingLog = await prisma.agentRoutingLog.delete({
   *   where: {
   *     // ... filter to delete one AgentRoutingLog
   *   }
   * })
   * 
   */
  delete<T extends AgentRoutingLogDeleteArgs>(args: Prisma.SelectSubset<T, AgentRoutingLogDeleteArgs<ExtArgs>>): Prisma.Prisma__AgentRoutingLogClient<runtime.Types.Result.GetResult<Prisma.$AgentRoutingLogPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one AgentRoutingLog.
   * @param {AgentRoutingLogUpdateArgs} args - Arguments to update one AgentRoutingLog.
   * @example
   * // Update one AgentRoutingLog
   * const agentRoutingLog = await prisma.agentRoutingLog.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends AgentRoutingLogUpdateArgs>(args: Prisma.SelectSubset<T, AgentRoutingLogUpdateArgs<ExtArgs>>): Prisma.Prisma__AgentRoutingLogClient<runtime.Types.Result.GetResult<Prisma.$AgentRoutingLogPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more AgentRoutingLogs.
   * @param {AgentRoutingLogDeleteManyArgs} args - Arguments to filter AgentRoutingLogs to delete.
   * @example
   * // Delete a few AgentRoutingLogs
   * const { count } = await prisma.agentRoutingLog.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends AgentRoutingLogDeleteManyArgs>(args?: Prisma.SelectSubset<T, AgentRoutingLogDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more AgentRoutingLogs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AgentRoutingLogUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many AgentRoutingLogs
   * const agentRoutingLog = await prisma.agentRoutingLog.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends AgentRoutingLogUpdateManyArgs>(args: Prisma.SelectSubset<T, AgentRoutingLogUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more AgentRoutingLogs and returns the data updated in the database.
   * @param {AgentRoutingLogUpdateManyAndReturnArgs} args - Arguments to update many AgentRoutingLogs.
   * @example
   * // Update many AgentRoutingLogs
   * const agentRoutingLog = await prisma.agentRoutingLog.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more AgentRoutingLogs and only return the `id`
   * const agentRoutingLogWithIdOnly = await prisma.agentRoutingLog.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends AgentRoutingLogUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, AgentRoutingLogUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AgentRoutingLogPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one AgentRoutingLog.
   * @param {AgentRoutingLogUpsertArgs} args - Arguments to update or create a AgentRoutingLog.
   * @example
   * // Update or create a AgentRoutingLog
   * const agentRoutingLog = await prisma.agentRoutingLog.upsert({
   *   create: {
   *     // ... data to create a AgentRoutingLog
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the AgentRoutingLog we want to update
   *   }
   * })
   */
  upsert<T extends AgentRoutingLogUpsertArgs>(args: Prisma.SelectSubset<T, AgentRoutingLogUpsertArgs<ExtArgs>>): Prisma.Prisma__AgentRoutingLogClient<runtime.Types.Result.GetResult<Prisma.$AgentRoutingLogPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of AgentRoutingLogs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AgentRoutingLogCountArgs} args - Arguments to filter AgentRoutingLogs to count.
   * @example
   * // Count the number of AgentRoutingLogs
   * const count = await prisma.agentRoutingLog.count({
   *   where: {
   *     // ... the filter for the AgentRoutingLogs we want to count
   *   }
   * })
  **/
  count<T extends AgentRoutingLogCountArgs>(
    args?: Prisma.Subset<T, AgentRoutingLogCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], AgentRoutingLogCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a AgentRoutingLog.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AgentRoutingLogAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends AgentRoutingLogAggregateArgs>(args: Prisma.Subset<T, AgentRoutingLogAggregateArgs>): Prisma.PrismaPromise<GetAgentRoutingLogAggregateType<T>>

  /**
   * Group by AgentRoutingLog.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AgentRoutingLogGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends AgentRoutingLogGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: AgentRoutingLogGroupByArgs['orderBy'] }
      : { orderBy?: AgentRoutingLogGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, AgentRoutingLogGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetAgentRoutingLogGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the AgentRoutingLog model
 */
readonly fields: AgentRoutingLogFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for AgentRoutingLog.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__AgentRoutingLogClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the AgentRoutingLog model
 */
export interface AgentRoutingLogFieldRefs {
  readonly id: Prisma.FieldRef<"AgentRoutingLog", 'String'>
  readonly conversationId: Prisma.FieldRef<"AgentRoutingLog", 'String'>
  readonly query: Prisma.FieldRef<"AgentRoutingLog", 'String'>
  readonly detectedIntent: Prisma.FieldRef<"AgentRoutingLog", 'String'>
  readonly selectedAgent: Prisma.FieldRef<"AgentRoutingLog", 'String'>
  readonly confidence: Prisma.FieldRef<"AgentRoutingLog", 'Float'>
  readonly reasoning: Prisma.FieldRef<"AgentRoutingLog", 'String'>
  readonly createdAt: Prisma.FieldRef<"AgentRoutingLog", 'DateTime'>
}
    

// Custom InputTypes
/**
 * AgentRoutingLog findUnique
 */
export type AgentRoutingLogFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AgentRoutingLog
   */
  select?: Prisma.AgentRoutingLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AgentRoutingLog
   */
  omit?: Prisma.AgentRoutingLogOmit<ExtArgs> | null
  /**
   * Filter, which AgentRoutingLog to fetch.
   */
  where: Prisma.AgentRoutingLogWhereUniqueInput
}

/**
 * AgentRoutingLog findUniqueOrThrow
 */
export type AgentRoutingLogFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AgentRoutingLog
   */
  select?: Prisma.AgentRoutingLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AgentRoutingLog
   */
  omit?: Prisma.AgentRoutingLogOmit<ExtArgs> | null
  /**
   * Filter, which AgentRoutingLog to fetch.
   */
  where: Prisma.AgentRoutingLogWhereUniqueInput
}

/**
 * AgentRoutingLog findFirst
 */
export type AgentRoutingLogFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AgentRoutingLog
   */
  select?: Prisma.AgentRoutingLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AgentRoutingLog
   */
  omit?: Prisma.AgentRoutingLogOmit<ExtArgs> | null
  /**
   * Filter, which AgentRoutingLog to fetch.
   */
  where?: Prisma.AgentRoutingLogWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AgentRoutingLogs to fetch.
   */
  orderBy?: Prisma.AgentRoutingLogOrderByWithRelationInput | Prisma.AgentRoutingLogOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for AgentRoutingLogs.
   */
  cursor?: Prisma.AgentRoutingLogWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AgentRoutingLogs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AgentRoutingLogs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AgentRoutingLogs.
   */
  distinct?: Prisma.AgentRoutingLogScalarFieldEnum | Prisma.AgentRoutingLogScalarFieldEnum[]
}

/**
 * AgentRoutingLog findFirstOrThrow
 */
export type AgentRoutingLogFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AgentRoutingLog
   */
  select?: Prisma.AgentRoutingLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AgentRoutingLog
   */
  omit?: Prisma.AgentRoutingLogOmit<ExtArgs> | null
  /**
   * Filter, which AgentRoutingLog to fetch.
   */
  where?: Prisma.AgentRoutingLogWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AgentRoutingLogs to fetch.
   */
  orderBy?: Prisma.AgentRoutingLogOrderByWithRelationInput | Prisma.AgentRoutingLogOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for AgentRoutingLogs.
   */
  cursor?: Prisma.AgentRoutingLogWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AgentRoutingLogs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AgentRoutingLogs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AgentRoutingLogs.
   */
  distinct?: Prisma.AgentRoutingLogScalarFieldEnum | Prisma.AgentRoutingLogScalarFieldEnum[]
}

/**
 * AgentRoutingLog findMany
 */
export type AgentRoutingLogFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AgentRoutingLog
   */
  select?: Prisma.AgentRoutingLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AgentRoutingLog
   */
  omit?: Prisma.AgentRoutingLogOmit<ExtArgs> | null
  /**
   * Filter, which AgentRoutingLogs to fetch.
   */
  where?: Prisma.AgentRoutingLogWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AgentRoutingLogs to fetch.
   */
  orderBy?: Prisma.AgentRoutingLogOrderByWithRelationInput | Prisma.AgentRoutingLogOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing AgentRoutingLogs.
   */
  cursor?: Prisma.AgentRoutingLogWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AgentRoutingLogs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AgentRoutingLogs.
   */
  skip?: number
  distinct?: Prisma.AgentRoutingLogScalarFieldEnum | Prisma.AgentRoutingLogScalarFieldEnum[]
}

/**
 * AgentRoutingLog create
 */
export type AgentRoutingLogCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AgentRoutingLog
   */
  select?: Prisma.AgentRoutingLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AgentRoutingLog
   */
  omit?: Prisma.AgentRoutingLogOmit<ExtArgs> | null
  /**
   * The data needed to create a AgentRoutingLog.
   */
  data: Prisma.XOR<Prisma.AgentRoutingLogCreateInput, Prisma.AgentRoutingLogUncheckedCreateInput>
}

/**
 * AgentRoutingLog createMany
 */
export type AgentRoutingLogCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many AgentRoutingLogs.
   */
  data: Prisma.AgentRoutingLogCreateManyInput | Prisma.AgentRoutingLogCreateManyInput[]
}

/**
 * AgentRoutingLog createManyAndReturn
 */
export type AgentRoutingLogCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AgentRoutingLog
   */
  select?: Prisma.AgentRoutingLogSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the AgentRoutingLog
   */
  omit?: Prisma.AgentRoutingLogOmit<ExtArgs> | null
  /**
   * The data used to create many AgentRoutingLogs.
   */
  data: Prisma.AgentRoutingLogCreateManyInput | Prisma.AgentRoutingLogCreateManyInput[]
}

/**
 * AgentRoutingLog update
 */
export type AgentRoutingLogUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AgentRoutingLog
   */
  select?: Prisma.AgentRoutingLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AgentRoutingLog
   */
  omit?: Prisma.AgentRoutingLogOmit<ExtArgs> | null
  /**
   * The data needed to update a AgentRoutingLog.
   */
  data: Prisma.XOR<Prisma.AgentRoutingLogUpdateInput, Prisma.AgentRoutingLogUncheckedUpdateInput>
  /**
   * Choose, which AgentRoutingLog to update.
   */
  where: Prisma.AgentRoutingLogWhereUniqueInput
}

/**
 * AgentRoutingLog updateMany
 */
export type AgentRoutingLogUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update AgentRoutingLogs.
   */
  data: Prisma.XOR<Prisma.AgentRoutingLogUpdateManyMutationInput, Prisma.AgentRoutingLogUncheckedUpdateManyInput>
  /**
   * Filter which AgentRoutingLogs to update
   */
  where?: Prisma.AgentRoutingLogWhereInput
  /**
   * Limit how many AgentRoutingLogs to update.
   */
  limit?: number
}

/**
 * AgentRoutingLog updateManyAndReturn
 */
export type AgentRoutingLogUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AgentRoutingLog
   */
  select?: Prisma.AgentRoutingLogSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the AgentRoutingLog
   */
  omit?: Prisma.AgentRoutingLogOmit<ExtArgs> | null
  /**
   * The data used to update AgentRoutingLogs.
   */
  data: Prisma.XOR<Prisma.AgentRoutingLogUpdateManyMutationInput, Prisma.AgentRoutingLogUncheckedUpdateManyInput>
  /**
   * Filter which AgentRoutingLogs to update
   */
  where?: Prisma.AgentRoutingLogWhereInput
  /**
   * Limit how many AgentRoutingLogs to update.
   */
  limit?: number
}

/**
 * AgentRoutingLog upsert
 */
export type AgentRoutingLogUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AgentRoutingLog
   */
  select?: Prisma.AgentRoutingLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AgentRoutingLog
   */
  omit?: Prisma.AgentRoutingLogOmit<ExtArgs> | null
  /**
   * The filter to search for the AgentRoutingLog to update in case it exists.
   */
  where: Prisma.AgentRoutingLogWhereUniqueInput
  /**
   * In case the AgentRoutingLog found by the `where` argument doesn't exist, create a new AgentRoutingLog with this data.
   */
  create: Prisma.XOR<Prisma.AgentRoutingLogCreateInput, Prisma.AgentRoutingLogUncheckedCreateInput>
  /**
   * In case the AgentRoutingLog was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.AgentRoutingLogUpdateInput, Prisma.AgentRoutingLogUncheckedUpdateInput>
}

/**
 * AgentRoutingLog delete
 */
export type AgentRoutingLogDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AgentRoutingLog
   */
  select?: Prisma.AgentRoutingLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AgentRoutingLog
   */
  omit?: Prisma.AgentRoutingLogOmit<ExtArgs> | null
  /**
   * Filter which AgentRoutingLog to delete.
   */
  where: Prisma.AgentRoutingLogWhereUniqueInput
}

/**
 * AgentRoutingLog deleteMany
 */
export type AgentRoutingLogDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which AgentRoutingLogs to delete
   */
  where?: Prisma.AgentRoutingLogWhereInput
  /**
   * Limit how many AgentRoutingLogs to delete.
   */
  limit?: number
}

/**
 * AgentRoutingLog without action
 */
export type AgentRoutingLogDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AgentRoutingLog
   */
  select?: Prisma.AgentRoutingLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AgentRoutingLog
   */
  omit?: Prisma.AgentRoutingLogOmit<ExtArgs> | null
}
