
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `MessageSource` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model MessageSource
 * 
 */
export type MessageSourceModel = runtime.Types.Result.DefaultSelection<Prisma.$MessageSourcePayload>

export type AggregateMessageSource = {
  _count: MessageSourceCountAggregateOutputType | null
  _avg: MessageSourceAvgAggregateOutputType | null
  _sum: MessageSourceSumAggregateOutputType | null
  _min: MessageSourceMinAggregateOutputType | null
  _max: MessageSourceMaxAggregateOutputType | null
}

export type MessageSourceAvgAggregateOutputType = {
  rankPosition: number | null
  similarity: number | null
}

export type MessageSourceSumAggregateOutputType = {
  rankPosition: number | null
  similarity: number | null
}

export type MessageSourceMinAggregateOutputType = {
  id: string | null
  messageId: string | null
  documentId: string | null
  chunkId: string | null
  rankPosition: number | null
  similarity: number | null
  createdAt: Date | null
}

export type MessageSourceMaxAggregateOutputType = {
  id: string | null
  messageId: string | null
  documentId: string | null
  chunkId: string | null
  rankPosition: number | null
  similarity: number | null
  createdAt: Date | null
}

export type MessageSourceCountAggregateOutputType = {
  id: number
  messageId: number
  documentId: number
  chunkId: number
  rankPosition: number
  similarity: number
  createdAt: number
  _all: number
}


export type MessageSourceAvgAggregateInputType = {
  rankPosition?: true
  similarity?: true
}

export type MessageSourceSumAggregateInputType = {
  rankPosition?: true
  similarity?: true
}

export type MessageSourceMinAggregateInputType = {
  id?: true
  messageId?: true
  documentId?: true
  chunkId?: true
  rankPosition?: true
  similarity?: true
  createdAt?: true
}

export type MessageSourceMaxAggregateInputType = {
  id?: true
  messageId?: true
  documentId?: true
  chunkId?: true
  rankPosition?: true
  similarity?: true
  createdAt?: true
}

export type MessageSourceCountAggregateInputType = {
  id?: true
  messageId?: true
  documentId?: true
  chunkId?: true
  rankPosition?: true
  similarity?: true
  createdAt?: true
  _all?: true
}

export type MessageSourceAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which MessageSource to aggregate.
   */
  where?: Prisma.MessageSourceWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MessageSources to fetch.
   */
  orderBy?: Prisma.MessageSourceOrderByWithRelationInput | Prisma.MessageSourceOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.MessageSourceWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MessageSources from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MessageSources.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned MessageSources
  **/
  _count?: true | MessageSourceCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: MessageSourceAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: MessageSourceSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: MessageSourceMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: MessageSourceMaxAggregateInputType
}

export type GetMessageSourceAggregateType<T extends MessageSourceAggregateArgs> = {
      [P in keyof T & keyof AggregateMessageSource]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateMessageSource[P]>
    : Prisma.GetScalarType<T[P], AggregateMessageSource[P]>
}




export type MessageSourceGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.MessageSourceWhereInput
  orderBy?: Prisma.MessageSourceOrderByWithAggregationInput | Prisma.MessageSourceOrderByWithAggregationInput[]
  by: Prisma.MessageSourceScalarFieldEnum[] | Prisma.MessageSourceScalarFieldEnum
  having?: Prisma.MessageSourceScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: MessageSourceCountAggregateInputType | true
  _avg?: MessageSourceAvgAggregateInputType
  _sum?: MessageSourceSumAggregateInputType
  _min?: MessageSourceMinAggregateInputType
  _max?: MessageSourceMaxAggregateInputType
}

export type MessageSourceGroupByOutputType = {
  id: string
  messageId: string
  documentId: string
  chunkId: string
  rankPosition: number
  similarity: number
  createdAt: Date
  _count: MessageSourceCountAggregateOutputType | null
  _avg: MessageSourceAvgAggregateOutputType | null
  _sum: MessageSourceSumAggregateOutputType | null
  _min: MessageSourceMinAggregateOutputType | null
  _max: MessageSourceMaxAggregateOutputType | null
}

type GetMessageSourceGroupByPayload<T extends MessageSourceGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<MessageSourceGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof MessageSourceGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], MessageSourceGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], MessageSourceGroupByOutputType[P]>
      }
    >
  >



export type MessageSourceWhereInput = {
  AND?: Prisma.MessageSourceWhereInput | Prisma.MessageSourceWhereInput[]
  OR?: Prisma.MessageSourceWhereInput[]
  NOT?: Prisma.MessageSourceWhereInput | Prisma.MessageSourceWhereInput[]
  id?: Prisma.StringFilter<"MessageSource"> | string
  messageId?: Prisma.StringFilter<"MessageSource"> | string
  documentId?: Prisma.StringFilter<"MessageSource"> | string
  chunkId?: Prisma.StringFilter<"MessageSource"> | string
  rankPosition?: Prisma.IntFilter<"MessageSource"> | number
  similarity?: Prisma.FloatFilter<"MessageSource"> | number
  createdAt?: Prisma.DateTimeFilter<"MessageSource"> | Date | string
  message?: Prisma.XOR<Prisma.MessageScalarRelationFilter, Prisma.MessageWhereInput>
  document?: Prisma.XOR<Prisma.DocumentScalarRelationFilter, Prisma.DocumentWhereInput>
  chunk?: Prisma.XOR<Prisma.DocumentChunkScalarRelationFilter, Prisma.DocumentChunkWhereInput>
}

export type MessageSourceOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  messageId?: Prisma.SortOrder
  documentId?: Prisma.SortOrder
  chunkId?: Prisma.SortOrder
  rankPosition?: Prisma.SortOrder
  similarity?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  message?: Prisma.MessageOrderByWithRelationInput
  document?: Prisma.DocumentOrderByWithRelationInput
  chunk?: Prisma.DocumentChunkOrderByWithRelationInput
}

export type MessageSourceWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.MessageSourceWhereInput | Prisma.MessageSourceWhereInput[]
  OR?: Prisma.MessageSourceWhereInput[]
  NOT?: Prisma.MessageSourceWhereInput | Prisma.MessageSourceWhereInput[]
  messageId?: Prisma.StringFilter<"MessageSource"> | string
  documentId?: Prisma.StringFilter<"MessageSource"> | string
  chunkId?: Prisma.StringFilter<"MessageSource"> | string
  rankPosition?: Prisma.IntFilter<"MessageSource"> | number
  similarity?: Prisma.FloatFilter<"MessageSource"> | number
  createdAt?: Prisma.DateTimeFilter<"MessageSource"> | Date | string
  message?: Prisma.XOR<Prisma.MessageScalarRelationFilter, Prisma.MessageWhereInput>
  document?: Prisma.XOR<Prisma.DocumentScalarRelationFilter, Prisma.DocumentWhereInput>
  chunk?: Prisma.XOR<Prisma.DocumentChunkScalarRelationFilter, Prisma.DocumentChunkWhereInput>
}, "id">

export type MessageSourceOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  messageId?: Prisma.SortOrder
  documentId?: Prisma.SortOrder
  chunkId?: Prisma.SortOrder
  rankPosition?: Prisma.SortOrder
  similarity?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.MessageSourceCountOrderByAggregateInput
  _avg?: Prisma.MessageSourceAvgOrderByAggregateInput
  _max?: Prisma.MessageSourceMaxOrderByAggregateInput
  _min?: Prisma.MessageSourceMinOrderByAggregateInput
  _sum?: Prisma.MessageSourceSumOrderByAggregateInput
}

export type MessageSourceScalarWhereWithAggregatesInput = {
  AND?: Prisma.MessageSourceScalarWhereWithAggregatesInput | Prisma.MessageSourceScalarWhereWithAggregatesInput[]
  OR?: Prisma.MessageSourceScalarWhereWithAggregatesInput[]
  NOT?: Prisma.MessageSourceScalarWhereWithAggregatesInput | Prisma.MessageSourceScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"MessageSource"> | string
  messageId?: Prisma.StringWithAggregatesFilter<"MessageSource"> | string
  documentId?: Prisma.StringWithAggregatesFilter<"MessageSource"> | string
  chunkId?: Prisma.StringWithAggregatesFilter<"MessageSource"> | string
  rankPosition?: Prisma.IntWithAggregatesFilter<"MessageSource"> | number
  similarity?: Prisma.FloatWithAggregatesFilter<"MessageSource"> | number
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"MessageSource"> | Date | string
}

export type MessageSourceCreateInput = {
  id?: string
  rankPosition: number
  similarity: number
  createdAt?: Date | string
  message: Prisma.MessageCreateNestedOneWithoutSourcesInput
  document: Prisma.DocumentCreateNestedOneWithoutMessageSourcesInput
  chunk: Prisma.DocumentChunkCreateNestedOneWithoutMessageSourcesInput
}

export type MessageSourceUncheckedCreateInput = {
  id?: string
  messageId: string
  documentId: string
  chunkId: string
  rankPosition: number
  similarity: number
  createdAt?: Date | string
}

export type MessageSourceUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  rankPosition?: Prisma.IntFieldUpdateOperationsInput | number
  similarity?: Prisma.FloatFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  message?: Prisma.MessageUpdateOneRequiredWithoutSourcesNestedInput
  document?: Prisma.DocumentUpdateOneRequiredWithoutMessageSourcesNestedInput
  chunk?: Prisma.DocumentChunkUpdateOneRequiredWithoutMessageSourcesNestedInput
}

export type MessageSourceUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  messageId?: Prisma.StringFieldUpdateOperationsInput | string
  documentId?: Prisma.StringFieldUpdateOperationsInput | string
  chunkId?: Prisma.StringFieldUpdateOperationsInput | string
  rankPosition?: Prisma.IntFieldUpdateOperationsInput | number
  similarity?: Prisma.FloatFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MessageSourceCreateManyInput = {
  id?: string
  messageId: string
  documentId: string
  chunkId: string
  rankPosition: number
  similarity: number
  createdAt?: Date | string
}

export type MessageSourceUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  rankPosition?: Prisma.IntFieldUpdateOperationsInput | number
  similarity?: Prisma.FloatFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MessageSourceUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  messageId?: Prisma.StringFieldUpdateOperationsInput | string
  documentId?: Prisma.StringFieldUpdateOperationsInput | string
  chunkId?: Prisma.StringFieldUpdateOperationsInput | string
  rankPosition?: Prisma.IntFieldUpdateOperationsInput | number
  similarity?: Prisma.FloatFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MessageSourceListRelationFilter = {
  every?: Prisma.MessageSourceWhereInput
  some?: Prisma.MessageSourceWhereInput
  none?: Prisma.MessageSourceWhereInput
}

export type MessageSourceOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type MessageSourceCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  messageId?: Prisma.SortOrder
  documentId?: Prisma.SortOrder
  chunkId?: Prisma.SortOrder
  rankPosition?: Prisma.SortOrder
  similarity?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type MessageSourceAvgOrderByAggregateInput = {
  rankPosition?: Prisma.SortOrder
  similarity?: Prisma.SortOrder
}

export type MessageSourceMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  messageId?: Prisma.SortOrder
  documentId?: Prisma.SortOrder
  chunkId?: Prisma.SortOrder
  rankPosition?: Prisma.SortOrder
  similarity?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type MessageSourceMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  messageId?: Prisma.SortOrder
  documentId?: Prisma.SortOrder
  chunkId?: Prisma.SortOrder
  rankPosition?: Prisma.SortOrder
  similarity?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type MessageSourceSumOrderByAggregateInput = {
  rankPosition?: Prisma.SortOrder
  similarity?: Prisma.SortOrder
}

export type MessageSourceCreateNestedManyWithoutMessageInput = {
  create?: Prisma.XOR<Prisma.MessageSourceCreateWithoutMessageInput, Prisma.MessageSourceUncheckedCreateWithoutMessageInput> | Prisma.MessageSourceCreateWithoutMessageInput[] | Prisma.MessageSourceUncheckedCreateWithoutMessageInput[]
  connectOrCreate?: Prisma.MessageSourceCreateOrConnectWithoutMessageInput | Prisma.MessageSourceCreateOrConnectWithoutMessageInput[]
  createMany?: Prisma.MessageSourceCreateManyMessageInputEnvelope
  connect?: Prisma.MessageSourceWhereUniqueInput | Prisma.MessageSourceWhereUniqueInput[]
}

export type MessageSourceUncheckedCreateNestedManyWithoutMessageInput = {
  create?: Prisma.XOR<Prisma.MessageSourceCreateWithoutMessageInput, Prisma.MessageSourceUncheckedCreateWithoutMessageInput> | Prisma.MessageSourceCreateWithoutMessageInput[] | Prisma.MessageSourceUncheckedCreateWithoutMessageInput[]
  connectOrCreate?: Prisma.MessageSourceCreateOrConnectWithoutMessageInput | Prisma.MessageSourceCreateOrConnectWithoutMessageInput[]
  createMany?: Prisma.MessageSourceCreateManyMessageInputEnvelope
  connect?: Prisma.MessageSourceWhereUniqueInput | Prisma.MessageSourceWhereUniqueInput[]
}

export type MessageSourceUpdateManyWithoutMessageNestedInput = {
  create?: Prisma.XOR<Prisma.MessageSourceCreateWithoutMessageInput, Prisma.MessageSourceUncheckedCreateWithoutMessageInput> | Prisma.MessageSourceCreateWithoutMessageInput[] | Prisma.MessageSourceUncheckedCreateWithoutMessageInput[]
  connectOrCreate?: Prisma.MessageSourceCreateOrConnectWithoutMessageInput | Prisma.MessageSourceCreateOrConnectWithoutMessageInput[]
  upsert?: Prisma.MessageSourceUpsertWithWhereUniqueWithoutMessageInput | Prisma.MessageSourceUpsertWithWhereUniqueWithoutMessageInput[]
  createMany?: Prisma.MessageSourceCreateManyMessageInputEnvelope
  set?: Prisma.MessageSourceWhereUniqueInput | Prisma.MessageSourceWhereUniqueInput[]
  disconnect?: Prisma.MessageSourceWhereUniqueInput | Prisma.MessageSourceWhereUniqueInput[]
  delete?: Prisma.MessageSourceWhereUniqueInput | Prisma.MessageSourceWhereUniqueInput[]
  connect?: Prisma.MessageSourceWhereUniqueInput | Prisma.MessageSourceWhereUniqueInput[]
  update?: Prisma.MessageSourceUpdateWithWhereUniqueWithoutMessageInput | Prisma.MessageSourceUpdateWithWhereUniqueWithoutMessageInput[]
  updateMany?: Prisma.MessageSourceUpdateManyWithWhereWithoutMessageInput | Prisma.MessageSourceUpdateManyWithWhereWithoutMessageInput[]
  deleteMany?: Prisma.MessageSourceScalarWhereInput | Prisma.MessageSourceScalarWhereInput[]
}

export type MessageSourceUncheckedUpdateManyWithoutMessageNestedInput = {
  create?: Prisma.XOR<Prisma.MessageSourceCreateWithoutMessageInput, Prisma.MessageSourceUncheckedCreateWithoutMessageInput> | Prisma.MessageSourceCreateWithoutMessageInput[] | Prisma.MessageSourceUncheckedCreateWithoutMessageInput[]
  connectOrCreate?: Prisma.MessageSourceCreateOrConnectWithoutMessageInput | Prisma.MessageSourceCreateOrConnectWithoutMessageInput[]
  upsert?: Prisma.MessageSourceUpsertWithWhereUniqueWithoutMessageInput | Prisma.MessageSourceUpsertWithWhereUniqueWithoutMessageInput[]
  createMany?: Prisma.MessageSourceCreateManyMessageInputEnvelope
  set?: Prisma.MessageSourceWhereUniqueInput | Prisma.MessageSourceWhereUniqueInput[]
  disconnect?: Prisma.MessageSourceWhereUniqueInput | Prisma.MessageSourceWhereUniqueInput[]
  delete?: Prisma.MessageSourceWhereUniqueInput | Prisma.MessageSourceWhereUniqueInput[]
  connect?: Prisma.MessageSourceWhereUniqueInput | Prisma.MessageSourceWhereUniqueInput[]
  update?: Prisma.MessageSourceUpdateWithWhereUniqueWithoutMessageInput | Prisma.MessageSourceUpdateWithWhereUniqueWithoutMessageInput[]
  updateMany?: Prisma.MessageSourceUpdateManyWithWhereWithoutMessageInput | Prisma.MessageSourceUpdateManyWithWhereWithoutMessageInput[]
  deleteMany?: Prisma.MessageSourceScalarWhereInput | Prisma.MessageSourceScalarWhereInput[]
}

export type MessageSourceCreateNestedManyWithoutDocumentInput = {
  create?: Prisma.XOR<Prisma.MessageSourceCreateWithoutDocumentInput, Prisma.MessageSourceUncheckedCreateWithoutDocumentInput> | Prisma.MessageSourceCreateWithoutDocumentInput[] | Prisma.MessageSourceUncheckedCreateWithoutDocumentInput[]
  connectOrCreate?: Prisma.MessageSourceCreateOrConnectWithoutDocumentInput | Prisma.MessageSourceCreateOrConnectWithoutDocumentInput[]
  createMany?: Prisma.MessageSourceCreateManyDocumentInputEnvelope
  connect?: Prisma.MessageSourceWhereUniqueInput | Prisma.MessageSourceWhereUniqueInput[]
}

export type MessageSourceUncheckedCreateNestedManyWithoutDocumentInput = {
  create?: Prisma.XOR<Prisma.MessageSourceCreateWithoutDocumentInput, Prisma.MessageSourceUncheckedCreateWithoutDocumentInput> | Prisma.MessageSourceCreateWithoutDocumentInput[] | Prisma.MessageSourceUncheckedCreateWithoutDocumentInput[]
  connectOrCreate?: Prisma.MessageSourceCreateOrConnectWithoutDocumentInput | Prisma.MessageSourceCreateOrConnectWithoutDocumentInput[]
  createMany?: Prisma.MessageSourceCreateManyDocumentInputEnvelope
  connect?: Prisma.MessageSourceWhereUniqueInput | Prisma.MessageSourceWhereUniqueInput[]
}

export type MessageSourceUpdateManyWithoutDocumentNestedInput = {
  create?: Prisma.XOR<Prisma.MessageSourceCreateWithoutDocumentInput, Prisma.MessageSourceUncheckedCreateWithoutDocumentInput> | Prisma.MessageSourceCreateWithoutDocumentInput[] | Prisma.MessageSourceUncheckedCreateWithoutDocumentInput[]
  connectOrCreate?: Prisma.MessageSourceCreateOrConnectWithoutDocumentInput | Prisma.MessageSourceCreateOrConnectWithoutDocumentInput[]
  upsert?: Prisma.MessageSourceUpsertWithWhereUniqueWithoutDocumentInput | Prisma.MessageSourceUpsertWithWhereUniqueWithoutDocumentInput[]
  createMany?: Prisma.MessageSourceCreateManyDocumentInputEnvelope
  set?: Prisma.MessageSourceWhereUniqueInput | Prisma.MessageSourceWhereUniqueInput[]
  disconnect?: Prisma.MessageSourceWhereUniqueInput | Prisma.MessageSourceWhereUniqueInput[]
  delete?: Prisma.MessageSourceWhereUniqueInput | Prisma.MessageSourceWhereUniqueInput[]
  connect?: Prisma.MessageSourceWhereUniqueInput | Prisma.MessageSourceWhereUniqueInput[]
  update?: Prisma.MessageSourceUpdateWithWhereUniqueWithoutDocumentInput | Prisma.MessageSourceUpdateWithWhereUniqueWithoutDocumentInput[]
  updateMany?: Prisma.MessageSourceUpdateManyWithWhereWithoutDocumentInput | Prisma.MessageSourceUpdateManyWithWhereWithoutDocumentInput[]
  deleteMany?: Prisma.MessageSourceScalarWhereInput | Prisma.MessageSourceScalarWhereInput[]
}

export type MessageSourceUncheckedUpdateManyWithoutDocumentNestedInput = {
  create?: Prisma.XOR<Prisma.MessageSourceCreateWithoutDocumentInput, Prisma.MessageSourceUncheckedCreateWithoutDocumentInput> | Prisma.MessageSourceCreateWithoutDocumentInput[] | Prisma.MessageSourceUncheckedCreateWithoutDocumentInput[]
  connectOrCreate?: Prisma.MessageSourceCreateOrConnectWithoutDocumentInput | Prisma.MessageSourceCreateOrConnectWithoutDocumentInput[]
  upsert?: Prisma.MessageSourceUpsertWithWhereUniqueWithoutDocumentInput | Prisma.MessageSourceUpsertWithWhereUniqueWithoutDocumentInput[]
  createMany?: Prisma.MessageSourceCreateManyDocumentInputEnvelope
  set?: Prisma.MessageSourceWhereUniqueInput | Prisma.MessageSourceWhereUniqueInput[]
  disconnect?: Prisma.MessageSourceWhereUniqueInput | Prisma.MessageSourceWhereUniqueInput[]
  delete?: Prisma.MessageSourceWhereUniqueInput | Prisma.MessageSourceWhereUniqueInput[]
  connect?: Prisma.MessageSourceWhereUniqueInput | Prisma.MessageSourceWhereUniqueInput[]
  update?: Prisma.MessageSourceUpdateWithWhereUniqueWithoutDocumentInput | Prisma.MessageSourceUpdateWithWhereUniqueWithoutDocumentInput[]
  updateMany?: Prisma.MessageSourceUpdateManyWithWhereWithoutDocumentInput | Prisma.MessageSourceUpdateManyWithWhereWithoutDocumentInput[]
  deleteMany?: Prisma.MessageSourceScalarWhereInput | Prisma.MessageSourceScalarWhereInput[]
}

export type MessageSourceCreateNestedManyWithoutChunkInput = {
  create?: Prisma.XOR<Prisma.MessageSourceCreateWithoutChunkInput, Prisma.MessageSourceUncheckedCreateWithoutChunkInput> | Prisma.MessageSourceCreateWithoutChunkInput[] | Prisma.MessageSourceUncheckedCreateWithoutChunkInput[]
  connectOrCreate?: Prisma.MessageSourceCreateOrConnectWithoutChunkInput | Prisma.MessageSourceCreateOrConnectWithoutChunkInput[]
  createMany?: Prisma.MessageSourceCreateManyChunkInputEnvelope
  connect?: Prisma.MessageSourceWhereUniqueInput | Prisma.MessageSourceWhereUniqueInput[]
}

export type MessageSourceUncheckedCreateNestedManyWithoutChunkInput = {
  create?: Prisma.XOR<Prisma.MessageSourceCreateWithoutChunkInput, Prisma.MessageSourceUncheckedCreateWithoutChunkInput> | Prisma.MessageSourceCreateWithoutChunkInput[] | Prisma.MessageSourceUncheckedCreateWithoutChunkInput[]
  connectOrCreate?: Prisma.MessageSourceCreateOrConnectWithoutChunkInput | Prisma.MessageSourceCreateOrConnectWithoutChunkInput[]
  createMany?: Prisma.MessageSourceCreateManyChunkInputEnvelope
  connect?: Prisma.MessageSourceWhereUniqueInput | Prisma.MessageSourceWhereUniqueInput[]
}

export type MessageSourceUpdateManyWithoutChunkNestedInput = {
  create?: Prisma.XOR<Prisma.MessageSourceCreateWithoutChunkInput, Prisma.MessageSourceUncheckedCreateWithoutChunkInput> | Prisma.MessageSourceCreateWithoutChunkInput[] | Prisma.MessageSourceUncheckedCreateWithoutChunkInput[]
  connectOrCreate?: Prisma.MessageSourceCreateOrConnectWithoutChunkInput | Prisma.MessageSourceCreateOrConnectWithoutChunkInput[]
  upsert?: Prisma.MessageSourceUpsertWithWhereUniqueWithoutChunkInput | Prisma.MessageSourceUpsertWithWhereUniqueWithoutChunkInput[]
  createMany?: Prisma.MessageSourceCreateManyChunkInputEnvelope
  set?: Prisma.MessageSourceWhereUniqueInput | Prisma.MessageSourceWhereUniqueInput[]
  disconnect?: Prisma.MessageSourceWhereUniqueInput | Prisma.MessageSourceWhereUniqueInput[]
  delete?: Prisma.MessageSourceWhereUniqueInput | Prisma.MessageSourceWhereUniqueInput[]
  connect?: Prisma.MessageSourceWhereUniqueInput | Prisma.MessageSourceWhereUniqueInput[]
  update?: Prisma.MessageSourceUpdateWithWhereUniqueWithoutChunkInput | Prisma.MessageSourceUpdateWithWhereUniqueWithoutChunkInput[]
  updateMany?: Prisma.MessageSourceUpdateManyWithWhereWithoutChunkInput | Prisma.MessageSourceUpdateManyWithWhereWithoutChunkInput[]
  deleteMany?: Prisma.MessageSourceScalarWhereInput | Prisma.MessageSourceScalarWhereInput[]
}

export type MessageSourceUncheckedUpdateManyWithoutChunkNestedInput = {
  create?: Prisma.XOR<Prisma.MessageSourceCreateWithoutChunkInput, Prisma.MessageSourceUncheckedCreateWithoutChunkInput> | Prisma.MessageSourceCreateWithoutChunkInput[] | Prisma.MessageSourceUncheckedCreateWithoutChunkInput[]
  connectOrCreate?: Prisma.MessageSourceCreateOrConnectWithoutChunkInput | Prisma.MessageSourceCreateOrConnectWithoutChunkInput[]
  upsert?: Prisma.MessageSourceUpsertWithWhereUniqueWithoutChunkInput | Prisma.MessageSourceUpsertWithWhereUniqueWithoutChunkInput[]
  createMany?: Prisma.MessageSourceCreateManyChunkInputEnvelope
  set?: Prisma.MessageSourceWhereUniqueInput | Prisma.MessageSourceWhereUniqueInput[]
  disconnect?: Prisma.MessageSourceWhereUniqueInput | Prisma.MessageSourceWhereUniqueInput[]
  delete?: Prisma.MessageSourceWhereUniqueInput | Prisma.MessageSourceWhereUniqueInput[]
  connect?: Prisma.MessageSourceWhereUniqueInput | Prisma.MessageSourceWhereUniqueInput[]
  update?: Prisma.MessageSourceUpdateWithWhereUniqueWithoutChunkInput | Prisma.MessageSourceUpdateWithWhereUniqueWithoutChunkInput[]
  updateMany?: Prisma.MessageSourceUpdateManyWithWhereWithoutChunkInput | Prisma.MessageSourceUpdateManyWithWhereWithoutChunkInput[]
  deleteMany?: Prisma.MessageSourceScalarWhereInput | Prisma.MessageSourceScalarWhereInput[]
}

export type FloatFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type MessageSourceCreateWithoutMessageInput = {
  id?: string
  rankPosition: number
  similarity: number
  createdAt?: Date | string
  document: Prisma.DocumentCreateNestedOneWithoutMessageSourcesInput
  chunk: Prisma.DocumentChunkCreateNestedOneWithoutMessageSourcesInput
}

export type MessageSourceUncheckedCreateWithoutMessageInput = {
  id?: string
  documentId: string
  chunkId: string
  rankPosition: number
  similarity: number
  createdAt?: Date | string
}

export type MessageSourceCreateOrConnectWithoutMessageInput = {
  where: Prisma.MessageSourceWhereUniqueInput
  create: Prisma.XOR<Prisma.MessageSourceCreateWithoutMessageInput, Prisma.MessageSourceUncheckedCreateWithoutMessageInput>
}

export type MessageSourceCreateManyMessageInputEnvelope = {
  data: Prisma.MessageSourceCreateManyMessageInput | Prisma.MessageSourceCreateManyMessageInput[]
}

export type MessageSourceUpsertWithWhereUniqueWithoutMessageInput = {
  where: Prisma.MessageSourceWhereUniqueInput
  update: Prisma.XOR<Prisma.MessageSourceUpdateWithoutMessageInput, Prisma.MessageSourceUncheckedUpdateWithoutMessageInput>
  create: Prisma.XOR<Prisma.MessageSourceCreateWithoutMessageInput, Prisma.MessageSourceUncheckedCreateWithoutMessageInput>
}

export type MessageSourceUpdateWithWhereUniqueWithoutMessageInput = {
  where: Prisma.MessageSourceWhereUniqueInput
  data: Prisma.XOR<Prisma.MessageSourceUpdateWithoutMessageInput, Prisma.MessageSourceUncheckedUpdateWithoutMessageInput>
}

export type MessageSourceUpdateManyWithWhereWithoutMessageInput = {
  where: Prisma.MessageSourceScalarWhereInput
  data: Prisma.XOR<Prisma.MessageSourceUpdateManyMutationInput, Prisma.MessageSourceUncheckedUpdateManyWithoutMessageInput>
}

export type MessageSourceScalarWhereInput = {
  AND?: Prisma.MessageSourceScalarWhereInput | Prisma.MessageSourceScalarWhereInput[]
  OR?: Prisma.MessageSourceScalarWhereInput[]
  NOT?: Prisma.MessageSourceScalarWhereInput | Prisma.MessageSourceScalarWhereInput[]
  id?: Prisma.StringFilter<"MessageSource"> | string
  messageId?: Prisma.StringFilter<"MessageSource"> | string
  documentId?: Prisma.StringFilter<"MessageSource"> | string
  chunkId?: Prisma.StringFilter<"MessageSource"> | string
  rankPosition?: Prisma.IntFilter<"MessageSource"> | number
  similarity?: Prisma.FloatFilter<"MessageSource"> | number
  createdAt?: Prisma.DateTimeFilter<"MessageSource"> | Date | string
}

export type MessageSourceCreateWithoutDocumentInput = {
  id?: string
  rankPosition: number
  similarity: number
  createdAt?: Date | string
  message: Prisma.MessageCreateNestedOneWithoutSourcesInput
  chunk: Prisma.DocumentChunkCreateNestedOneWithoutMessageSourcesInput
}

export type MessageSourceUncheckedCreateWithoutDocumentInput = {
  id?: string
  messageId: string
  chunkId: string
  rankPosition: number
  similarity: number
  createdAt?: Date | string
}

export type MessageSourceCreateOrConnectWithoutDocumentInput = {
  where: Prisma.MessageSourceWhereUniqueInput
  create: Prisma.XOR<Prisma.MessageSourceCreateWithoutDocumentInput, Prisma.MessageSourceUncheckedCreateWithoutDocumentInput>
}

export type MessageSourceCreateManyDocumentInputEnvelope = {
  data: Prisma.MessageSourceCreateManyDocumentInput | Prisma.MessageSourceCreateManyDocumentInput[]
}

export type MessageSourceUpsertWithWhereUniqueWithoutDocumentInput = {
  where: Prisma.MessageSourceWhereUniqueInput
  update: Prisma.XOR<Prisma.MessageSourceUpdateWithoutDocumentInput, Prisma.MessageSourceUncheckedUpdateWithoutDocumentInput>
  create: Prisma.XOR<Prisma.MessageSourceCreateWithoutDocumentInput, Prisma.MessageSourceUncheckedCreateWithoutDocumentInput>
}

export type MessageSourceUpdateWithWhereUniqueWithoutDocumentInput = {
  where: Prisma.MessageSourceWhereUniqueInput
  data: Prisma.XOR<Prisma.MessageSourceUpdateWithoutDocumentInput, Prisma.MessageSourceUncheckedUpdateWithoutDocumentInput>
}

export type MessageSourceUpdateManyWithWhereWithoutDocumentInput = {
  where: Prisma.MessageSourceScalarWhereInput
  data: Prisma.XOR<Prisma.MessageSourceUpdateManyMutationInput, Prisma.MessageSourceUncheckedUpdateManyWithoutDocumentInput>
}

export type MessageSourceCreateWithoutChunkInput = {
  id?: string
  rankPosition: number
  similarity: number
  createdAt?: Date | string
  message: Prisma.MessageCreateNestedOneWithoutSourcesInput
  document: Prisma.DocumentCreateNestedOneWithoutMessageSourcesInput
}

export type MessageSourceUncheckedCreateWithoutChunkInput = {
  id?: string
  messageId: string
  documentId: string
  rankPosition: number
  similarity: number
  createdAt?: Date | string
}

export type MessageSourceCreateOrConnectWithoutChunkInput = {
  where: Prisma.MessageSourceWhereUniqueInput
  create: Prisma.XOR<Prisma.MessageSourceCreateWithoutChunkInput, Prisma.MessageSourceUncheckedCreateWithoutChunkInput>
}

export type MessageSourceCreateManyChunkInputEnvelope = {
  data: Prisma.MessageSourceCreateManyChunkInput | Prisma.MessageSourceCreateManyChunkInput[]
}

export type MessageSourceUpsertWithWhereUniqueWithoutChunkInput = {
  where: Prisma.MessageSourceWhereUniqueInput
  update: Prisma.XOR<Prisma.MessageSourceUpdateWithoutChunkInput, Prisma.MessageSourceUncheckedUpdateWithoutChunkInput>
  create: Prisma.XOR<Prisma.MessageSourceCreateWithoutChunkInput, Prisma.MessageSourceUncheckedCreateWithoutChunkInput>
}

export type MessageSourceUpdateWithWhereUniqueWithoutChunkInput = {
  where: Prisma.MessageSourceWhereUniqueInput
  data: Prisma.XOR<Prisma.MessageSourceUpdateWithoutChunkInput, Prisma.MessageSourceUncheckedUpdateWithoutChunkInput>
}

export type MessageSourceUpdateManyWithWhereWithoutChunkInput = {
  where: Prisma.MessageSourceScalarWhereInput
  data: Prisma.XOR<Prisma.MessageSourceUpdateManyMutationInput, Prisma.MessageSourceUncheckedUpdateManyWithoutChunkInput>
}

export type MessageSourceCreateManyMessageInput = {
  id?: string
  documentId: string
  chunkId: string
  rankPosition: number
  similarity: number
  createdAt?: Date | string
}

export type MessageSourceUpdateWithoutMessageInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  rankPosition?: Prisma.IntFieldUpdateOperationsInput | number
  similarity?: Prisma.FloatFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  document?: Prisma.DocumentUpdateOneRequiredWithoutMessageSourcesNestedInput
  chunk?: Prisma.DocumentChunkUpdateOneRequiredWithoutMessageSourcesNestedInput
}

export type MessageSourceUncheckedUpdateWithoutMessageInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  documentId?: Prisma.StringFieldUpdateOperationsInput | string
  chunkId?: Prisma.StringFieldUpdateOperationsInput | string
  rankPosition?: Prisma.IntFieldUpdateOperationsInput | number
  similarity?: Prisma.FloatFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MessageSourceUncheckedUpdateManyWithoutMessageInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  documentId?: Prisma.StringFieldUpdateOperationsInput | string
  chunkId?: Prisma.StringFieldUpdateOperationsInput | string
  rankPosition?: Prisma.IntFieldUpdateOperationsInput | number
  similarity?: Prisma.FloatFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MessageSourceCreateManyDocumentInput = {
  id?: string
  messageId: string
  chunkId: string
  rankPosition: number
  similarity: number
  createdAt?: Date | string
}

export type MessageSourceUpdateWithoutDocumentInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  rankPosition?: Prisma.IntFieldUpdateOperationsInput | number
  similarity?: Prisma.FloatFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  message?: Prisma.MessageUpdateOneRequiredWithoutSourcesNestedInput
  chunk?: Prisma.DocumentChunkUpdateOneRequiredWithoutMessageSourcesNestedInput
}

export type MessageSourceUncheckedUpdateWithoutDocumentInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  messageId?: Prisma.StringFieldUpdateOperationsInput | string
  chunkId?: Prisma.StringFieldUpdateOperationsInput | string
  rankPosition?: Prisma.IntFieldUpdateOperationsInput | number
  similarity?: Prisma.FloatFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MessageSourceUncheckedUpdateManyWithoutDocumentInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  messageId?: Prisma.StringFieldUpdateOperationsInput | string
  chunkId?: Prisma.StringFieldUpdateOperationsInput | string
  rankPosition?: Prisma.IntFieldUpdateOperationsInput | number
  similarity?: Prisma.FloatFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MessageSourceCreateManyChunkInput = {
  id?: string
  messageId: string
  documentId: string
  rankPosition: number
  similarity: number
  createdAt?: Date | string
}

export type MessageSourceUpdateWithoutChunkInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  rankPosition?: Prisma.IntFieldUpdateOperationsInput | number
  similarity?: Prisma.FloatFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  message?: Prisma.MessageUpdateOneRequiredWithoutSourcesNestedInput
  document?: Prisma.DocumentUpdateOneRequiredWithoutMessageSourcesNestedInput
}

export type MessageSourceUncheckedUpdateWithoutChunkInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  messageId?: Prisma.StringFieldUpdateOperationsInput | string
  documentId?: Prisma.StringFieldUpdateOperationsInput | string
  rankPosition?: Prisma.IntFieldUpdateOperationsInput | number
  similarity?: Prisma.FloatFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MessageSourceUncheckedUpdateManyWithoutChunkInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  messageId?: Prisma.StringFieldUpdateOperationsInput | string
  documentId?: Prisma.StringFieldUpdateOperationsInput | string
  rankPosition?: Prisma.IntFieldUpdateOperationsInput | number
  similarity?: Prisma.FloatFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type MessageSourceSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  messageId?: boolean
  documentId?: boolean
  chunkId?: boolean
  rankPosition?: boolean
  similarity?: boolean
  createdAt?: boolean
  message?: boolean | Prisma.MessageDefaultArgs<ExtArgs>
  document?: boolean | Prisma.DocumentDefaultArgs<ExtArgs>
  chunk?: boolean | Prisma.DocumentChunkDefaultArgs<ExtArgs>
}, ExtArgs["result"]["messageSource"]>

export type MessageSourceSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  messageId?: boolean
  documentId?: boolean
  chunkId?: boolean
  rankPosition?: boolean
  similarity?: boolean
  createdAt?: boolean
  message?: boolean | Prisma.MessageDefaultArgs<ExtArgs>
  document?: boolean | Prisma.DocumentDefaultArgs<ExtArgs>
  chunk?: boolean | Prisma.DocumentChunkDefaultArgs<ExtArgs>
}, ExtArgs["result"]["messageSource"]>

export type MessageSourceSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  messageId?: boolean
  documentId?: boolean
  chunkId?: boolean
  rankPosition?: boolean
  similarity?: boolean
  createdAt?: boolean
  message?: boolean | Prisma.MessageDefaultArgs<ExtArgs>
  document?: boolean | Prisma.DocumentDefaultArgs<ExtArgs>
  chunk?: boolean | Prisma.DocumentChunkDefaultArgs<ExtArgs>
}, ExtArgs["result"]["messageSource"]>

export type MessageSourceSelectScalar = {
  id?: boolean
  messageId?: boolean
  documentId?: boolean
  chunkId?: boolean
  rankPosition?: boolean
  similarity?: boolean
  createdAt?: boolean
}

export type MessageSourceOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "messageId" | "documentId" | "chunkId" | "rankPosition" | "similarity" | "createdAt", ExtArgs["result"]["messageSource"]>
export type MessageSourceInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  message?: boolean | Prisma.MessageDefaultArgs<ExtArgs>
  document?: boolean | Prisma.DocumentDefaultArgs<ExtArgs>
  chunk?: boolean | Prisma.DocumentChunkDefaultArgs<ExtArgs>
}
export type MessageSourceIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  message?: boolean | Prisma.MessageDefaultArgs<ExtArgs>
  document?: boolean | Prisma.DocumentDefaultArgs<ExtArgs>
  chunk?: boolean | Prisma.DocumentChunkDefaultArgs<ExtArgs>
}
export type MessageSourceIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  message?: boolean | Prisma.MessageDefaultArgs<ExtArgs>
  document?: boolean | Prisma.DocumentDefaultArgs<ExtArgs>
  chunk?: boolean | Prisma.DocumentChunkDefaultArgs<ExtArgs>
}

export type $MessageSourcePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "MessageSource"
  objects: {
    message: Prisma.$MessagePayload<ExtArgs>
    document: Prisma.$DocumentPayload<ExtArgs>
    chunk: Prisma.$DocumentChunkPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    messageId: string
    documentId: string
    chunkId: string
    rankPosition: number
    similarity: number
    createdAt: Date
  }, ExtArgs["result"]["messageSource"]>
  composites: {}
}

export type MessageSourceGetPayload<S extends boolean | null | undefined | MessageSourceDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$MessageSourcePayload, S>

export type MessageSourceCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<MessageSourceFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: MessageSourceCountAggregateInputType | true
  }

export interface MessageSourceDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['MessageSource'], meta: { name: 'MessageSource' } }
  /**
   * Find zero or one MessageSource that matches the filter.
   * @param {MessageSourceFindUniqueArgs} args - Arguments to find a MessageSource
   * @example
   * // Get one MessageSource
   * const messageSource = await prisma.messageSource.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends MessageSourceFindUniqueArgs>(args: Prisma.SelectSubset<T, MessageSourceFindUniqueArgs<ExtArgs>>): Prisma.Prisma__MessageSourceClient<runtime.Types.Result.GetResult<Prisma.$MessageSourcePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one MessageSource that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {MessageSourceFindUniqueOrThrowArgs} args - Arguments to find a MessageSource
   * @example
   * // Get one MessageSource
   * const messageSource = await prisma.messageSource.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends MessageSourceFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, MessageSourceFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__MessageSourceClient<runtime.Types.Result.GetResult<Prisma.$MessageSourcePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first MessageSource that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MessageSourceFindFirstArgs} args - Arguments to find a MessageSource
   * @example
   * // Get one MessageSource
   * const messageSource = await prisma.messageSource.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends MessageSourceFindFirstArgs>(args?: Prisma.SelectSubset<T, MessageSourceFindFirstArgs<ExtArgs>>): Prisma.Prisma__MessageSourceClient<runtime.Types.Result.GetResult<Prisma.$MessageSourcePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first MessageSource that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MessageSourceFindFirstOrThrowArgs} args - Arguments to find a MessageSource
   * @example
   * // Get one MessageSource
   * const messageSource = await prisma.messageSource.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends MessageSourceFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, MessageSourceFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__MessageSourceClient<runtime.Types.Result.GetResult<Prisma.$MessageSourcePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more MessageSources that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MessageSourceFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all MessageSources
   * const messageSources = await prisma.messageSource.findMany()
   * 
   * // Get first 10 MessageSources
   * const messageSources = await prisma.messageSource.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const messageSourceWithIdOnly = await prisma.messageSource.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends MessageSourceFindManyArgs>(args?: Prisma.SelectSubset<T, MessageSourceFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MessageSourcePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a MessageSource.
   * @param {MessageSourceCreateArgs} args - Arguments to create a MessageSource.
   * @example
   * // Create one MessageSource
   * const MessageSource = await prisma.messageSource.create({
   *   data: {
   *     // ... data to create a MessageSource
   *   }
   * })
   * 
   */
  create<T extends MessageSourceCreateArgs>(args: Prisma.SelectSubset<T, MessageSourceCreateArgs<ExtArgs>>): Prisma.Prisma__MessageSourceClient<runtime.Types.Result.GetResult<Prisma.$MessageSourcePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many MessageSources.
   * @param {MessageSourceCreateManyArgs} args - Arguments to create many MessageSources.
   * @example
   * // Create many MessageSources
   * const messageSource = await prisma.messageSource.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends MessageSourceCreateManyArgs>(args?: Prisma.SelectSubset<T, MessageSourceCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many MessageSources and returns the data saved in the database.
   * @param {MessageSourceCreateManyAndReturnArgs} args - Arguments to create many MessageSources.
   * @example
   * // Create many MessageSources
   * const messageSource = await prisma.messageSource.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many MessageSources and only return the `id`
   * const messageSourceWithIdOnly = await prisma.messageSource.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends MessageSourceCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, MessageSourceCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MessageSourcePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a MessageSource.
   * @param {MessageSourceDeleteArgs} args - Arguments to delete one MessageSource.
   * @example
   * // Delete one MessageSource
   * const MessageSource = await prisma.messageSource.delete({
   *   where: {
   *     // ... filter to delete one MessageSource
   *   }
   * })
   * 
   */
  delete<T extends MessageSourceDeleteArgs>(args: Prisma.SelectSubset<T, MessageSourceDeleteArgs<ExtArgs>>): Prisma.Prisma__MessageSourceClient<runtime.Types.Result.GetResult<Prisma.$MessageSourcePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one MessageSource.
   * @param {MessageSourceUpdateArgs} args - Arguments to update one MessageSource.
   * @example
   * // Update one MessageSource
   * const messageSource = await prisma.messageSource.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends MessageSourceUpdateArgs>(args: Prisma.SelectSubset<T, MessageSourceUpdateArgs<ExtArgs>>): Prisma.Prisma__MessageSourceClient<runtime.Types.Result.GetResult<Prisma.$MessageSourcePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more MessageSources.
   * @param {MessageSourceDeleteManyArgs} args - Arguments to filter MessageSources to delete.
   * @example
   * // Delete a few MessageSources
   * const { count } = await prisma.messageSource.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends MessageSourceDeleteManyArgs>(args?: Prisma.SelectSubset<T, MessageSourceDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more MessageSources.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MessageSourceUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many MessageSources
   * const messageSource = await prisma.messageSource.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends MessageSourceUpdateManyArgs>(args: Prisma.SelectSubset<T, MessageSourceUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more MessageSources and returns the data updated in the database.
   * @param {MessageSourceUpdateManyAndReturnArgs} args - Arguments to update many MessageSources.
   * @example
   * // Update many MessageSources
   * const messageSource = await prisma.messageSource.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more MessageSources and only return the `id`
   * const messageSourceWithIdOnly = await prisma.messageSource.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends MessageSourceUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, MessageSourceUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MessageSourcePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one MessageSource.
   * @param {MessageSourceUpsertArgs} args - Arguments to update or create a MessageSource.
   * @example
   * // Update or create a MessageSource
   * const messageSource = await prisma.messageSource.upsert({
   *   create: {
   *     // ... data to create a MessageSource
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the MessageSource we want to update
   *   }
   * })
   */
  upsert<T extends MessageSourceUpsertArgs>(args: Prisma.SelectSubset<T, MessageSourceUpsertArgs<ExtArgs>>): Prisma.Prisma__MessageSourceClient<runtime.Types.Result.GetResult<Prisma.$MessageSourcePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of MessageSources.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MessageSourceCountArgs} args - Arguments to filter MessageSources to count.
   * @example
   * // Count the number of MessageSources
   * const count = await prisma.messageSource.count({
   *   where: {
   *     // ... the filter for the MessageSources we want to count
   *   }
   * })
  **/
  count<T extends MessageSourceCountArgs>(
    args?: Prisma.Subset<T, MessageSourceCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], MessageSourceCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a MessageSource.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MessageSourceAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends MessageSourceAggregateArgs>(args: Prisma.Subset<T, MessageSourceAggregateArgs>): Prisma.PrismaPromise<GetMessageSourceAggregateType<T>>

  /**
   * Group by MessageSource.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MessageSourceGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends MessageSourceGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: MessageSourceGroupByArgs['orderBy'] }
      : { orderBy?: MessageSourceGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, MessageSourceGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetMessageSourceGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the MessageSource model
 */
readonly fields: MessageSourceFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for MessageSource.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__MessageSourceClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  message<T extends Prisma.MessageDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.MessageDefaultArgs<ExtArgs>>): Prisma.Prisma__MessageClient<runtime.Types.Result.GetResult<Prisma.$MessagePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  document<T extends Prisma.DocumentDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.DocumentDefaultArgs<ExtArgs>>): Prisma.Prisma__DocumentClient<runtime.Types.Result.GetResult<Prisma.$DocumentPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  chunk<T extends Prisma.DocumentChunkDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.DocumentChunkDefaultArgs<ExtArgs>>): Prisma.Prisma__DocumentChunkClient<runtime.Types.Result.GetResult<Prisma.$DocumentChunkPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the MessageSource model
 */
export interface MessageSourceFieldRefs {
  readonly id: Prisma.FieldRef<"MessageSource", 'String'>
  readonly messageId: Prisma.FieldRef<"MessageSource", 'String'>
  readonly documentId: Prisma.FieldRef<"MessageSource", 'String'>
  readonly chunkId: Prisma.FieldRef<"MessageSource", 'String'>
  readonly rankPosition: Prisma.FieldRef<"MessageSource", 'Int'>
  readonly similarity: Prisma.FieldRef<"MessageSource", 'Float'>
  readonly createdAt: Prisma.FieldRef<"MessageSource", 'DateTime'>
}
    

// Custom InputTypes
/**
 * MessageSource findUnique
 */
export type MessageSourceFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MessageSource
   */
  select?: Prisma.MessageSourceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MessageSource
   */
  omit?: Prisma.MessageSourceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MessageSourceInclude<ExtArgs> | null
  /**
   * Filter, which MessageSource to fetch.
   */
  where: Prisma.MessageSourceWhereUniqueInput
}

/**
 * MessageSource findUniqueOrThrow
 */
export type MessageSourceFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MessageSource
   */
  select?: Prisma.MessageSourceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MessageSource
   */
  omit?: Prisma.MessageSourceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MessageSourceInclude<ExtArgs> | null
  /**
   * Filter, which MessageSource to fetch.
   */
  where: Prisma.MessageSourceWhereUniqueInput
}

/**
 * MessageSource findFirst
 */
export type MessageSourceFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MessageSource
   */
  select?: Prisma.MessageSourceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MessageSource
   */
  omit?: Prisma.MessageSourceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MessageSourceInclude<ExtArgs> | null
  /**
   * Filter, which MessageSource to fetch.
   */
  where?: Prisma.MessageSourceWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MessageSources to fetch.
   */
  orderBy?: Prisma.MessageSourceOrderByWithRelationInput | Prisma.MessageSourceOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for MessageSources.
   */
  cursor?: Prisma.MessageSourceWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MessageSources from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MessageSources.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of MessageSources.
   */
  distinct?: Prisma.MessageSourceScalarFieldEnum | Prisma.MessageSourceScalarFieldEnum[]
}

/**
 * MessageSource findFirstOrThrow
 */
export type MessageSourceFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MessageSource
   */
  select?: Prisma.MessageSourceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MessageSource
   */
  omit?: Prisma.MessageSourceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MessageSourceInclude<ExtArgs> | null
  /**
   * Filter, which MessageSource to fetch.
   */
  where?: Prisma.MessageSourceWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MessageSources to fetch.
   */
  orderBy?: Prisma.MessageSourceOrderByWithRelationInput | Prisma.MessageSourceOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for MessageSources.
   */
  cursor?: Prisma.MessageSourceWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MessageSources from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MessageSources.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of MessageSources.
   */
  distinct?: Prisma.MessageSourceScalarFieldEnum | Prisma.MessageSourceScalarFieldEnum[]
}

/**
 * MessageSource findMany
 */
export type MessageSourceFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MessageSource
   */
  select?: Prisma.MessageSourceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MessageSource
   */
  omit?: Prisma.MessageSourceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MessageSourceInclude<ExtArgs> | null
  /**
   * Filter, which MessageSources to fetch.
   */
  where?: Prisma.MessageSourceWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MessageSources to fetch.
   */
  orderBy?: Prisma.MessageSourceOrderByWithRelationInput | Prisma.MessageSourceOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing MessageSources.
   */
  cursor?: Prisma.MessageSourceWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MessageSources from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MessageSources.
   */
  skip?: number
  distinct?: Prisma.MessageSourceScalarFieldEnum | Prisma.MessageSourceScalarFieldEnum[]
}

/**
 * MessageSource create
 */
export type MessageSourceCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MessageSource
   */
  select?: Prisma.MessageSourceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MessageSource
   */
  omit?: Prisma.MessageSourceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MessageSourceInclude<ExtArgs> | null
  /**
   * The data needed to create a MessageSource.
   */
  data: Prisma.XOR<Prisma.MessageSourceCreateInput, Prisma.MessageSourceUncheckedCreateInput>
}

/**
 * MessageSource createMany
 */
export type MessageSourceCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many MessageSources.
   */
  data: Prisma.MessageSourceCreateManyInput | Prisma.MessageSourceCreateManyInput[]
}

/**
 * MessageSource createManyAndReturn
 */
export type MessageSourceCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MessageSource
   */
  select?: Prisma.MessageSourceSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the MessageSource
   */
  omit?: Prisma.MessageSourceOmit<ExtArgs> | null
  /**
   * The data used to create many MessageSources.
   */
  data: Prisma.MessageSourceCreateManyInput | Prisma.MessageSourceCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MessageSourceIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * MessageSource update
 */
export type MessageSourceUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MessageSource
   */
  select?: Prisma.MessageSourceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MessageSource
   */
  omit?: Prisma.MessageSourceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MessageSourceInclude<ExtArgs> | null
  /**
   * The data needed to update a MessageSource.
   */
  data: Prisma.XOR<Prisma.MessageSourceUpdateInput, Prisma.MessageSourceUncheckedUpdateInput>
  /**
   * Choose, which MessageSource to update.
   */
  where: Prisma.MessageSourceWhereUniqueInput
}

/**
 * MessageSource updateMany
 */
export type MessageSourceUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update MessageSources.
   */
  data: Prisma.XOR<Prisma.MessageSourceUpdateManyMutationInput, Prisma.MessageSourceUncheckedUpdateManyInput>
  /**
   * Filter which MessageSources to update
   */
  where?: Prisma.MessageSourceWhereInput
  /**
   * Limit how many MessageSources to update.
   */
  limit?: number
}

/**
 * MessageSource updateManyAndReturn
 */
export type MessageSourceUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MessageSource
   */
  select?: Prisma.MessageSourceSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the MessageSource
   */
  omit?: Prisma.MessageSourceOmit<ExtArgs> | null
  /**
   * The data used to update MessageSources.
   */
  data: Prisma.XOR<Prisma.MessageSourceUpdateManyMutationInput, Prisma.MessageSourceUncheckedUpdateManyInput>
  /**
   * Filter which MessageSources to update
   */
  where?: Prisma.MessageSourceWhereInput
  /**
   * Limit how many MessageSources to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MessageSourceIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * MessageSource upsert
 */
export type MessageSourceUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MessageSource
   */
  select?: Prisma.MessageSourceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MessageSource
   */
  omit?: Prisma.MessageSourceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MessageSourceInclude<ExtArgs> | null
  /**
   * The filter to search for the MessageSource to update in case it exists.
   */
  where: Prisma.MessageSourceWhereUniqueInput
  /**
   * In case the MessageSource found by the `where` argument doesn't exist, create a new MessageSource with this data.
   */
  create: Prisma.XOR<Prisma.MessageSourceCreateInput, Prisma.MessageSourceUncheckedCreateInput>
  /**
   * In case the MessageSource was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.MessageSourceUpdateInput, Prisma.MessageSourceUncheckedUpdateInput>
}

/**
 * MessageSource delete
 */
export type MessageSourceDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MessageSource
   */
  select?: Prisma.MessageSourceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MessageSource
   */
  omit?: Prisma.MessageSourceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MessageSourceInclude<ExtArgs> | null
  /**
   * Filter which MessageSource to delete.
   */
  where: Prisma.MessageSourceWhereUniqueInput
}

/**
 * MessageSource deleteMany
 */
export type MessageSourceDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which MessageSources to delete
   */
  where?: Prisma.MessageSourceWhereInput
  /**
   * Limit how many MessageSources to delete.
   */
  limit?: number
}

/**
 * MessageSource without action
 */
export type MessageSourceDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MessageSource
   */
  select?: Prisma.MessageSourceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MessageSource
   */
  omit?: Prisma.MessageSourceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MessageSourceInclude<ExtArgs> | null
}
