
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ToolConfiguration` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model ToolConfiguration
 * 
 */
export type ToolConfigurationModel = runtime.Types.Result.DefaultSelection<Prisma.$ToolConfigurationPayload>

export type AggregateToolConfiguration = {
  _count: ToolConfigurationCountAggregateOutputType | null
  _min: ToolConfigurationMinAggregateOutputType | null
  _max: ToolConfigurationMaxAggregateOutputType | null
}

export type ToolConfigurationMinAggregateOutputType = {
  id: string | null
  globalEnabled: boolean | null
  toolSettings: string | null
  loggingConfig: string | null
  securityConfig: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type ToolConfigurationMaxAggregateOutputType = {
  id: string | null
  globalEnabled: boolean | null
  toolSettings: string | null
  loggingConfig: string | null
  securityConfig: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type ToolConfigurationCountAggregateOutputType = {
  id: number
  globalEnabled: number
  toolSettings: number
  loggingConfig: number
  securityConfig: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type ToolConfigurationMinAggregateInputType = {
  id?: true
  globalEnabled?: true
  toolSettings?: true
  loggingConfig?: true
  securityConfig?: true
  createdAt?: true
  updatedAt?: true
}

export type ToolConfigurationMaxAggregateInputType = {
  id?: true
  globalEnabled?: true
  toolSettings?: true
  loggingConfig?: true
  securityConfig?: true
  createdAt?: true
  updatedAt?: true
}

export type ToolConfigurationCountAggregateInputType = {
  id?: true
  globalEnabled?: true
  toolSettings?: true
  loggingConfig?: true
  securityConfig?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type ToolConfigurationAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ToolConfiguration to aggregate.
   */
  where?: Prisma.ToolConfigurationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ToolConfigurations to fetch.
   */
  orderBy?: Prisma.ToolConfigurationOrderByWithRelationInput | Prisma.ToolConfigurationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ToolConfigurationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ToolConfigurations from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ToolConfigurations.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ToolConfigurations
  **/
  _count?: true | ToolConfigurationCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ToolConfigurationMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ToolConfigurationMaxAggregateInputType
}

export type GetToolConfigurationAggregateType<T extends ToolConfigurationAggregateArgs> = {
      [P in keyof T & keyof AggregateToolConfiguration]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateToolConfiguration[P]>
    : Prisma.GetScalarType<T[P], AggregateToolConfiguration[P]>
}




export type ToolConfigurationGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ToolConfigurationWhereInput
  orderBy?: Prisma.ToolConfigurationOrderByWithAggregationInput | Prisma.ToolConfigurationOrderByWithAggregationInput[]
  by: Prisma.ToolConfigurationScalarFieldEnum[] | Prisma.ToolConfigurationScalarFieldEnum
  having?: Prisma.ToolConfigurationScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ToolConfigurationCountAggregateInputType | true
  _min?: ToolConfigurationMinAggregateInputType
  _max?: ToolConfigurationMaxAggregateInputType
}

export type ToolConfigurationGroupByOutputType = {
  id: string
  globalEnabled: boolean
  toolSettings: string
  loggingConfig: string
  securityConfig: string
  createdAt: Date
  updatedAt: Date
  _count: ToolConfigurationCountAggregateOutputType | null
  _min: ToolConfigurationMinAggregateOutputType | null
  _max: ToolConfigurationMaxAggregateOutputType | null
}

type GetToolConfigurationGroupByPayload<T extends ToolConfigurationGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ToolConfigurationGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ToolConfigurationGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ToolConfigurationGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ToolConfigurationGroupByOutputType[P]>
      }
    >
  >



export type ToolConfigurationWhereInput = {
  AND?: Prisma.ToolConfigurationWhereInput | Prisma.ToolConfigurationWhereInput[]
  OR?: Prisma.ToolConfigurationWhereInput[]
  NOT?: Prisma.ToolConfigurationWhereInput | Prisma.ToolConfigurationWhereInput[]
  id?: Prisma.StringFilter<"ToolConfiguration"> | string
  globalEnabled?: Prisma.BoolFilter<"ToolConfiguration"> | boolean
  toolSettings?: Prisma.StringFilter<"ToolConfiguration"> | string
  loggingConfig?: Prisma.StringFilter<"ToolConfiguration"> | string
  securityConfig?: Prisma.StringFilter<"ToolConfiguration"> | string
  createdAt?: Prisma.DateTimeFilter<"ToolConfiguration"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"ToolConfiguration"> | Date | string
}

export type ToolConfigurationOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  globalEnabled?: Prisma.SortOrder
  toolSettings?: Prisma.SortOrder
  loggingConfig?: Prisma.SortOrder
  securityConfig?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ToolConfigurationWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.ToolConfigurationWhereInput | Prisma.ToolConfigurationWhereInput[]
  OR?: Prisma.ToolConfigurationWhereInput[]
  NOT?: Prisma.ToolConfigurationWhereInput | Prisma.ToolConfigurationWhereInput[]
  globalEnabled?: Prisma.BoolFilter<"ToolConfiguration"> | boolean
  toolSettings?: Prisma.StringFilter<"ToolConfiguration"> | string
  loggingConfig?: Prisma.StringFilter<"ToolConfiguration"> | string
  securityConfig?: Prisma.StringFilter<"ToolConfiguration"> | string
  createdAt?: Prisma.DateTimeFilter<"ToolConfiguration"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"ToolConfiguration"> | Date | string
}, "id">

export type ToolConfigurationOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  globalEnabled?: Prisma.SortOrder
  toolSettings?: Prisma.SortOrder
  loggingConfig?: Prisma.SortOrder
  securityConfig?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.ToolConfigurationCountOrderByAggregateInput
  _max?: Prisma.ToolConfigurationMaxOrderByAggregateInput
  _min?: Prisma.ToolConfigurationMinOrderByAggregateInput
}

export type ToolConfigurationScalarWhereWithAggregatesInput = {
  AND?: Prisma.ToolConfigurationScalarWhereWithAggregatesInput | Prisma.ToolConfigurationScalarWhereWithAggregatesInput[]
  OR?: Prisma.ToolConfigurationScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ToolConfigurationScalarWhereWithAggregatesInput | Prisma.ToolConfigurationScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"ToolConfiguration"> | string
  globalEnabled?: Prisma.BoolWithAggregatesFilter<"ToolConfiguration"> | boolean
  toolSettings?: Prisma.StringWithAggregatesFilter<"ToolConfiguration"> | string
  loggingConfig?: Prisma.StringWithAggregatesFilter<"ToolConfiguration"> | string
  securityConfig?: Prisma.StringWithAggregatesFilter<"ToolConfiguration"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"ToolConfiguration"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"ToolConfiguration"> | Date | string
}

export type ToolConfigurationCreateInput = {
  id?: string
  globalEnabled?: boolean
  toolSettings: string
  loggingConfig: string
  securityConfig: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ToolConfigurationUncheckedCreateInput = {
  id?: string
  globalEnabled?: boolean
  toolSettings: string
  loggingConfig: string
  securityConfig: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ToolConfigurationUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  globalEnabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  toolSettings?: Prisma.StringFieldUpdateOperationsInput | string
  loggingConfig?: Prisma.StringFieldUpdateOperationsInput | string
  securityConfig?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ToolConfigurationUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  globalEnabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  toolSettings?: Prisma.StringFieldUpdateOperationsInput | string
  loggingConfig?: Prisma.StringFieldUpdateOperationsInput | string
  securityConfig?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ToolConfigurationCreateManyInput = {
  id?: string
  globalEnabled?: boolean
  toolSettings: string
  loggingConfig: string
  securityConfig: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ToolConfigurationUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  globalEnabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  toolSettings?: Prisma.StringFieldUpdateOperationsInput | string
  loggingConfig?: Prisma.StringFieldUpdateOperationsInput | string
  securityConfig?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ToolConfigurationUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  globalEnabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  toolSettings?: Prisma.StringFieldUpdateOperationsInput | string
  loggingConfig?: Prisma.StringFieldUpdateOperationsInput | string
  securityConfig?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ToolConfigurationCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  globalEnabled?: Prisma.SortOrder
  toolSettings?: Prisma.SortOrder
  loggingConfig?: Prisma.SortOrder
  securityConfig?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ToolConfigurationMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  globalEnabled?: Prisma.SortOrder
  toolSettings?: Prisma.SortOrder
  loggingConfig?: Prisma.SortOrder
  securityConfig?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ToolConfigurationMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  globalEnabled?: Prisma.SortOrder
  toolSettings?: Prisma.SortOrder
  loggingConfig?: Prisma.SortOrder
  securityConfig?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}



export type ToolConfigurationSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  globalEnabled?: boolean
  toolSettings?: boolean
  loggingConfig?: boolean
  securityConfig?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["toolConfiguration"]>

export type ToolConfigurationSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  globalEnabled?: boolean
  toolSettings?: boolean
  loggingConfig?: boolean
  securityConfig?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["toolConfiguration"]>

export type ToolConfigurationSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  globalEnabled?: boolean
  toolSettings?: boolean
  loggingConfig?: boolean
  securityConfig?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["toolConfiguration"]>

export type ToolConfigurationSelectScalar = {
  id?: boolean
  globalEnabled?: boolean
  toolSettings?: boolean
  loggingConfig?: boolean
  securityConfig?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type ToolConfigurationOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "globalEnabled" | "toolSettings" | "loggingConfig" | "securityConfig" | "createdAt" | "updatedAt", ExtArgs["result"]["toolConfiguration"]>

export type $ToolConfigurationPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ToolConfiguration"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    globalEnabled: boolean
    toolSettings: string
    loggingConfig: string
    securityConfig: string
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["toolConfiguration"]>
  composites: {}
}

export type ToolConfigurationGetPayload<S extends boolean | null | undefined | ToolConfigurationDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ToolConfigurationPayload, S>

export type ToolConfigurationCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ToolConfigurationFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ToolConfigurationCountAggregateInputType | true
  }

export interface ToolConfigurationDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ToolConfiguration'], meta: { name: 'ToolConfiguration' } }
  /**
   * Find zero or one ToolConfiguration that matches the filter.
   * @param {ToolConfigurationFindUniqueArgs} args - Arguments to find a ToolConfiguration
   * @example
   * // Get one ToolConfiguration
   * const toolConfiguration = await prisma.toolConfiguration.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ToolConfigurationFindUniqueArgs>(args: Prisma.SelectSubset<T, ToolConfigurationFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ToolConfigurationClient<runtime.Types.Result.GetResult<Prisma.$ToolConfigurationPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ToolConfiguration that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ToolConfigurationFindUniqueOrThrowArgs} args - Arguments to find a ToolConfiguration
   * @example
   * // Get one ToolConfiguration
   * const toolConfiguration = await prisma.toolConfiguration.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ToolConfigurationFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ToolConfigurationFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ToolConfigurationClient<runtime.Types.Result.GetResult<Prisma.$ToolConfigurationPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ToolConfiguration that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ToolConfigurationFindFirstArgs} args - Arguments to find a ToolConfiguration
   * @example
   * // Get one ToolConfiguration
   * const toolConfiguration = await prisma.toolConfiguration.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ToolConfigurationFindFirstArgs>(args?: Prisma.SelectSubset<T, ToolConfigurationFindFirstArgs<ExtArgs>>): Prisma.Prisma__ToolConfigurationClient<runtime.Types.Result.GetResult<Prisma.$ToolConfigurationPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ToolConfiguration that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ToolConfigurationFindFirstOrThrowArgs} args - Arguments to find a ToolConfiguration
   * @example
   * // Get one ToolConfiguration
   * const toolConfiguration = await prisma.toolConfiguration.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ToolConfigurationFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ToolConfigurationFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ToolConfigurationClient<runtime.Types.Result.GetResult<Prisma.$ToolConfigurationPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ToolConfigurations that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ToolConfigurationFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ToolConfigurations
   * const toolConfigurations = await prisma.toolConfiguration.findMany()
   * 
   * // Get first 10 ToolConfigurations
   * const toolConfigurations = await prisma.toolConfiguration.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const toolConfigurationWithIdOnly = await prisma.toolConfiguration.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ToolConfigurationFindManyArgs>(args?: Prisma.SelectSubset<T, ToolConfigurationFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ToolConfigurationPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ToolConfiguration.
   * @param {ToolConfigurationCreateArgs} args - Arguments to create a ToolConfiguration.
   * @example
   * // Create one ToolConfiguration
   * const ToolConfiguration = await prisma.toolConfiguration.create({
   *   data: {
   *     // ... data to create a ToolConfiguration
   *   }
   * })
   * 
   */
  create<T extends ToolConfigurationCreateArgs>(args: Prisma.SelectSubset<T, ToolConfigurationCreateArgs<ExtArgs>>): Prisma.Prisma__ToolConfigurationClient<runtime.Types.Result.GetResult<Prisma.$ToolConfigurationPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ToolConfigurations.
   * @param {ToolConfigurationCreateManyArgs} args - Arguments to create many ToolConfigurations.
   * @example
   * // Create many ToolConfigurations
   * const toolConfiguration = await prisma.toolConfiguration.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ToolConfigurationCreateManyArgs>(args?: Prisma.SelectSubset<T, ToolConfigurationCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many ToolConfigurations and returns the data saved in the database.
   * @param {ToolConfigurationCreateManyAndReturnArgs} args - Arguments to create many ToolConfigurations.
   * @example
   * // Create many ToolConfigurations
   * const toolConfiguration = await prisma.toolConfiguration.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many ToolConfigurations and only return the `id`
   * const toolConfigurationWithIdOnly = await prisma.toolConfiguration.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ToolConfigurationCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ToolConfigurationCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ToolConfigurationPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a ToolConfiguration.
   * @param {ToolConfigurationDeleteArgs} args - Arguments to delete one ToolConfiguration.
   * @example
   * // Delete one ToolConfiguration
   * const ToolConfiguration = await prisma.toolConfiguration.delete({
   *   where: {
   *     // ... filter to delete one ToolConfiguration
   *   }
   * })
   * 
   */
  delete<T extends ToolConfigurationDeleteArgs>(args: Prisma.SelectSubset<T, ToolConfigurationDeleteArgs<ExtArgs>>): Prisma.Prisma__ToolConfigurationClient<runtime.Types.Result.GetResult<Prisma.$ToolConfigurationPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ToolConfiguration.
   * @param {ToolConfigurationUpdateArgs} args - Arguments to update one ToolConfiguration.
   * @example
   * // Update one ToolConfiguration
   * const toolConfiguration = await prisma.toolConfiguration.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ToolConfigurationUpdateArgs>(args: Prisma.SelectSubset<T, ToolConfigurationUpdateArgs<ExtArgs>>): Prisma.Prisma__ToolConfigurationClient<runtime.Types.Result.GetResult<Prisma.$ToolConfigurationPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ToolConfigurations.
   * @param {ToolConfigurationDeleteManyArgs} args - Arguments to filter ToolConfigurations to delete.
   * @example
   * // Delete a few ToolConfigurations
   * const { count } = await prisma.toolConfiguration.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ToolConfigurationDeleteManyArgs>(args?: Prisma.SelectSubset<T, ToolConfigurationDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ToolConfigurations.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ToolConfigurationUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ToolConfigurations
   * const toolConfiguration = await prisma.toolConfiguration.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ToolConfigurationUpdateManyArgs>(args: Prisma.SelectSubset<T, ToolConfigurationUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ToolConfigurations and returns the data updated in the database.
   * @param {ToolConfigurationUpdateManyAndReturnArgs} args - Arguments to update many ToolConfigurations.
   * @example
   * // Update many ToolConfigurations
   * const toolConfiguration = await prisma.toolConfiguration.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more ToolConfigurations and only return the `id`
   * const toolConfigurationWithIdOnly = await prisma.toolConfiguration.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ToolConfigurationUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ToolConfigurationUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ToolConfigurationPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one ToolConfiguration.
   * @param {ToolConfigurationUpsertArgs} args - Arguments to update or create a ToolConfiguration.
   * @example
   * // Update or create a ToolConfiguration
   * const toolConfiguration = await prisma.toolConfiguration.upsert({
   *   create: {
   *     // ... data to create a ToolConfiguration
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ToolConfiguration we want to update
   *   }
   * })
   */
  upsert<T extends ToolConfigurationUpsertArgs>(args: Prisma.SelectSubset<T, ToolConfigurationUpsertArgs<ExtArgs>>): Prisma.Prisma__ToolConfigurationClient<runtime.Types.Result.GetResult<Prisma.$ToolConfigurationPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ToolConfigurations.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ToolConfigurationCountArgs} args - Arguments to filter ToolConfigurations to count.
   * @example
   * // Count the number of ToolConfigurations
   * const count = await prisma.toolConfiguration.count({
   *   where: {
   *     // ... the filter for the ToolConfigurations we want to count
   *   }
   * })
  **/
  count<T extends ToolConfigurationCountArgs>(
    args?: Prisma.Subset<T, ToolConfigurationCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ToolConfigurationCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ToolConfiguration.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ToolConfigurationAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ToolConfigurationAggregateArgs>(args: Prisma.Subset<T, ToolConfigurationAggregateArgs>): Prisma.PrismaPromise<GetToolConfigurationAggregateType<T>>

  /**
   * Group by ToolConfiguration.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ToolConfigurationGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ToolConfigurationGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ToolConfigurationGroupByArgs['orderBy'] }
      : { orderBy?: ToolConfigurationGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ToolConfigurationGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetToolConfigurationGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ToolConfiguration model
 */
readonly fields: ToolConfigurationFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ToolConfiguration.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ToolConfigurationClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ToolConfiguration model
 */
export interface ToolConfigurationFieldRefs {
  readonly id: Prisma.FieldRef<"ToolConfiguration", 'String'>
  readonly globalEnabled: Prisma.FieldRef<"ToolConfiguration", 'Boolean'>
  readonly toolSettings: Prisma.FieldRef<"ToolConfiguration", 'String'>
  readonly loggingConfig: Prisma.FieldRef<"ToolConfiguration", 'String'>
  readonly securityConfig: Prisma.FieldRef<"ToolConfiguration", 'String'>
  readonly createdAt: Prisma.FieldRef<"ToolConfiguration", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"ToolConfiguration", 'DateTime'>
}
    

// Custom InputTypes
/**
 * ToolConfiguration findUnique
 */
export type ToolConfigurationFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ToolConfiguration
   */
  select?: Prisma.ToolConfigurationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ToolConfiguration
   */
  omit?: Prisma.ToolConfigurationOmit<ExtArgs> | null
  /**
   * Filter, which ToolConfiguration to fetch.
   */
  where: Prisma.ToolConfigurationWhereUniqueInput
}

/**
 * ToolConfiguration findUniqueOrThrow
 */
export type ToolConfigurationFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ToolConfiguration
   */
  select?: Prisma.ToolConfigurationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ToolConfiguration
   */
  omit?: Prisma.ToolConfigurationOmit<ExtArgs> | null
  /**
   * Filter, which ToolConfiguration to fetch.
   */
  where: Prisma.ToolConfigurationWhereUniqueInput
}

/**
 * ToolConfiguration findFirst
 */
export type ToolConfigurationFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ToolConfiguration
   */
  select?: Prisma.ToolConfigurationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ToolConfiguration
   */
  omit?: Prisma.ToolConfigurationOmit<ExtArgs> | null
  /**
   * Filter, which ToolConfiguration to fetch.
   */
  where?: Prisma.ToolConfigurationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ToolConfigurations to fetch.
   */
  orderBy?: Prisma.ToolConfigurationOrderByWithRelationInput | Prisma.ToolConfigurationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ToolConfigurations.
   */
  cursor?: Prisma.ToolConfigurationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ToolConfigurations from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ToolConfigurations.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ToolConfigurations.
   */
  distinct?: Prisma.ToolConfigurationScalarFieldEnum | Prisma.ToolConfigurationScalarFieldEnum[]
}

/**
 * ToolConfiguration findFirstOrThrow
 */
export type ToolConfigurationFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ToolConfiguration
   */
  select?: Prisma.ToolConfigurationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ToolConfiguration
   */
  omit?: Prisma.ToolConfigurationOmit<ExtArgs> | null
  /**
   * Filter, which ToolConfiguration to fetch.
   */
  where?: Prisma.ToolConfigurationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ToolConfigurations to fetch.
   */
  orderBy?: Prisma.ToolConfigurationOrderByWithRelationInput | Prisma.ToolConfigurationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ToolConfigurations.
   */
  cursor?: Prisma.ToolConfigurationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ToolConfigurations from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ToolConfigurations.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ToolConfigurations.
   */
  distinct?: Prisma.ToolConfigurationScalarFieldEnum | Prisma.ToolConfigurationScalarFieldEnum[]
}

/**
 * ToolConfiguration findMany
 */
export type ToolConfigurationFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ToolConfiguration
   */
  select?: Prisma.ToolConfigurationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ToolConfiguration
   */
  omit?: Prisma.ToolConfigurationOmit<ExtArgs> | null
  /**
   * Filter, which ToolConfigurations to fetch.
   */
  where?: Prisma.ToolConfigurationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ToolConfigurations to fetch.
   */
  orderBy?: Prisma.ToolConfigurationOrderByWithRelationInput | Prisma.ToolConfigurationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ToolConfigurations.
   */
  cursor?: Prisma.ToolConfigurationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ToolConfigurations from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ToolConfigurations.
   */
  skip?: number
  distinct?: Prisma.ToolConfigurationScalarFieldEnum | Prisma.ToolConfigurationScalarFieldEnum[]
}

/**
 * ToolConfiguration create
 */
export type ToolConfigurationCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ToolConfiguration
   */
  select?: Prisma.ToolConfigurationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ToolConfiguration
   */
  omit?: Prisma.ToolConfigurationOmit<ExtArgs> | null
  /**
   * The data needed to create a ToolConfiguration.
   */
  data: Prisma.XOR<Prisma.ToolConfigurationCreateInput, Prisma.ToolConfigurationUncheckedCreateInput>
}

/**
 * ToolConfiguration createMany
 */
export type ToolConfigurationCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ToolConfigurations.
   */
  data: Prisma.ToolConfigurationCreateManyInput | Prisma.ToolConfigurationCreateManyInput[]
}

/**
 * ToolConfiguration createManyAndReturn
 */
export type ToolConfigurationCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ToolConfiguration
   */
  select?: Prisma.ToolConfigurationSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ToolConfiguration
   */
  omit?: Prisma.ToolConfigurationOmit<ExtArgs> | null
  /**
   * The data used to create many ToolConfigurations.
   */
  data: Prisma.ToolConfigurationCreateManyInput | Prisma.ToolConfigurationCreateManyInput[]
}

/**
 * ToolConfiguration update
 */
export type ToolConfigurationUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ToolConfiguration
   */
  select?: Prisma.ToolConfigurationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ToolConfiguration
   */
  omit?: Prisma.ToolConfigurationOmit<ExtArgs> | null
  /**
   * The data needed to update a ToolConfiguration.
   */
  data: Prisma.XOR<Prisma.ToolConfigurationUpdateInput, Prisma.ToolConfigurationUncheckedUpdateInput>
  /**
   * Choose, which ToolConfiguration to update.
   */
  where: Prisma.ToolConfigurationWhereUniqueInput
}

/**
 * ToolConfiguration updateMany
 */
export type ToolConfigurationUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ToolConfigurations.
   */
  data: Prisma.XOR<Prisma.ToolConfigurationUpdateManyMutationInput, Prisma.ToolConfigurationUncheckedUpdateManyInput>
  /**
   * Filter which ToolConfigurations to update
   */
  where?: Prisma.ToolConfigurationWhereInput
  /**
   * Limit how many ToolConfigurations to update.
   */
  limit?: number
}

/**
 * ToolConfiguration updateManyAndReturn
 */
export type ToolConfigurationUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ToolConfiguration
   */
  select?: Prisma.ToolConfigurationSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ToolConfiguration
   */
  omit?: Prisma.ToolConfigurationOmit<ExtArgs> | null
  /**
   * The data used to update ToolConfigurations.
   */
  data: Prisma.XOR<Prisma.ToolConfigurationUpdateManyMutationInput, Prisma.ToolConfigurationUncheckedUpdateManyInput>
  /**
   * Filter which ToolConfigurations to update
   */
  where?: Prisma.ToolConfigurationWhereInput
  /**
   * Limit how many ToolConfigurations to update.
   */
  limit?: number
}

/**
 * ToolConfiguration upsert
 */
export type ToolConfigurationUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ToolConfiguration
   */
  select?: Prisma.ToolConfigurationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ToolConfiguration
   */
  omit?: Prisma.ToolConfigurationOmit<ExtArgs> | null
  /**
   * The filter to search for the ToolConfiguration to update in case it exists.
   */
  where: Prisma.ToolConfigurationWhereUniqueInput
  /**
   * In case the ToolConfiguration found by the `where` argument doesn't exist, create a new ToolConfiguration with this data.
   */
  create: Prisma.XOR<Prisma.ToolConfigurationCreateInput, Prisma.ToolConfigurationUncheckedCreateInput>
  /**
   * In case the ToolConfiguration was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ToolConfigurationUpdateInput, Prisma.ToolConfigurationUncheckedUpdateInput>
}

/**
 * ToolConfiguration delete
 */
export type ToolConfigurationDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ToolConfiguration
   */
  select?: Prisma.ToolConfigurationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ToolConfiguration
   */
  omit?: Prisma.ToolConfigurationOmit<ExtArgs> | null
  /**
   * Filter which ToolConfiguration to delete.
   */
  where: Prisma.ToolConfigurationWhereUniqueInput
}

/**
 * ToolConfiguration deleteMany
 */
export type ToolConfigurationDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ToolConfigurations to delete
   */
  where?: Prisma.ToolConfigurationWhereInput
  /**
   * Limit how many ToolConfigurations to delete.
   */
  limit?: number
}

/**
 * ToolConfiguration without action
 */
export type ToolConfigurationDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ToolConfiguration
   */
  select?: Prisma.ToolConfigurationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ToolConfiguration
   */
  omit?: Prisma.ToolConfigurationOmit<ExtArgs> | null
}
