
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ToolExecutionLog` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model ToolExecutionLog
 * 
 */
export type ToolExecutionLogModel = runtime.Types.Result.DefaultSelection<Prisma.$ToolExecutionLogPayload>

export type AggregateToolExecutionLog = {
  _count: ToolExecutionLogCountAggregateOutputType | null
  _avg: ToolExecutionLogAvgAggregateOutputType | null
  _sum: ToolExecutionLogSumAggregateOutputType | null
  _min: ToolExecutionLogMinAggregateOutputType | null
  _max: ToolExecutionLogMaxAggregateOutputType | null
}

export type ToolExecutionLogAvgAggregateOutputType = {
  executionTime: number | null
  resultSize: number | null
}

export type ToolExecutionLogSumAggregateOutputType = {
  executionTime: number | null
  resultSize: number | null
}

export type ToolExecutionLogMinAggregateOutputType = {
  id: string | null
  conversationId: string | null
  userId: string | null
  toolName: string | null
  toolCallId: string | null
  paramsHash: string | null
  executionTime: number | null
  resultHash: string | null
  success: boolean | null
  errorMessage: string | null
  resultSize: number | null
  cacheHit: boolean | null
  metadata: string | null
  createdAt: Date | null
}

export type ToolExecutionLogMaxAggregateOutputType = {
  id: string | null
  conversationId: string | null
  userId: string | null
  toolName: string | null
  toolCallId: string | null
  paramsHash: string | null
  executionTime: number | null
  resultHash: string | null
  success: boolean | null
  errorMessage: string | null
  resultSize: number | null
  cacheHit: boolean | null
  metadata: string | null
  createdAt: Date | null
}

export type ToolExecutionLogCountAggregateOutputType = {
  id: number
  conversationId: number
  userId: number
  toolName: number
  toolCallId: number
  paramsHash: number
  executionTime: number
  resultHash: number
  success: number
  errorMessage: number
  resultSize: number
  cacheHit: number
  metadata: number
  createdAt: number
  _all: number
}


export type ToolExecutionLogAvgAggregateInputType = {
  executionTime?: true
  resultSize?: true
}

export type ToolExecutionLogSumAggregateInputType = {
  executionTime?: true
  resultSize?: true
}

export type ToolExecutionLogMinAggregateInputType = {
  id?: true
  conversationId?: true
  userId?: true
  toolName?: true
  toolCallId?: true
  paramsHash?: true
  executionTime?: true
  resultHash?: true
  success?: true
  errorMessage?: true
  resultSize?: true
  cacheHit?: true
  metadata?: true
  createdAt?: true
}

export type ToolExecutionLogMaxAggregateInputType = {
  id?: true
  conversationId?: true
  userId?: true
  toolName?: true
  toolCallId?: true
  paramsHash?: true
  executionTime?: true
  resultHash?: true
  success?: true
  errorMessage?: true
  resultSize?: true
  cacheHit?: true
  metadata?: true
  createdAt?: true
}

export type ToolExecutionLogCountAggregateInputType = {
  id?: true
  conversationId?: true
  userId?: true
  toolName?: true
  toolCallId?: true
  paramsHash?: true
  executionTime?: true
  resultHash?: true
  success?: true
  errorMessage?: true
  resultSize?: true
  cacheHit?: true
  metadata?: true
  createdAt?: true
  _all?: true
}

export type ToolExecutionLogAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ToolExecutionLog to aggregate.
   */
  where?: Prisma.ToolExecutionLogWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ToolExecutionLogs to fetch.
   */
  orderBy?: Prisma.ToolExecutionLogOrderByWithRelationInput | Prisma.ToolExecutionLogOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ToolExecutionLogWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ToolExecutionLogs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ToolExecutionLogs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ToolExecutionLogs
  **/
  _count?: true | ToolExecutionLogCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: ToolExecutionLogAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: ToolExecutionLogSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ToolExecutionLogMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ToolExecutionLogMaxAggregateInputType
}

export type GetToolExecutionLogAggregateType<T extends ToolExecutionLogAggregateArgs> = {
      [P in keyof T & keyof AggregateToolExecutionLog]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateToolExecutionLog[P]>
    : Prisma.GetScalarType<T[P], AggregateToolExecutionLog[P]>
}




export type ToolExecutionLogGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ToolExecutionLogWhereInput
  orderBy?: Prisma.ToolExecutionLogOrderByWithAggregationInput | Prisma.ToolExecutionLogOrderByWithAggregationInput[]
  by: Prisma.ToolExecutionLogScalarFieldEnum[] | Prisma.ToolExecutionLogScalarFieldEnum
  having?: Prisma.ToolExecutionLogScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ToolExecutionLogCountAggregateInputType | true
  _avg?: ToolExecutionLogAvgAggregateInputType
  _sum?: ToolExecutionLogSumAggregateInputType
  _min?: ToolExecutionLogMinAggregateInputType
  _max?: ToolExecutionLogMaxAggregateInputType
}

export type ToolExecutionLogGroupByOutputType = {
  id: string
  conversationId: string
  userId: string
  toolName: string
  toolCallId: string
  paramsHash: string
  executionTime: number
  resultHash: string
  success: boolean
  errorMessage: string | null
  resultSize: number
  cacheHit: boolean
  metadata: string | null
  createdAt: Date
  _count: ToolExecutionLogCountAggregateOutputType | null
  _avg: ToolExecutionLogAvgAggregateOutputType | null
  _sum: ToolExecutionLogSumAggregateOutputType | null
  _min: ToolExecutionLogMinAggregateOutputType | null
  _max: ToolExecutionLogMaxAggregateOutputType | null
}

type GetToolExecutionLogGroupByPayload<T extends ToolExecutionLogGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ToolExecutionLogGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ToolExecutionLogGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ToolExecutionLogGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ToolExecutionLogGroupByOutputType[P]>
      }
    >
  >



export type ToolExecutionLogWhereInput = {
  AND?: Prisma.ToolExecutionLogWhereInput | Prisma.ToolExecutionLogWhereInput[]
  OR?: Prisma.ToolExecutionLogWhereInput[]
  NOT?: Prisma.ToolExecutionLogWhereInput | Prisma.ToolExecutionLogWhereInput[]
  id?: Prisma.StringFilter<"ToolExecutionLog"> | string
  conversationId?: Prisma.StringFilter<"ToolExecutionLog"> | string
  userId?: Prisma.StringFilter<"ToolExecutionLog"> | string
  toolName?: Prisma.StringFilter<"ToolExecutionLog"> | string
  toolCallId?: Prisma.StringFilter<"ToolExecutionLog"> | string
  paramsHash?: Prisma.StringFilter<"ToolExecutionLog"> | string
  executionTime?: Prisma.IntFilter<"ToolExecutionLog"> | number
  resultHash?: Prisma.StringFilter<"ToolExecutionLog"> | string
  success?: Prisma.BoolFilter<"ToolExecutionLog"> | boolean
  errorMessage?: Prisma.StringNullableFilter<"ToolExecutionLog"> | string | null
  resultSize?: Prisma.IntFilter<"ToolExecutionLog"> | number
  cacheHit?: Prisma.BoolFilter<"ToolExecutionLog"> | boolean
  metadata?: Prisma.StringNullableFilter<"ToolExecutionLog"> | string | null
  createdAt?: Prisma.DateTimeFilter<"ToolExecutionLog"> | Date | string
}

export type ToolExecutionLogOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  conversationId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  toolName?: Prisma.SortOrder
  toolCallId?: Prisma.SortOrder
  paramsHash?: Prisma.SortOrder
  executionTime?: Prisma.SortOrder
  resultHash?: Prisma.SortOrder
  success?: Prisma.SortOrder
  errorMessage?: Prisma.SortOrderInput | Prisma.SortOrder
  resultSize?: Prisma.SortOrder
  cacheHit?: Prisma.SortOrder
  metadata?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type ToolExecutionLogWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.ToolExecutionLogWhereInput | Prisma.ToolExecutionLogWhereInput[]
  OR?: Prisma.ToolExecutionLogWhereInput[]
  NOT?: Prisma.ToolExecutionLogWhereInput | Prisma.ToolExecutionLogWhereInput[]
  conversationId?: Prisma.StringFilter<"ToolExecutionLog"> | string
  userId?: Prisma.StringFilter<"ToolExecutionLog"> | string
  toolName?: Prisma.StringFilter<"ToolExecutionLog"> | string
  toolCallId?: Prisma.StringFilter<"ToolExecutionLog"> | string
  paramsHash?: Prisma.StringFilter<"ToolExecutionLog"> | string
  executionTime?: Prisma.IntFilter<"ToolExecutionLog"> | number
  resultHash?: Prisma.StringFilter<"ToolExecutionLog"> | string
  success?: Prisma.BoolFilter<"ToolExecutionLog"> | boolean
  errorMessage?: Prisma.StringNullableFilter<"ToolExecutionLog"> | string | null
  resultSize?: Prisma.IntFilter<"ToolExecutionLog"> | number
  cacheHit?: Prisma.BoolFilter<"ToolExecutionLog"> | boolean
  metadata?: Prisma.StringNullableFilter<"ToolExecutionLog"> | string | null
  createdAt?: Prisma.DateTimeFilter<"ToolExecutionLog"> | Date | string
}, "id">

export type ToolExecutionLogOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  conversationId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  toolName?: Prisma.SortOrder
  toolCallId?: Prisma.SortOrder
  paramsHash?: Prisma.SortOrder
  executionTime?: Prisma.SortOrder
  resultHash?: Prisma.SortOrder
  success?: Prisma.SortOrder
  errorMessage?: Prisma.SortOrderInput | Prisma.SortOrder
  resultSize?: Prisma.SortOrder
  cacheHit?: Prisma.SortOrder
  metadata?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.ToolExecutionLogCountOrderByAggregateInput
  _avg?: Prisma.ToolExecutionLogAvgOrderByAggregateInput
  _max?: Prisma.ToolExecutionLogMaxOrderByAggregateInput
  _min?: Prisma.ToolExecutionLogMinOrderByAggregateInput
  _sum?: Prisma.ToolExecutionLogSumOrderByAggregateInput
}

export type ToolExecutionLogScalarWhereWithAggregatesInput = {
  AND?: Prisma.ToolExecutionLogScalarWhereWithAggregatesInput | Prisma.ToolExecutionLogScalarWhereWithAggregatesInput[]
  OR?: Prisma.ToolExecutionLogScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ToolExecutionLogScalarWhereWithAggregatesInput | Prisma.ToolExecutionLogScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"ToolExecutionLog"> | string
  conversationId?: Prisma.StringWithAggregatesFilter<"ToolExecutionLog"> | string
  userId?: Prisma.StringWithAggregatesFilter<"ToolExecutionLog"> | string
  toolName?: Prisma.StringWithAggregatesFilter<"ToolExecutionLog"> | string
  toolCallId?: Prisma.StringWithAggregatesFilter<"ToolExecutionLog"> | string
  paramsHash?: Prisma.StringWithAggregatesFilter<"ToolExecutionLog"> | string
  executionTime?: Prisma.IntWithAggregatesFilter<"ToolExecutionLog"> | number
  resultHash?: Prisma.StringWithAggregatesFilter<"ToolExecutionLog"> | string
  success?: Prisma.BoolWithAggregatesFilter<"ToolExecutionLog"> | boolean
  errorMessage?: Prisma.StringNullableWithAggregatesFilter<"ToolExecutionLog"> | string | null
  resultSize?: Prisma.IntWithAggregatesFilter<"ToolExecutionLog"> | number
  cacheHit?: Prisma.BoolWithAggregatesFilter<"ToolExecutionLog"> | boolean
  metadata?: Prisma.StringNullableWithAggregatesFilter<"ToolExecutionLog"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"ToolExecutionLog"> | Date | string
}

export type ToolExecutionLogCreateInput = {
  id?: string
  conversationId: string
  userId: string
  toolName: string
  toolCallId: string
  paramsHash: string
  executionTime: number
  resultHash: string
  success?: boolean
  errorMessage?: string | null
  resultSize: number
  cacheHit?: boolean
  metadata?: string | null
  createdAt?: Date | string
}

export type ToolExecutionLogUncheckedCreateInput = {
  id?: string
  conversationId: string
  userId: string
  toolName: string
  toolCallId: string
  paramsHash: string
  executionTime: number
  resultHash: string
  success?: boolean
  errorMessage?: string | null
  resultSize: number
  cacheHit?: boolean
  metadata?: string | null
  createdAt?: Date | string
}

export type ToolExecutionLogUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  conversationId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  toolName?: Prisma.StringFieldUpdateOperationsInput | string
  toolCallId?: Prisma.StringFieldUpdateOperationsInput | string
  paramsHash?: Prisma.StringFieldUpdateOperationsInput | string
  executionTime?: Prisma.IntFieldUpdateOperationsInput | number
  resultHash?: Prisma.StringFieldUpdateOperationsInput | string
  success?: Prisma.BoolFieldUpdateOperationsInput | boolean
  errorMessage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  resultSize?: Prisma.IntFieldUpdateOperationsInput | number
  cacheHit?: Prisma.BoolFieldUpdateOperationsInput | boolean
  metadata?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ToolExecutionLogUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  conversationId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  toolName?: Prisma.StringFieldUpdateOperationsInput | string
  toolCallId?: Prisma.StringFieldUpdateOperationsInput | string
  paramsHash?: Prisma.StringFieldUpdateOperationsInput | string
  executionTime?: Prisma.IntFieldUpdateOperationsInput | number
  resultHash?: Prisma.StringFieldUpdateOperationsInput | string
  success?: Prisma.BoolFieldUpdateOperationsInput | boolean
  errorMessage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  resultSize?: Prisma.IntFieldUpdateOperationsInput | number
  cacheHit?: Prisma.BoolFieldUpdateOperationsInput | boolean
  metadata?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ToolExecutionLogCreateManyInput = {
  id?: string
  conversationId: string
  userId: string
  toolName: string
  toolCallId: string
  paramsHash: string
  executionTime: number
  resultHash: string
  success?: boolean
  errorMessage?: string | null
  resultSize: number
  cacheHit?: boolean
  metadata?: string | null
  createdAt?: Date | string
}

export type ToolExecutionLogUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  conversationId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  toolName?: Prisma.StringFieldUpdateOperationsInput | string
  toolCallId?: Prisma.StringFieldUpdateOperationsInput | string
  paramsHash?: Prisma.StringFieldUpdateOperationsInput | string
  executionTime?: Prisma.IntFieldUpdateOperationsInput | number
  resultHash?: Prisma.StringFieldUpdateOperationsInput | string
  success?: Prisma.BoolFieldUpdateOperationsInput | boolean
  errorMessage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  resultSize?: Prisma.IntFieldUpdateOperationsInput | number
  cacheHit?: Prisma.BoolFieldUpdateOperationsInput | boolean
  metadata?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ToolExecutionLogUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  conversationId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  toolName?: Prisma.StringFieldUpdateOperationsInput | string
  toolCallId?: Prisma.StringFieldUpdateOperationsInput | string
  paramsHash?: Prisma.StringFieldUpdateOperationsInput | string
  executionTime?: Prisma.IntFieldUpdateOperationsInput | number
  resultHash?: Prisma.StringFieldUpdateOperationsInput | string
  success?: Prisma.BoolFieldUpdateOperationsInput | boolean
  errorMessage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  resultSize?: Prisma.IntFieldUpdateOperationsInput | number
  cacheHit?: Prisma.BoolFieldUpdateOperationsInput | boolean
  metadata?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ToolExecutionLogCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  conversationId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  toolName?: Prisma.SortOrder
  toolCallId?: Prisma.SortOrder
  paramsHash?: Prisma.SortOrder
  executionTime?: Prisma.SortOrder
  resultHash?: Prisma.SortOrder
  success?: Prisma.SortOrder
  errorMessage?: Prisma.SortOrder
  resultSize?: Prisma.SortOrder
  cacheHit?: Prisma.SortOrder
  metadata?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type ToolExecutionLogAvgOrderByAggregateInput = {
  executionTime?: Prisma.SortOrder
  resultSize?: Prisma.SortOrder
}

export type ToolExecutionLogMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  conversationId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  toolName?: Prisma.SortOrder
  toolCallId?: Prisma.SortOrder
  paramsHash?: Prisma.SortOrder
  executionTime?: Prisma.SortOrder
  resultHash?: Prisma.SortOrder
  success?: Prisma.SortOrder
  errorMessage?: Prisma.SortOrder
  resultSize?: Prisma.SortOrder
  cacheHit?: Prisma.SortOrder
  metadata?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type ToolExecutionLogMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  conversationId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  toolName?: Prisma.SortOrder
  toolCallId?: Prisma.SortOrder
  paramsHash?: Prisma.SortOrder
  executionTime?: Prisma.SortOrder
  resultHash?: Prisma.SortOrder
  success?: Prisma.SortOrder
  errorMessage?: Prisma.SortOrder
  resultSize?: Prisma.SortOrder
  cacheHit?: Prisma.SortOrder
  metadata?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type ToolExecutionLogSumOrderByAggregateInput = {
  executionTime?: Prisma.SortOrder
  resultSize?: Prisma.SortOrder
}

export type BoolFieldUpdateOperationsInput = {
  set?: boolean
}



export type ToolExecutionLogSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  conversationId?: boolean
  userId?: boolean
  toolName?: boolean
  toolCallId?: boolean
  paramsHash?: boolean
  executionTime?: boolean
  resultHash?: boolean
  success?: boolean
  errorMessage?: boolean
  resultSize?: boolean
  cacheHit?: boolean
  metadata?: boolean
  createdAt?: boolean
}, ExtArgs["result"]["toolExecutionLog"]>

export type ToolExecutionLogSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  conversationId?: boolean
  userId?: boolean
  toolName?: boolean
  toolCallId?: boolean
  paramsHash?: boolean
  executionTime?: boolean
  resultHash?: boolean
  success?: boolean
  errorMessage?: boolean
  resultSize?: boolean
  cacheHit?: boolean
  metadata?: boolean
  createdAt?: boolean
}, ExtArgs["result"]["toolExecutionLog"]>

export type ToolExecutionLogSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  conversationId?: boolean
  userId?: boolean
  toolName?: boolean
  toolCallId?: boolean
  paramsHash?: boolean
  executionTime?: boolean
  resultHash?: boolean
  success?: boolean
  errorMessage?: boolean
  resultSize?: boolean
  cacheHit?: boolean
  metadata?: boolean
  createdAt?: boolean
}, ExtArgs["result"]["toolExecutionLog"]>

export type ToolExecutionLogSelectScalar = {
  id?: boolean
  conversationId?: boolean
  userId?: boolean
  toolName?: boolean
  toolCallId?: boolean
  paramsHash?: boolean
  executionTime?: boolean
  resultHash?: boolean
  success?: boolean
  errorMessage?: boolean
  resultSize?: boolean
  cacheHit?: boolean
  metadata?: boolean
  createdAt?: boolean
}

export type ToolExecutionLogOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "conversationId" | "userId" | "toolName" | "toolCallId" | "paramsHash" | "executionTime" | "resultHash" | "success" | "errorMessage" | "resultSize" | "cacheHit" | "metadata" | "createdAt", ExtArgs["result"]["toolExecutionLog"]>

export type $ToolExecutionLogPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ToolExecutionLog"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    conversationId: string
    userId: string
    toolName: string
    toolCallId: string
    paramsHash: string
    executionTime: number
    resultHash: string
    success: boolean
    errorMessage: string | null
    resultSize: number
    cacheHit: boolean
    metadata: string | null
    createdAt: Date
  }, ExtArgs["result"]["toolExecutionLog"]>
  composites: {}
}

export type ToolExecutionLogGetPayload<S extends boolean | null | undefined | ToolExecutionLogDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ToolExecutionLogPayload, S>

export type ToolExecutionLogCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ToolExecutionLogFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ToolExecutionLogCountAggregateInputType | true
  }

export interface ToolExecutionLogDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ToolExecutionLog'], meta: { name: 'ToolExecutionLog' } }
  /**
   * Find zero or one ToolExecutionLog that matches the filter.
   * @param {ToolExecutionLogFindUniqueArgs} args - Arguments to find a ToolExecutionLog
   * @example
   * // Get one ToolExecutionLog
   * const toolExecutionLog = await prisma.toolExecutionLog.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ToolExecutionLogFindUniqueArgs>(args: Prisma.SelectSubset<T, ToolExecutionLogFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ToolExecutionLogClient<runtime.Types.Result.GetResult<Prisma.$ToolExecutionLogPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ToolExecutionLog that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ToolExecutionLogFindUniqueOrThrowArgs} args - Arguments to find a ToolExecutionLog
   * @example
   * // Get one ToolExecutionLog
   * const toolExecutionLog = await prisma.toolExecutionLog.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ToolExecutionLogFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ToolExecutionLogFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ToolExecutionLogClient<runtime.Types.Result.GetResult<Prisma.$ToolExecutionLogPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ToolExecutionLog that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ToolExecutionLogFindFirstArgs} args - Arguments to find a ToolExecutionLog
   * @example
   * // Get one ToolExecutionLog
   * const toolExecutionLog = await prisma.toolExecutionLog.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ToolExecutionLogFindFirstArgs>(args?: Prisma.SelectSubset<T, ToolExecutionLogFindFirstArgs<ExtArgs>>): Prisma.Prisma__ToolExecutionLogClient<runtime.Types.Result.GetResult<Prisma.$ToolExecutionLogPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ToolExecutionLog that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ToolExecutionLogFindFirstOrThrowArgs} args - Arguments to find a ToolExecutionLog
   * @example
   * // Get one ToolExecutionLog
   * const toolExecutionLog = await prisma.toolExecutionLog.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ToolExecutionLogFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ToolExecutionLogFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ToolExecutionLogClient<runtime.Types.Result.GetResult<Prisma.$ToolExecutionLogPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ToolExecutionLogs that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ToolExecutionLogFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ToolExecutionLogs
   * const toolExecutionLogs = await prisma.toolExecutionLog.findMany()
   * 
   * // Get first 10 ToolExecutionLogs
   * const toolExecutionLogs = await prisma.toolExecutionLog.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const toolExecutionLogWithIdOnly = await prisma.toolExecutionLog.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ToolExecutionLogFindManyArgs>(args?: Prisma.SelectSubset<T, ToolExecutionLogFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ToolExecutionLogPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ToolExecutionLog.
   * @param {ToolExecutionLogCreateArgs} args - Arguments to create a ToolExecutionLog.
   * @example
   * // Create one ToolExecutionLog
   * const ToolExecutionLog = await prisma.toolExecutionLog.create({
   *   data: {
   *     // ... data to create a ToolExecutionLog
   *   }
   * })
   * 
   */
  create<T extends ToolExecutionLogCreateArgs>(args: Prisma.SelectSubset<T, ToolExecutionLogCreateArgs<ExtArgs>>): Prisma.Prisma__ToolExecutionLogClient<runtime.Types.Result.GetResult<Prisma.$ToolExecutionLogPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ToolExecutionLogs.
   * @param {ToolExecutionLogCreateManyArgs} args - Arguments to create many ToolExecutionLogs.
   * @example
   * // Create many ToolExecutionLogs
   * const toolExecutionLog = await prisma.toolExecutionLog.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ToolExecutionLogCreateManyArgs>(args?: Prisma.SelectSubset<T, ToolExecutionLogCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many ToolExecutionLogs and returns the data saved in the database.
   * @param {ToolExecutionLogCreateManyAndReturnArgs} args - Arguments to create many ToolExecutionLogs.
   * @example
   * // Create many ToolExecutionLogs
   * const toolExecutionLog = await prisma.toolExecutionLog.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many ToolExecutionLogs and only return the `id`
   * const toolExecutionLogWithIdOnly = await prisma.toolExecutionLog.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ToolExecutionLogCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ToolExecutionLogCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ToolExecutionLogPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a ToolExecutionLog.
   * @param {ToolExecutionLogDeleteArgs} args - Arguments to delete one ToolExecutionLog.
   * @example
   * // Delete one ToolExecutionLog
   * const ToolExecutionLog = await prisma.toolExecutionLog.delete({
   *   where: {
   *     // ... filter to delete one ToolExecutionLog
   *   }
   * })
   * 
   */
  delete<T extends ToolExecutionLogDeleteArgs>(args: Prisma.SelectSubset<T, ToolExecutionLogDeleteArgs<ExtArgs>>): Prisma.Prisma__ToolExecutionLogClient<runtime.Types.Result.GetResult<Prisma.$ToolExecutionLogPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ToolExecutionLog.
   * @param {ToolExecutionLogUpdateArgs} args - Arguments to update one ToolExecutionLog.
   * @example
   * // Update one ToolExecutionLog
   * const toolExecutionLog = await prisma.toolExecutionLog.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ToolExecutionLogUpdateArgs>(args: Prisma.SelectSubset<T, ToolExecutionLogUpdateArgs<ExtArgs>>): Prisma.Prisma__ToolExecutionLogClient<runtime.Types.Result.GetResult<Prisma.$ToolExecutionLogPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ToolExecutionLogs.
   * @param {ToolExecutionLogDeleteManyArgs} args - Arguments to filter ToolExecutionLogs to delete.
   * @example
   * // Delete a few ToolExecutionLogs
   * const { count } = await prisma.toolExecutionLog.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ToolExecutionLogDeleteManyArgs>(args?: Prisma.SelectSubset<T, ToolExecutionLogDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ToolExecutionLogs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ToolExecutionLogUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ToolExecutionLogs
   * const toolExecutionLog = await prisma.toolExecutionLog.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ToolExecutionLogUpdateManyArgs>(args: Prisma.SelectSubset<T, ToolExecutionLogUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ToolExecutionLogs and returns the data updated in the database.
   * @param {ToolExecutionLogUpdateManyAndReturnArgs} args - Arguments to update many ToolExecutionLogs.
   * @example
   * // Update many ToolExecutionLogs
   * const toolExecutionLog = await prisma.toolExecutionLog.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more ToolExecutionLogs and only return the `id`
   * const toolExecutionLogWithIdOnly = await prisma.toolExecutionLog.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ToolExecutionLogUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ToolExecutionLogUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ToolExecutionLogPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one ToolExecutionLog.
   * @param {ToolExecutionLogUpsertArgs} args - Arguments to update or create a ToolExecutionLog.
   * @example
   * // Update or create a ToolExecutionLog
   * const toolExecutionLog = await prisma.toolExecutionLog.upsert({
   *   create: {
   *     // ... data to create a ToolExecutionLog
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ToolExecutionLog we want to update
   *   }
   * })
   */
  upsert<T extends ToolExecutionLogUpsertArgs>(args: Prisma.SelectSubset<T, ToolExecutionLogUpsertArgs<ExtArgs>>): Prisma.Prisma__ToolExecutionLogClient<runtime.Types.Result.GetResult<Prisma.$ToolExecutionLogPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ToolExecutionLogs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ToolExecutionLogCountArgs} args - Arguments to filter ToolExecutionLogs to count.
   * @example
   * // Count the number of ToolExecutionLogs
   * const count = await prisma.toolExecutionLog.count({
   *   where: {
   *     // ... the filter for the ToolExecutionLogs we want to count
   *   }
   * })
  **/
  count<T extends ToolExecutionLogCountArgs>(
    args?: Prisma.Subset<T, ToolExecutionLogCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ToolExecutionLogCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ToolExecutionLog.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ToolExecutionLogAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ToolExecutionLogAggregateArgs>(args: Prisma.Subset<T, ToolExecutionLogAggregateArgs>): Prisma.PrismaPromise<GetToolExecutionLogAggregateType<T>>

  /**
   * Group by ToolExecutionLog.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ToolExecutionLogGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ToolExecutionLogGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ToolExecutionLogGroupByArgs['orderBy'] }
      : { orderBy?: ToolExecutionLogGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ToolExecutionLogGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetToolExecutionLogGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ToolExecutionLog model
 */
readonly fields: ToolExecutionLogFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ToolExecutionLog.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ToolExecutionLogClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ToolExecutionLog model
 */
export interface ToolExecutionLogFieldRefs {
  readonly id: Prisma.FieldRef<"ToolExecutionLog", 'String'>
  readonly conversationId: Prisma.FieldRef<"ToolExecutionLog", 'String'>
  readonly userId: Prisma.FieldRef<"ToolExecutionLog", 'String'>
  readonly toolName: Prisma.FieldRef<"ToolExecutionLog", 'String'>
  readonly toolCallId: Prisma.FieldRef<"ToolExecutionLog", 'String'>
  readonly paramsHash: Prisma.FieldRef<"ToolExecutionLog", 'String'>
  readonly executionTime: Prisma.FieldRef<"ToolExecutionLog", 'Int'>
  readonly resultHash: Prisma.FieldRef<"ToolExecutionLog", 'String'>
  readonly success: Prisma.FieldRef<"ToolExecutionLog", 'Boolean'>
  readonly errorMessage: Prisma.FieldRef<"ToolExecutionLog", 'String'>
  readonly resultSize: Prisma.FieldRef<"ToolExecutionLog", 'Int'>
  readonly cacheHit: Prisma.FieldRef<"ToolExecutionLog", 'Boolean'>
  readonly metadata: Prisma.FieldRef<"ToolExecutionLog", 'String'>
  readonly createdAt: Prisma.FieldRef<"ToolExecutionLog", 'DateTime'>
}
    

// Custom InputTypes
/**
 * ToolExecutionLog findUnique
 */
export type ToolExecutionLogFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ToolExecutionLog
   */
  select?: Prisma.ToolExecutionLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ToolExecutionLog
   */
  omit?: Prisma.ToolExecutionLogOmit<ExtArgs> | null
  /**
   * Filter, which ToolExecutionLog to fetch.
   */
  where: Prisma.ToolExecutionLogWhereUniqueInput
}

/**
 * ToolExecutionLog findUniqueOrThrow
 */
export type ToolExecutionLogFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ToolExecutionLog
   */
  select?: Prisma.ToolExecutionLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ToolExecutionLog
   */
  omit?: Prisma.ToolExecutionLogOmit<ExtArgs> | null
  /**
   * Filter, which ToolExecutionLog to fetch.
   */
  where: Prisma.ToolExecutionLogWhereUniqueInput
}

/**
 * ToolExecutionLog findFirst
 */
export type ToolExecutionLogFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ToolExecutionLog
   */
  select?: Prisma.ToolExecutionLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ToolExecutionLog
   */
  omit?: Prisma.ToolExecutionLogOmit<ExtArgs> | null
  /**
   * Filter, which ToolExecutionLog to fetch.
   */
  where?: Prisma.ToolExecutionLogWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ToolExecutionLogs to fetch.
   */
  orderBy?: Prisma.ToolExecutionLogOrderByWithRelationInput | Prisma.ToolExecutionLogOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ToolExecutionLogs.
   */
  cursor?: Prisma.ToolExecutionLogWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ToolExecutionLogs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ToolExecutionLogs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ToolExecutionLogs.
   */
  distinct?: Prisma.ToolExecutionLogScalarFieldEnum | Prisma.ToolExecutionLogScalarFieldEnum[]
}

/**
 * ToolExecutionLog findFirstOrThrow
 */
export type ToolExecutionLogFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ToolExecutionLog
   */
  select?: Prisma.ToolExecutionLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ToolExecutionLog
   */
  omit?: Prisma.ToolExecutionLogOmit<ExtArgs> | null
  /**
   * Filter, which ToolExecutionLog to fetch.
   */
  where?: Prisma.ToolExecutionLogWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ToolExecutionLogs to fetch.
   */
  orderBy?: Prisma.ToolExecutionLogOrderByWithRelationInput | Prisma.ToolExecutionLogOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ToolExecutionLogs.
   */
  cursor?: Prisma.ToolExecutionLogWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ToolExecutionLogs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ToolExecutionLogs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ToolExecutionLogs.
   */
  distinct?: Prisma.ToolExecutionLogScalarFieldEnum | Prisma.ToolExecutionLogScalarFieldEnum[]
}

/**
 * ToolExecutionLog findMany
 */
export type ToolExecutionLogFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ToolExecutionLog
   */
  select?: Prisma.ToolExecutionLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ToolExecutionLog
   */
  omit?: Prisma.ToolExecutionLogOmit<ExtArgs> | null
  /**
   * Filter, which ToolExecutionLogs to fetch.
   */
  where?: Prisma.ToolExecutionLogWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ToolExecutionLogs to fetch.
   */
  orderBy?: Prisma.ToolExecutionLogOrderByWithRelationInput | Prisma.ToolExecutionLogOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ToolExecutionLogs.
   */
  cursor?: Prisma.ToolExecutionLogWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ToolExecutionLogs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ToolExecutionLogs.
   */
  skip?: number
  distinct?: Prisma.ToolExecutionLogScalarFieldEnum | Prisma.ToolExecutionLogScalarFieldEnum[]
}

/**
 * ToolExecutionLog create
 */
export type ToolExecutionLogCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ToolExecutionLog
   */
  select?: Prisma.ToolExecutionLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ToolExecutionLog
   */
  omit?: Prisma.ToolExecutionLogOmit<ExtArgs> | null
  /**
   * The data needed to create a ToolExecutionLog.
   */
  data: Prisma.XOR<Prisma.ToolExecutionLogCreateInput, Prisma.ToolExecutionLogUncheckedCreateInput>
}

/**
 * ToolExecutionLog createMany
 */
export type ToolExecutionLogCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ToolExecutionLogs.
   */
  data: Prisma.ToolExecutionLogCreateManyInput | Prisma.ToolExecutionLogCreateManyInput[]
}

/**
 * ToolExecutionLog createManyAndReturn
 */
export type ToolExecutionLogCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ToolExecutionLog
   */
  select?: Prisma.ToolExecutionLogSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ToolExecutionLog
   */
  omit?: Prisma.ToolExecutionLogOmit<ExtArgs> | null
  /**
   * The data used to create many ToolExecutionLogs.
   */
  data: Prisma.ToolExecutionLogCreateManyInput | Prisma.ToolExecutionLogCreateManyInput[]
}

/**
 * ToolExecutionLog update
 */
export type ToolExecutionLogUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ToolExecutionLog
   */
  select?: Prisma.ToolExecutionLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ToolExecutionLog
   */
  omit?: Prisma.ToolExecutionLogOmit<ExtArgs> | null
  /**
   * The data needed to update a ToolExecutionLog.
   */
  data: Prisma.XOR<Prisma.ToolExecutionLogUpdateInput, Prisma.ToolExecutionLogUncheckedUpdateInput>
  /**
   * Choose, which ToolExecutionLog to update.
   */
  where: Prisma.ToolExecutionLogWhereUniqueInput
}

/**
 * ToolExecutionLog updateMany
 */
export type ToolExecutionLogUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ToolExecutionLogs.
   */
  data: Prisma.XOR<Prisma.ToolExecutionLogUpdateManyMutationInput, Prisma.ToolExecutionLogUncheckedUpdateManyInput>
  /**
   * Filter which ToolExecutionLogs to update
   */
  where?: Prisma.ToolExecutionLogWhereInput
  /**
   * Limit how many ToolExecutionLogs to update.
   */
  limit?: number
}

/**
 * ToolExecutionLog updateManyAndReturn
 */
export type ToolExecutionLogUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ToolExecutionLog
   */
  select?: Prisma.ToolExecutionLogSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ToolExecutionLog
   */
  omit?: Prisma.ToolExecutionLogOmit<ExtArgs> | null
  /**
   * The data used to update ToolExecutionLogs.
   */
  data: Prisma.XOR<Prisma.ToolExecutionLogUpdateManyMutationInput, Prisma.ToolExecutionLogUncheckedUpdateManyInput>
  /**
   * Filter which ToolExecutionLogs to update
   */
  where?: Prisma.ToolExecutionLogWhereInput
  /**
   * Limit how many ToolExecutionLogs to update.
   */
  limit?: number
}

/**
 * ToolExecutionLog upsert
 */
export type ToolExecutionLogUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ToolExecutionLog
   */
  select?: Prisma.ToolExecutionLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ToolExecutionLog
   */
  omit?: Prisma.ToolExecutionLogOmit<ExtArgs> | null
  /**
   * The filter to search for the ToolExecutionLog to update in case it exists.
   */
  where: Prisma.ToolExecutionLogWhereUniqueInput
  /**
   * In case the ToolExecutionLog found by the `where` argument doesn't exist, create a new ToolExecutionLog with this data.
   */
  create: Prisma.XOR<Prisma.ToolExecutionLogCreateInput, Prisma.ToolExecutionLogUncheckedCreateInput>
  /**
   * In case the ToolExecutionLog was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ToolExecutionLogUpdateInput, Prisma.ToolExecutionLogUncheckedUpdateInput>
}

/**
 * ToolExecutionLog delete
 */
export type ToolExecutionLogDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ToolExecutionLog
   */
  select?: Prisma.ToolExecutionLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ToolExecutionLog
   */
  omit?: Prisma.ToolExecutionLogOmit<ExtArgs> | null
  /**
   * Filter which ToolExecutionLog to delete.
   */
  where: Prisma.ToolExecutionLogWhereUniqueInput
}

/**
 * ToolExecutionLog deleteMany
 */
export type ToolExecutionLogDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ToolExecutionLogs to delete
   */
  where?: Prisma.ToolExecutionLogWhereInput
  /**
   * Limit how many ToolExecutionLogs to delete.
   */
  limit?: number
}

/**
 * ToolExecutionLog without action
 */
export type ToolExecutionLogDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ToolExecutionLog
   */
  select?: Prisma.ToolExecutionLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ToolExecutionLog
   */
  omit?: Prisma.ToolExecutionLogOmit<ExtArgs> | null
}
